### ISSUE TITLE
Cannot start solidity-develop - npm ERR! missing script: start

### ISSUE THREAD

**Issue by raky35** [ethereum/remix-ide#1017]
Hello Team, My apologies for ignorance i am new , i am trying to setup the local environment of browser-solidity in my mac . 
sh-3.2# npm -version
o/p 5.6.0
sh-3.2# node -v
o/p v8.9.4
sh-3.2# cd solidity-develop/
i ran sudo npm install -g npm and  npm init all looks good so far ,i see package.json is genrated
  
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
 but when i run sh-3.2# npm start  i get error npm ERR! missing script: start  not sure wht i have add more to get starting local env. 

Request experts to throw light on issue if possible please.
Many thanks in Advance 
Cheers
raky

**Comment by yann300** [comment]
just try to run
```
npm install
npm run build && npm run serve
```

**Comment by raky35** [comment]
Much appreciated  Yann for your advice, i have deleted 'package.json' from solidity-develop and run advised commands as per below ...
sh-3.2# npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN solidity-develop@3.0.0 No repository field.

up to date in 0.129s
sh-3.2# npm install
npm WARN XXXX No description
npm WARN XXXXX No repository field.
npm WARN XXXXX No license field.

up to date in 2.214s
sh-3.2# npm run build && npm run serve
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-01-25T12_40_40_078Z-debug.log

Any idea please what is going wrong , very frustrating not sure what i am missing ...  
Thanks 
Kind Regards 
raky

**Comment by raky35** [comment]
sh-3.2# cd solidity-develop/
sh-3.2# npm install
npm WARN XXXX No description
npm WARN XXXX No repository field.
npm WARN XXXX No license field.

up to date in 5.331s
sh-3.2#

**Comment by raky35** [comment]
i am trying setup in MacOs

**Comment by iurimatias** [comment]
@raky35 try ```npm start``` then go to http://localhost:8080

**Comment by raky35** [comment]
Thanks but still no luck .. 
sh-3.2# npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-01-26T15_07_31_677Z-debug.log
sh-3.2#

**Comment by raky35** [comment]
info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:402:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:357:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:400:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:332:20)
4 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)

**Comment by iurimatias** [comment]
to be clear, are you trying to start ```browser-solidity``` or build the  ```solidity``` compiler? to use browser-solidity/remix you don't actually need to compile the solidity compiler as it will be included

**Comment by raky35** [comment]
Hi iurimatias , Appreciate ,ur help can u please read my above posting and advice if i missing anything or steps to run and see the blower window...  many thanks Cheers raky

**Comment by raky35** [comment]
Hi Team, Now i got another code which is also throwing me error ... thanks regards raky

Last login: Mon Jan 29 11:17:16 on console
XXXX:~ XXXX$ cd Documents/SOFT
-bash: cd: Documents/SOFT: No such file or directory
XXXX:~ XXXX $ cd Documents/SOFTWARE/browser-solidity/
XXXX:browser-solidity XXXX $ ls
LICENSE.md		ci			nightwatch.js
README.md		contracts		package.json
assets			icon.png		src
background.js		index.html		test
best-practices.md	manifest.json		test-browser
XXXX:browser-solidity XXXX $ sudo su
Password:
sh-3.2# npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/ethereum/remixd.git /var/root/.npm/_cacache/tmp/git-clone-01b56919
npm ERR! fatal: could not create leading directories of '/var/root/.npm/_cacache/tmp/git-clone-01b56919': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-01-29T16_09_11_197Z-debug.log
sh-3.2# cd ..
sh-3.2# ls
.DS_Store				jaxrs-ri-2
.installationinformation		jbdevstudio.app
Django-1.10.6				jboss-6.1.0.Final
DjangoNosql				jboss-as-7.1.1.Final
Eclipse.app				jboss-fuse-6.2.1.redhat-084
IBM Integration Bus 10.0.1213.4.app	jbossesb-server-4.12
InstallConfigRecord.xml			kanboard
JBoss-EULA.html				mongodb_3.4.4
PostgressDriverVer9.4			mqlight-1.0.2016062300
Soapui					mqlight-developer-1.0.3.0-L160912
Uninstaller				mysql-odbc5.3.6
VirtualEnvironments			myvirtualenv
angular-cli-master			openldap-2.4.44.2
apache-activemq-5.9.0			readme.txt
apache-cxf-2.3.2			runtimes
apache-cxf-2.7.12			solidity-develop
apache-tomcat-8.0.30			studio
apacheds-2.0.0-M23			subversion-1.9.4
browser-solidity			subversion-1.9.4.zip
db-6.0.20				wildfly-9.0.2.Final
eclipseneon
sh-3.2# sudo chown -R XXXX:staff browser-solidity/
sh-3.2# sudo chmod -R  755 browser-solidity/
sh-3.2# ls
.DS_Store				jaxrs-ri-2
.installationinformation		jbdevstudio.app
Django-1.10.6				jboss-6.1.0.Final
DjangoNosql				jboss-as-7.1.1.Final
Eclipse.app				jboss-fuse-6.2.1.redhat-084
IBM Integration Bus 10.0.1213.4.app	jbossesb-server-4.12
InstallConfigRecord.xml			kanboard
JBoss-EULA.html				mongodb_3.4.4
PostgressDriverVer9.4			mqlight-1.0.2016062300
Soapui					mqlight-developer-1.0.3.0-L160912
Uninstaller				mysql-odbc5.3.6
VirtualEnvironments			myvirtualenv
angular-cli-master			openldap-2.4.44.2
apache-activemq-5.9.0			readme.txt
apache-cxf-2.3.2			runtimes
apache-cxf-2.7.12			solidity-develop
apache-tomcat-8.0.30			studio
apacheds-2.0.0-M23			subversion-1.9.4
browser-solidity			subversion-1.9.4.zip
db-6.0.20				wildfly-9.0.2.Final
eclipseneon
sh-3.2# cd browser-solidity/
sh-3.2# ls
.babelrc		background.js		manifest.json
.gitignore		best-practices.md	nightwatch.js
.travis.yml		ci			package.json
LICENSE.md		contracts		src
README.md		icon.png		test
assets			index.html		test-browser
sh-3.2# npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/ethereum/remixd.git /var/root/.npm/_cacache/tmp/git-clone-5b1ff433
npm ERR! fatal: could not create leading directories of '/var/root/.npm/_cacache/tmp/git-clone-5b1ff433': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-01-29T16_12_02_260Z-debug.log
sh-3.2# npm run build && npm run serve

> browser-solidity@0.0.0 build /Users/XXXX/Documents/SOFTWARE/browser-solidity
> browserify src/index.js -o build/app.js

sh: browserify: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! browser-solidity@0.0.0 build: `browserify src/index.js -o build/app.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the browser-solidity@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-01-29T16_12_39_255Z-debug.log
sh-3.2# sudo npm install -g npm
/var/root/.npm-global/bin/npm -> /var/root/.npm-global/lib/node_modules/npm/bin/npm-cli.js
/var/root/.npm-global/bin/npx -> /var/root/.npm-global/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.6.0
updated 1 package in 14.089s
sh-3.2# npm start 

> browser-solidity@0.0.0 start /Users/XXXX/Documents/SOFTWARE/browser-solidity
> npm-run-all -lpr serve watch onchange remixd

sh: npm-run-all: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! browser-solidity@0.0.0 start: `npm-run-all -lpr serve watch onchange remixd`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the browser-solidity@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-01-29T16_18_55_152Z-debug.log
sh-3.2# clear 

sh-3.2# sudo npm install -g npm
/var/root/.npm-global/bin/npm -> /var/root/.npm-global/lib/node_modules/npm/bin/npm-cli.js
/var/root/.npm-global/bin/npx -> /var/root/.npm-global/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.6.0
updated 1 package in 9.873s
sh-3.2# npm run build && npm run serve

> browser-solidity@0.0.0 build /Users/XXXX/Documents/SOFTWARE/browser-solidity
> browserify src/index.js -o build/app.js

sh: browserify: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! browser-solidity@0.0.0 build: `browserify src/index.js -o build/app.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the browser-solidity@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-01-29T16_21_56_483Z-debug.log
sh-3.2# sudo npm install  npm
npm notice created a lockfile as package-lock.json. You should commit this file.
+ npm@5.6.0
added 476 packages in 13.459s
sh-3.2# ls
.babelrc		best-practices.md	node_modules
.gitignore		ci			package-lock.json
.travis.yml		contracts		package.json
LICENSE.md		icon.png		src
README.md		index.html		test
assets			manifest.json		test-browser
background.js		nightwatch.js
sh-3.2# sudo npm install  npm
npm notice created a lockfile as package-lock.json. You should commit this file.
+ npm@5.6.0
updated 1 package in 11.15s
sh-3.2# sudo npm run serve

> browser-solidity@0.0.0 serve /Users/XXXX/Documents/SOFTWARE/browser-solidity
> execr --silent http-server .

sh: execr: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! browser-solidity@0.0.0 serve: `execr --silent http-server .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the browser-solidity@0.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-01-29T16_24_04_234Z-debug.log
sh-3.2# sudo npm run server
npm ERR! missing script: server

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-01-29T16_24_07_498Z-debug.log
sh-3.2# sudo npm run serve

> browser-solidity@0.0.0 serve /Users/XXXX/Documents/SOFTWARE/browser-solidity
> execr --silent http-server .

sh: execr: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! browser-solidity@0.0.0 serve: `execr --silent http-server .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the browser-solidity@0.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-01-29T16_24_34_946Z-debug.log
sh-3.2#  npm run build && npm run serve

> browser-solidity@0.0.0 build /Users/XXXX/Documents/SOFTWARE/browser-solidity
> browserify src/index.js -o build/app.js

sh: browserify: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! browser-solidity@0.0.0 build: `browserify src/index.js -o build/app.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the browser-solidity@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-01-29T16_25_15_501Z-debug.log
sh-3.2# vi /var/root/.npm/_logs/2018-01-29T16_25_15_501Z-debug.log

12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid browser-solidity@0.0.0
14 verbose cwd /Users/XXXX/Documents/SOFTWARE/browser-solidity
15 verbose Darwin 17.4.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
17 verbose node v8.9.4
18 verbose npm  v5.6.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error browser-solidity@0.0.0 build: `browserify src/index.js -o build/app.js`
23 error spawn ENOENT
24 error Failed at the browser-solidity@0.0.0 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
![screen shot 2018-01-29 at 16 29 50](https://user-images.githubusercontent.com/7769590/35521470-ba9a2d28-0511-11e8-9e1e-5208da5cf412.png)

**Comment by yann300** [comment]
the installation scripts has been changed a little. please could you give another try?
closing now, please reopen if necessary

**Comment by gravyplaya** [comment]
still an issue.

**Comment by yann300** [comment]
@gravyplaya could you please post a description of the error you got?
