### ISSUE TITLE
[Plugins] add a child->parent communication

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1058]
in `PluginManager.js`, we should listen on message from children. 
**only** manage the one which currently has the focus.

**Comment by serapath** [comment]
> I don't think merging these 2 is good. that's good to keep separating the html view of plugins tab and how plugin API actually work.

I am not sure what you mean.
* I imagine the `plugin tab` would have a "constructor" to make new plugin tabs which expose the standard `plugin API`
* also the plugin constructor can statically remember all it's instances and communicate between them (e.g. unfocus and focus a different instance)
