### ISSUE TITLE
[Plugins] Ability for plugin to switch file and go to specific line

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1059]
API
```
{
 type: 'editor',
 function: 'goToLine'
 value: {
     fileName: fileName,
     line: line,
     column: column
 }
}
```

that'll use:

```
fileManager.switchFile(name)
editor.gotoLine(line, col)
```

**Comment by serapath** [comment]
I tried to think a bit more about the `API`, and maybe you are right with this approach.
* the `type` seems to represent an `address` (like which "entity" is addressed to do something)
* the `function` seems to say what type of message or operation is requested to happen
* the `value` is the data or payload associated with the message or operation

We would probably need to specify the `API` a plugin maker can use.
* To me, the message or operation type in the example above seems to be `goToLine`
* the address or part of the app that is responsible to process the message or operation is `editor`

**another example** could be:
* Maybe the remix-ide could allow a plugin to switch the content of a dropdown
    * the `compile`, `run` and `settings` tab have dropdowns
    * so a plugin might specify the message or operation type as `selectInDropdown`
    * the value might contain the new value for the dropdown
    * the address would be e.g.`compileTab/dropdown`, `run/dropdown`, `settings/dropdown`

If the `type` is to be understood as a message, then `value` would describe a `payload` or `data`
If the `type` is to be understood as an operation, then `value` would describe `arguments`

So a request could look like:
```js
var args = { fileName, line, column }
var event = { type: 'goToLine', key: 'editor', val: args }

event.type // describes the kind of "message" or "operation/command"
event.key // describes the "address" of the apps part or component which should process the request
event.val // describes the "data" or "payload" or "arguments" for the message or operation
```

**Comment by yann300** [comment]
Defining component like `['compileTab', 'dropdown']` would mean that the plugin could directly update ui core component of remix, that should not be the case. `function` or `operation (in your case)` should only be high level execution.
Given that I don't really see the point of having this finegrained definition of targeted components ...
But yeah that might be needed in the future.

we could support both
`var event = { key: ['editor'], op: 'goToLine', val: { fileName, line, column } }`
`var event = { key: 'editor', op: 'goToLine', val: { fileName, line, column } }`
would mean the same.

OK for `operation` but I would prefer to keep `type` for that component name.

**Comment by serapath** [comment]
+1 i think supporting both is nice

otherwise - i'm not saying that plugins would be allowed to have all this "fine grained control", but that i would of course ask the user to grant permissions first and also to be able to revoke permissions later
This is super important i think.
Also, it's one thing that a plugin specifies something like `'compileTab', 'dropdown'` and another whether in browser-solidity we listen to that path and allow it or prompt the user or not.

So I'm not proposing to grant this kind of access automatically
