### ISSUE TITLE
[Plugins] Warn and confirm if plugin attempt to use API that modify user input and selection

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1062]
Plugin API 'll be mostly used to read information from Remix.

In case a function is going to change values (e.g modifying the content of the editor), we have to warn the user what the plugin is trying to do.
A checkbox should allow the user to accept any other request of the same type by the current plugin for the rest of the session ( a session being a page load ).
These options are not persisted.

**Comment by LianaHus** [comment]
I assume this can be closed since we have a permission system @yann300
