### ISSUE TITLE
Simplify StateManager hook for etheruemjs-vm

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#1073]
Depends on #1063.

The statemanager code https://github.com/ethereum/browser-solidity/blob/5b164fc004a283c280134176113777974d413bd8/src/execution-context.js#L67-L71 can now be simplified: https://github.com/ethereumjs/ethereumjs-vm#new-vmopts

**Comment by axic** [comment]
@yann300 you may be doing this already with #1620 ?

**Comment by LianaHus** [comment]
@yann300 ?
