### ISSUE TITLE
у меня не работает

### ISSUE THREAD

**Issue by slonik6663444** [ethereum/remix-ide#1078]
$ npm start

> browser-solidity@0.0.0 start R:\sunduchek\test\fin_2\browser-solidity
> npm-run-all -lpr serve watch onchange remixd

[remixd  ]
[remixd  ] > browser-solidity@0.0.0 remixd R:\sunduchek\test\fin_2\browser-solidity
[remixd  ] > node ./node_modules/remixd/src/main.js -s ./contracts
[remixd  ]
[onchange]
[onchange] > browser-solidity@0.0.0 onchange R:\sunduchek\test\fin_2\browser-solidity
[onchange] > onchange build/app.js -- npm-run-all lint
[onchange]
[serve   ]
[serve   ] > browser-solidity@0.0.0 serve R:\sunduchek\test\fin_2\browser-solidity
[serve   ] > execr --silent http-server .
[serve   ]
[watch   ]
[watch   ] > browser-solidity@0.0.0 watch R:\sunduchek\test\fin_2\browser-solidity
[watch   ] > watchify src/index.js -dv -p browserify-reload -o build/app.js
[watch   ]
[remixd  ] example: --dev-path /home/devchains/chain1 --mist --geth --frontend /home/frontend --frontend-port 8084 --auto-mine
[remixd  ]
[remixd  ]   Usage: main -s <shared folder>
[remixd  ]
[remixd  ]   Provide a two ways connection between the local computer and Remix IDE
[remixd  ]
[remixd  ]
[remixd  ]   Options:
[remixd  ]
[remixd  ]     -s, --shared-folder <path>            Folder to share with Remix IDE
[remixd  ]     -m, --mist                            start mist
[remixd  ]     -g, --geth                            start geth
[remixd  ]     -p, --dev-path <dev-path>             Folder used by mist/geth to start the development instance
[remixd  ]     -f, --frontend <front-end>            Folder that should be served by remixd
[remixd  ]     -p, --frontend-port <front-end-port>  Http port used by the frontend (default 8082)
[remixd  ]     -a, --auto-mine                       mine pending transactions
[remixd  ]     -r, --rpc <cors-domains>              start rpc server. Values are CORS domain
[remixd  ]     -rp, --rpc-port                       rpc server port (default 8545)
[remixd  ]     -h, --help                            output usage information
[remixd  ] [WARN] Any application that runs on your computer can potentially read from and write to all files in the directory.
[remixd  ] [WARN] Symbolinc links are not forwarded to Remix IDE
[remixd  ]
[remixd  ] [WARN] Symbolic link modification not allowed : ./contracts | R:\sunduchek\test\fin_2\browser-solidity\contracts
[remixd  ] Shared folder : ./contracts
[remixd  ] Wed Feb 14 2018 18:59:55 GMT+0200 (Финляндия (зима)) Remixd is listening on 127.0.0.1:65520
[watch   ] WS server listening on  51065
[watch   ] Error: Cannot find module 'swarmgw' from 'R:\sunduchek\test\fin_2\browser-solidity\src\app\compiler'
[watch   ] { Error: ENOENT: no such file or directory, open 'R:\sunduchek\test\fin_2\browser-solidity\build\app.js'
[watch   ]   errno: -4058,
[watch   ]   code: 'ENOENT',
[watch   ]   syscall: 'open',
[watch   ]   path: 'R:\\sunduchek\\test\\fin_2\\browser-solidity\\build\\app.js' }
[watch   ] Error: Cannot find module './soljson.js' from 'R:\sunduchek\test\fin_2\browser-solidity\node_modules\remix-solidity\node_modules\solc'
[watch   ] Error: Cannot find module 'keccakjs' from 'R:\sunduchek\test\fin_2\browser-solidity\node_modules\ethereumjs-vm\node_modules\ethereumjs-util'
[watch   ] Error: Cannot find module 'swarmgw' from 'R:\sunduchek\test\fin_2\browser-solidity\src\app\contract'
[watch   ] Error: Cannot find module 'keccakjs' from 'R:\sunduchek\test\fin_2\browser-solidity\node_modules\ethereumjs-abi\node_modules\ethereumjs-util'
[watch   ] Error: Cannot find module 'keccakjs' from 'R:\sunduchek\test\fin_2\browser-solidity\node_modules\ethereumjs-account\node_modules\ethereumjs-util'
[watch   ] Error: Cannot find module 'keccakjs' from 'R:\sunduchek\test\fin_2\browser-solidity\node_modules\remix-solidity\node_modules\ethereumjs-util'
[remixd  ] Wed Feb 14 2018 19:00:38 GMT+0200 (Финляндия (зима)) Received request for /
[remixd  ] Wed Feb 14 2018 19:01:06 GMT+0200 (Финляндия (зима)) Received request for /
[remixd  ] Wed Feb 14 2018 19:01:58 GMT+0200 (Финляндия (зима)) Received request for /

**Comment by ivan3a** [comment]
Do you install dependencies before "npm start" with "npm install"

**Comment by yann300** [comment]
closing
