### ISSUE TITLE
TODO list from Vitalik

### ISSUE THREAD

**Issue by redsquirrel** [ethereum/remix-ide#109]
via: https://blog.ethereum.org/2016/06/19/thinking-smart-contract-security/
- throw a warning if a contract does not provably consume less than 2300 gas if called with no data
- throw a warning if a function does not provably terminate within a safe amount of gas
- Variable names might be colored (eg. RGB based on the first three bytes of the hash of the name)
- perhaps a heuristic warning might be given if two variable names are too close to each other

**Comment by chriseth** [comment]
Note that the provider does provide upper bounds for gas usage by employing symbolic execution. Having said that, it ignores gas sent to sub-calls, that should probably be changed.

We should add a proper warning for the fallback function and perhaps a slightly less annoying warning for other functions. Furthermore, the warning should not be shown if the fallback function throws on purpose - not sure yet how to do detect that properly.

**Comment by yann300** [comment]
@chriseth @soad003 we should perhaps add a static analysis module

**Comment by chriseth** [comment]
@yann300 hm? We already have one. From the four items, only the last two are still remaining.
