### ISSUE TITLE
Possible Library sol file name max length issue.

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/remix-ide#1110]
I have a file name called eBlocBrokerLib.sol file which contains a library code. remix.solidity does not see this function. 

Example error:
`creation of eBlocBroker errored: Error deploying required libraries: Cannot find library reference browser/EblocBroker.sol:eBlocBrokerL`

When I change the file's name into Lib.sol, the error is fixed. It took a day for me to find this bug. 
- Is there any file name length or some other bug may exist?

**Comment by axic** [comment]
@yann300 Remix should be using the `linkReferences` of the JSON output as opposed to running linking using the old method. What is it doing at the moment?

**Comment by yann300** [comment]
it should do both
https://github.com/ethereum/remix/blob/master/remix-lib/src/execution/txFormat.js#L130 
have to check that up

**Comment by axic** [comment]
Also you could start using the linker from solc-js: https://github.com/ethereum/solc-js/blob/master/linker.js

In the process of adding support for linking via `linkReferences` but after that it will be complete. (It also has unit tests)

**Comment by axic** [comment]
Another better solution would be giving the libraries addresses to standard json and the compiler would do the job.

Also there is linking support solc-js now: https://github.com/ethereum/solc-js#linking-bytecode

**Comment by yann300** [comment]
that is fixed on remix-alpha.ethereum.org
