### ISSUE TITLE
Use request module in gist and version loading

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#1116]
The modern part of the code uses `request` instead of Jquery: https://github.com/ethereum/remix-ide/blob/master/src/app/compiler/compiler-imports.js#L9

These two old instances still use Jquery:
- https://github.com/ethereum/remix-ide/blob/master/src/app.js#L506
- https://github.com/ethereum/remix-ide/blob/master/src/app/tabs/settings-tab.js#L179

**Comment by bitpshr** [comment]
I took care of this in #1164.
