### ISSUE TITLE
[Plugins] Allow config file

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1117]
Some plugins might need to store config files.
proposal:
 - [x] config files are stored in the browser storage
 - [x] in the UI there are shown in a new explorer (`config` explorer)
 - [x] each plugin / ( or event remix module ) has its own folder inside `config` . e.g if the name of the plugin is `abc`, the plugin has access read / write  to the `config/abc` folder.
 when a plugin is first installed (or anytime actually) he can check the content of its config folder.
 - [ ] sometimes it would be handy to copy config file: from the `config/<plugin>` to localhost or the other way around. (that way we can import/export config files)
- [ ] add an event emitter to the config so that plugins can be "reactive" to the user changing the config

**Comment by duaraghav8** [comment]
cc @UtkarshGupta-CS

**Comment by serapath** [comment]
:+1: i like it

**one more suggestion:**
i would recommend to add an event emitter to the config so that plugins can be "reactive" to the user changing the config

**Comment by yann300** [comment]
PR https://github.com/ethereum/remix-ide/pull/1120

**Comment by yann300** [comment]
@serapath

**Comment by yann300** [comment]
@UtkarshGupta-CS @duaraghav8 
the PR ( #1120 ) has been pushed to http://remix-alpha.ethereum.org.
That should be ok, please let us know if there's any issue with that. thanks!
