### ISSUE TITLE
Deployed contract does not show up on the remix.solidity

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/remix-ide#1121]
I am using a private ethereum network and I am using remix.solidity (http://remix.ethereum.org) to deploy my contract. 

First I connect into my private-network:

`Run` => `Environment` and selected `Web3 Provide`
There will be a window opening asking “Are you sure want to connect to an ethereum node?” Clicked OK. Please note that, the connection is established to my private network and there is no problem on that side.

[![enter image description here][1]][1]

Than I deployed my contract via on `Run` tab and clicked `Create` button that is next to my contract. 

[![enter image description here][2]][2]

After some time, I can see that my contract (simple hello-world contract) is deployed on my network status (as the transaction it show up), but I do not see the deployed contract on the remix solidity browser (on console it hangs as `creation of greeter pending...`), so I cannot obtain its address and access into my contract.

**[Q]** What should I do to see the address of deployed contract on the remix solidity? Does anyone face with similar bug?

Thanks for the input.

Also I asked on here: https://ethereum.stackexchange.com/q/41224/4575

  [1]: https://i.stack.imgur.com/MqXnx.png
  [2]: https://i.stack.imgur.com/agUD0.png

**Comment by yann300** [comment]
you need to start mining on your private node to mine/validat the transaction.
how do you start you private network?

**Comment by avatar-lavventura** [comment]
I know that, I need to do mining, and I am doing mining thats why I was able to see the deployed transaction on the network status, but remix.solidity does not show it. There is nothing wrong with mining side. @yann300

**Comment by avatar-lavventura** [comment]
Please also note that I have tried using remix solidity with `http`. Its rather `bug` than a `question`. @yann300

**Comment by yann300** [comment]
could you try using remix-alpha.ethereum.org ?

**Comment by avatar-lavventura** [comment]
It has been solved when I used `remix-alpha.ethereum.org`. Please note that each addressed shown double times and the addresses section.

**Comment by avatar-lavventura** [comment]
I was using inside a VM machine. My issue was happening because of that. @yann300

**Comment by yann300** [comment]
closing this.
@avatar-lavventura thanks for the little feedback
"Please note that each addressed shown double times on the addresses section"
I will create an issue

**Comment by shrikant-ku** [comment]
Thanks alot for telling your solution of using remix-alpha.ethereum.org.
