### ISSUE TITLE
Error in accessing variable [Javascript VM]

### ISSUE THREAD

**Issue by cookedsteak** [ethereum/remix-ide#1138]
Simple contract code as follows
```
pragma solidity ^0.4.18;

contract A {
    uint256 public amount;
    
    function A() public {
        amount = 100;
    }
    function minus() public {
        amount = amount - 1;
    }
}

contract B {
    A public a;
    
    function B() public {
        a = new A();
        a.minus();
    } 
}
```
Error occurs:
`
call to A.amount errored: Cannot read property 'length' of undefined
`
when I want to print `amount` after the deployment.
And the main problem I think is 
`a.minus();` in the constructor of contract B.

These codes are fine on testnet.

**Comment by yann300** [comment]
I can't reproduce. Seems you are using the `atAddress` feature right? what if you `create` the contract B first?
there 's indeed an issue here, but that is more related on how we catch error. We should display something else than just `Cannot read property 'length' of undefined`.

**Comment by yann300** [comment]
we've updated remix.ethereum.org today. please reopen if this is still not fixed.
