### ISSUE TITLE
[Plugin] source code highlighting & annotations

### ISSUE THREAD

**Issue by serapath** [ethereum/remix-ide#1139]
```js
// editor api as usable inside of remix
var style = `.foobar { background-color: red;}`
document.head.appendChild(style)

var range = { start: { line:0, column: 2 }, end: {line:19, column:10 } }
var file = 'browser/ballot.sol'
var classname = 'foobar'
EDITOR.addMarker(range, file, classname/*, "fullLine" */)
```

```js
// inside plugin
var range = { start: { line:0, column: 2 }, end: {line:19, column:10 } }
var file = 'browser/ballot.sol'
var classname = 'foobar'
var origin = 'http://127.0.0.1:8080' // or 'http://remix.ethereum.org'
var method = 'editor.addMarker' // or 'setConfig' or 'getConfig'
var CALLid = 123

window.parent.postMessage(JSON.stringify({
      type: method,
      arguments: [range, file, classname],
      id: CALLid
}), origin)

window.addEventListener('message', function (msg) {
  var { id, type, error, result } = msg // if response
  var { type, value } = msg // if regular message
 
  var { type, arguments, id } = msg  // if you get called and offer API to remix

  console.log('receiveMessage', id, type, error, result, value)
}, false)
```

**Comment by aarlt** [comment]
@serapath nice! thanks a lot! i will give that a try as soon as possible

**Comment by yann300** [comment]
@serapath @aarlt is the goal here only to highlight source code ? is it possible to give a bit more explanation in the title

**Comment by aarlt** [comment]
@yann300 the main goal is to enable colouring of individual ranges. Additionally to that it would be nice to enable annotations on lines. To enable that we will need to define some messages that can be used by plugins to communicate those things to the remix-ide. 

From my point of view we will need three messages:
- reset message - to reset the state of the highlighting  & annotations - so all highlighted regions and annotations made by the plugin calling it will be removed
- color range/line message - an individual message that basically consists of `(file, range, color)` where `file` is the file that is opened, `range` is defined by a start and an end point. `a point` is a tuple of (line, column) - if `start.column == 0`, `end.column==0` the full line(s) can be coloured, the `color` is a tuple of two colours (foreground-color (text-color), background-color), .
- line-annotation message -  it would also be nice to use these line annotations - i don't know the exact term - but on the line ruler in remix it seem to be possible to place small icons. On mouse-over they are able to show a specified string. I want to be able to set those with (file, line-number, color, message-string), where `file` refers to the opened file, `color` is just the color with that the icon will be filled, `line-number` the line where the icon will be placed, and the `message-string` should be shown on mouse-over.

From my point of view these three messages will sufficient to visualize test-reports & code coverage within remix. Probably, we will need some optimizations: we could group individual messages together (array of those messages). This may improve the highlighting performance. But lets probably focus on optimizations later.

We should also think about how stuff will be done if multiple plugins are using the code-highlighting and annotation feature. Also I'm not sure about the behaviour, if those plugin range colouring is somehow overlapping with the range-colouring of remix.

@serapath probably we should change the title to something like "plugin: code highlighting & line annotations".

**Comment by serapath** [comment]
### brainstorming iframe api used by the plugin system

```js
var tmpID, msg, IDs = {}

// SEND
IDS[tmpID = Math.random()] = msg = { key: 'editor', type: 'mark', id: tmpID, value: [line1, line2, line3] }
window.postMessage(msg)

// RECEIVE
window.addEventListener('message', msg => {
  var { id, type, key, value, error } = msg
  if (error) return console.error(error.msg, error. status)
  /* canonicalise */ value = [].concat(value)
  
  if (IDS[id]) console.log('response', value)
  else if (id) console.log('request', type, key, value)
  else console.log('notification', type, key, value)
})
```

**Comment by yann300** [comment]
that looks good, just need to add the `type` property.
Also this above should be in a separate issue

**Comment by yann300** [comment]
moved there https://github.com/ethereum/remix-ide/issues/1139
