### ISSUE TITLE
"compiler not yet loaded"

### ISSUE THREAD

**Issue by obo20** [ethereum/remix-ide#1143]
I'm getting "compiler not yet loaded" for remix right now. I've also asked a few friends to test, and they're all getting the same issue. Running in incognito or safari doesn't help either.

**Comment by yann300** [comment]
I created a PullRequest now to warn loading of compiler version list failed (this might be due to adblocker). please try to deactivate it.

**Comment by ann-kilzer** [comment]
I'm getting this error in remix via mist v10.0. There are no adblockers here.

**Comment by yann300** [comment]
please try to change the solidity version in `compile` tab

**Comment by ann-kilzer** [comment]
I did try to change the version. It won't accept the selection.

**Comment by abrhamelm** [comment]
do i need an internet connection for the offline version?

**Comment by yann300** [comment]
no you don't
