### ISSUE TITLE
Cannot compile nor switch compiler version

### ISSUE THREAD

**Issue by bitcoin4cashqc** [ethereum/remix-ide#1148]
Hey guys, everything was fine yesterday on https://remix.ethereum.org, but now I can't compile anything on the remix editor. I tried to run the offline one, but I get a mock compiler error which I don't understand how to fix.

I just can't hit Start Compile nor select another compiler version, even with the ballot.sol original contract. I'm quite worried lol I need remix

**Comment by yann300** [comment]
adblock block loading the compiler version list (a new filter rule) . Try deactivating it. We are going to fix that too..

**Comment by bitcoin4cashqc** [comment]
Oh my that's dumb 😞

Thanks a lot

________________________________
De : yann300 <notifications@github.com>
Envoyé : 13 mars 2018 20:54:14
À : ethereum/remix-ide
Cc : bitcoin4cashqc; Author
Objet : Re: [ethereum/remix-ide] Cannot compile nor switch compiler version (#1148)


adblock block loading the compiler version list (a new filter rule) . Try deactivating it. We are going to fix that too..
