### ISSUE TITLE
UI/UX improvements - EDITOR

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/remix-ide#1150]
- [ ] TABS
  - improve the look of the tabs
![screen shot 2018-03-13 at 11 06 38 pm](https://user-images.githubusercontent.com/1076427/37374497-4be48da0-2713-11e8-915e-e06081697e63.png)
![screen shot 2018-03-13 at 11 06 27 pm](https://user-images.githubusercontent.com/1076427/37374498-4bfd0880-2713-11e8-837f-60d6e5a43f70.png)
![screen shot 2018-03-13 at 11 30 23 pm](https://user-images.githubusercontent.com/1076427/37375220-8c6c8f82-2716-11e8-97ca-23132b17e7d9.png)
 ---
- [ ] NEW FILE 
  - enable double click on empty space after tabs to create new tab/new file 
  - OR move create button to the tabs section (like in chrome) 
![screen shot 2018-03-13 at 11 08 26 pm](https://user-images.githubusercontent.com/1076427/37374578-b123f066-2713-11e8-97f9-a4b00c19bf9e.png)
---
- [ ] RENAME FILE
   - `rename` file with double clicking on the name in the tab

- [ ] CLOSE FILES
- add x(close) to all tabs, not just those in focus (easier to close many at once)
![screen shot 2018-04-01 at 5 35 07 pm](https://user-images.githubusercontent.com/1076427/38175358-3e3e6c74-35d3-11e8-83d8-af5c8438563c.png)

**Comment by yann300** [comment]
Proposal: @ninabreznik @ryestew 
I would be very in favor of removing the tab list. 
we would replace it by a vertical panel that would be displayed at the bottom of file explorer.

**Comment by ninabreznik** [comment]
@yann300 I missed your comment about the tab list. 

I am trying to imagine what you mean by displaying a vertical panel at the bottom of the file explorer and how would this feel to the users. Do you have some example project where you saw this use case so I could take a look at it?

I am not sure how the editor without tabs would feel. I remember @chriseth mentioning that he would like to remove this since we joined the team, but I am personally not convinced yet or maybe I just haven't found any really nice UX solution that would replace it. So far Chrome, Atom, Dev tools, Terminal all use tabs and it feels like this is one of best solutions, but I would be happy to explore more options...
