### ISSUE TITLE
UI/UX IMPROVEMENTS - LEFT PANEL

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/remix-ide#1151]
- [ ] LEFT PANEL: FILE EXPLORER
  - when `rename` is chosen on right click, enable click on the name (now you have to use arrow keys = super confusing)
  - enable double click to `rename` file or folder (also when double click on the tab)

- [x] LEFT PANEL: MENU BAR
  - re- add feature `load from gist`
  - move `create new file` to tabs AND to the right click in file explorer (next to rename and delete options)

---

**Comment by LianaHus** [comment]
"rename on double click" is still relevant

**Comment by LianaHus** [comment]
found this https://github.com/ethereum/remix-ide/issues/1840
