### ISSUE TITLE
Encoding error, address + uint

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/remix-ide#1152]
I have a contract with a method that has two arguments, an `address` and a `uint256` integer. For reasons I cannot comprehend, remix is not encoding the second parameter, instead pretending it's 0.

Here is a MWE:
```solidity
pragma solidity ^0.4.19;

contract Foo
{
    uint256 public amount;

    function bar(address a, uint256 b) public {
        require(b > 0);
        amount = b;
    }
    
   function baz(uint256 b) public {
        require(b > 0);
        amount = b;
    }
}
```
`bar(0xca35b....733c, 100)` doesn't work, it produces the following in the JS VM:
```
...
input: 0x894c6c83ca35b7d915458ef540ade6068dfe2f44e8fa733c
decoded input: {
 	"address a": "0xca35b7d915458ef540ade6068dfe2f44e8fa733c",
 	"uint256 b": "0"
}
...
```
`baz(100)` does work. For reference, it produces this:
```
...
input: 0xf3f73f220000000000000000000000000000000000000000000000000000000000000064
decoded input: {
 	"uint256 b": "100"
 }
...
```

I usually develop with Python, so hopefully this is just "*user error*", but I can't for the life of me begin to understand where the problem is. I'm trying to use Remix for a workshop I am giving, so this is kind of a drag for me.

**Comment by yann300** [comment]
thank for the feedback,
we have a PR that ill address this.
the way Remix accept arguments is not really convenient now.
try wrapping the address with double quotes
`"0xca35b7d915458ef540ade6068dfe2f44e8fa733c", 144`

**Comment by fubuloubu** [comment]
That works for me. Could've sworn I tried enclosing addresses in quotes, I guess I didn't haha. Thanks!

**Comment by yann300** [comment]
this has been fixed. now you can input `0xca35b7d915458ef540ade6068dfe2f44e8fa733c, 144`

**Comment by fubuloubu** [comment]
Confirmed! Thanks @yann300!
