### ISSUE TITLE
UI/UX IMPROVEMENTS - RUN TAB (recorder etc.)

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/remix-ide#1153]
- [ ] RUN TAB: UI SECTION ELEMENT
  - by default all sections could be collapsed and you see just a title and when you click you expand it and see whole functionality
---
- ELEMENTS
  - **Deployment setup** (env + account + gas (under more)),  
  - **Value** (value sends eth to contract or function (if payable) - where to put it?),
  - **Contract name**,  
  - **Deploy or call** already deployed contract,
  - **Pending** (remove pending notification and replace it with notification/alert in terminal menu bar),
  - **Recorder**,
  - **Deployed contracts**
    - Instance title
    - Instance environment
    - Instance address
    - Instance UDapp (UI/functions)
---

- [ ] DEPLOY OR CALL
  - rename `create` to `deploy`
  - rename `at address` to `retrieve`
  - add titles to the 'sections' (visible when section is collapsed):
    - 1. box
      `Contract title:` <= title
      `dropdown w/ contract names`
    - 2. box
      `Deploy or retrieve already deployed contract:` <= title
       input field +`dropdown` (`deploy` or `retrieve`) OR  show radio button and when user selects, display also input field (for create only if contract accepts params)

---
- [ ] DEPLOYED INSTANCE
![screen shot 2018-03-14 at 2 02 54 am](https://user-images.githubusercontent.com/1076427/37379560-f786dfce-272b-11e8-90a4-1d34af651e0e.png)
  - make it more clear that copy-top-clipboard copies the instance address
    - **new instance** (idea for redesign)
    `Deployment info` <= title
    `contract: Coursetro` 
    `environment: blockchain`
    `address: 0x72f9991977afeda43dbb2a895b875ba67f94d149 (copy button)` 
     (and on click it opens solidity functions/contract UI)`
    - below then buttons to trigger functions and type in params (UI of solidity contract ) 
---
- [ ] RECORDER
  - records transactions that RUN in the run tab (within deployed contracts (functions execution))
  - make a special Transactions section
  - Options:
    - delete all
    - save all (record)
    - recreate all (replay)
---

**Comment by ninabreznik** [comment]
# COLLAPSED/INNITIAL VIEW
![default](https://user-images.githubusercontent.com/1076427/37924055-094c3006-3131-11e8-9fac-71027a1fb0d3.JPG)

# EXPANDED VIEW
## CONTRACT (Create(Deploy), Load(Connect))
![dsc_1348](https://user-images.githubusercontent.com/1076427/37924063-0f10d3d4-3131-11e8-8743-990492f31074.JPG)
## RECORDER (Save/Replay)
![dsc_1349 1](https://user-images.githubusercontent.com/1076427/37924057-0b418b18-3131-11e8-8728-de2cee1bee17.JPG)

**Comment by ninabreznik** [comment]
@yann300 @ryestew Can you update this issue with additional info/sketches you might have?

**Comment by ryestew** [comment]
![runtab_3-26-18_v1a](https://user-images.githubusercontent.com/6050001/38100479-ce533478-337d-11e8-83c5-5748361c3eb5.jpg)

**Comment by ninabreznik** [comment]
@ryestew Did you want to close the issue or was this a mistake?

**Comment by ninabreznik** [comment]
@ryestew I have some feedback:

- **Access/Deploy**
could be tabs, so that people know you change the view when you select one (now it's not really clear they should choose one or another, grey tries but as a user you would't necessarily think the view and button will change if you select Access instead of Deploy )

- **Constructor** (Arguments)
I am not sure everyone is used of thinking in the 'class way' so constructor doesn't seem as the best metaphor in my opinion. I would prefer Arguments (because we are calling functions)

- **Gas and Value** (Context)
I am missing those two, so we have to think how to stick them to the 'Arguments' (now Constructor) section. If you look at my sketch (second image) - I did a section for 'Context', where I display default context (environment, account, gas and value) for this certain transaction (deployment or function call). Because we also want to teach people that when they create a transaction they always also pass the arguments and a context. 

- **Instances**
First, I am still not sure if I would call this section Instances, I think it's not clear for first time users. I am still leaning more towards Deployed contracts (something more easily to understand, since the whole Remix tool is already rather complex)
Second, I have to say I can't see the instances box as something higher in hierarchy than deployed contracts/instance itself. I think the box would need to go around all of the instances somehow. I here get a feeling that if I click X, it will just remove that box with the title, not all of the instances.

Maybe we could use this type of visualizing title + instances (like in Gmail) => you have a conversation title (this would be called for examples Deployed instances) and then below each email is one deployed instance. When you click on it it expands and opens more things. We wouldn't even need a caret, we could just use a css styling (cursor:pointer (same as it's done in Gmail for opening/closing certain email in one conversation))
![screen shot 2018-03-31 at 12 18 42 am](https://user-images.githubusercontent.com/1076427/38156887-89f862e2-3479-11e8-9374-1ce3ff451f5a.png)

- **UDapp (functions)**
Maybe same as a suggestion above could be done for functions (so we add a border and stack them one on another and then make cursor: pointer). This way we remove those carets that don't really look too nice. I find them good in file explorer on the left, but here (and in deployed instances) they don't look too nice. 

@serapath had an idea for how we could improve the expanded view when calling the functions. 
- since we have buttons at the beginning and then the arguments, it doesn't really feel intuitive. BUT, because we want to mimic calling of the functions, we could go with this version
![screen shot 2018-03-31 at 12 27 47 am](https://user-images.githubusercontent.com/1076427/38156990-6404edfc-347a-11e8-9315-a19dabe99d9f.png)

We would just add one thing - parenthesis. This way we make it look like function a bit - first the fn name, then arguments in parenthesis and after the button (I would rather call it execute than submit)

**Comment by ninabreznik** [comment]
And for expanded view I would actually leave the fn name without a button look and just make each argument in a separate line instead of one line for all arguments when you have a collapsed view.

So, function name with input for first arg
input field for second arg
input field for third arg
execute button

**Comment by ryestew** [comment]
I like the gmail analogy for the top grey bar.
One thing that I was struggling with is the amount of space in the tab:

**- long function names:**

so a function is not called vote but theFunctionFormerlyCalledVoteOrSomeSuchThing() - or something half that size - it still needs to be legible. - so  it made me not want to have 3 sections in the collapsed view ( function name, input, submit) but to leave it at 2 with the shortcut that we've been using ( the function name is the title of the button).

The deployed contracts bar ( I have it being called Instances)( but I like deployed contracts is better)
- I didn't want to put another line or a background color around the entire list of instances.  But your solution of just having that title text on a the bg - may solve that - I'll update the design and check.

**Carets**
I over-careted the design - I think taking them all away is not the answer - but removing as many as we can - the top level carets probably but inside the instance - I think keeping the caret for the expanded view of a function will not be too noisy.

**Gas and value inside of each instance**
I'll add this to the design to see how it looks.

**Comment by ryestew** [comment]
For the copy icon on the instance address - I think a tooltip will make this clear.  I think this mostly in the interest of saving space. Otherwise we'd probably need to put the title <br> address with copy.

**Comment by ninabreznik** [comment]
@ryestew 
I think I am going to start working on this issue. Will try to implement approximately this what we have and then we can still move things around. And you also try out things with functions inside of the instance. I see that you rotated all the edge cases so you know best. You see, I forgot in my feedback that sometimes function names are pretty long, so we have to have a solution that works for all the situation.

Let's try things out so we push this PR forward and let's chat or update each other here. But if you will also work in the evening or during the weekend and we will need a quick call, why not. :)

**Comment by ryestew** [comment]
<img width="646" alt="instances-deployed" src="https://user-images.githubusercontent.com/6050001/38507533-12fc6d22-3c1d-11e8-9885-f1b30dd1cdea.png">

**Comment by ninabreznik** [comment]
@ryestew Just a thought.... Maybe I would still go with `run` or `call the function` instead of with `submit`.

**Comment by ninabreznik** [comment]
@ryestew One question is still open. We said we should move gas and value to the place where deployment/function calls get executed... Do you have any plans for this?

**Comment by ryestew** [comment]
No I don't have a plan for moving gas & value...yet.  I want to finish putting the multi-params in the instances and then in the constructor.  But I liked your idea above - I'll do another sketch once I update the constructor.

**Comment by ryestew** [comment]
Also after a submit button ( or call / run button) is hit - I think we should erase the values from the input box. ( note to self)( I could do this in the current PR)

**Comment by ryestew** [comment]
<img width="403" alt="image" src="https://user-images.githubusercontent.com/6050001/38627172-9ea28752-3dae-11e8-81e2-0cb4a5b0eee9.png">

**Comment by ninabreznik** [comment]
@ryestew I can make a suggestion for how to include gas and value when executing deploy and then you can use it as an inspiration for your part.

I am also creating a card module (with expanded and collapsed view.) Will try to finish it today/tomorrow and will ping you when I do.

**Comment by ryestew** [comment]
Here is a view of the carets on the right side - now they are up and down angles:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/6050001/39188983-65d3805c-47d1-11e8-92fa-c2f908a26121.png">

**Comment by ninabreznik** [comment]
Nice. I like this more. @ryestew

**Comment by ryestew** [comment]
I think we have some conflicts with Call - because that word is also used for functions that return constants ( free ones ).  So Run or Transact or Snd Txn might be better - well if its a free one - the text could change - to Call and if it costs - then Transact.  Any thoughts?

**Comment by ninabreznik** [comment]
I agree, this makes sense. I would vote for run, since it's really generic and easy to understand, plus we already call a tab a Run tab, so users kind of expect to run things there :)

Transact is also not bad, I have to say. It says clearly that you will run a transaction and in real life we connect transaction with something payable, which is also what transactions actually are - a payable run.  So, what would you as a native speaker say. 

I would use always the same term, either run or transact, for all the buttons, because at the end also submit is actually triggering a transaction.
