### ISSUE TITLE
[Plugins] Defining messages structure

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1156]
# brainstorming iframe api used by plugins

```js
var tmpID, msg, sessions = {}


// RECEIVE
window.addEventListener('message', args => [].concat(args).forEach(msg => {
  var { id, status, type, key, value } = msg
  if (status === 'error') return console.error(value)
  /* "canonicalise" */ value = [].concat(value)
  if (IDS[id]) console.log('response', value)
  else if (id) console.log('request', type, key, value)
  else         console.log('notification', type, key, value)
}))


// SEND
function example (line1, line2, line3) {
  return sessions[tmpID = Math.random()] = msg = {
    key: 'editor', type: 'mark', id: tmpID, value: [line1, line2, line3]
  }
}
window.postMessage(example(...)) // sending message to highlight/mark 3 source code lines
var examples = [example(...), example(...), example(...)]
window.postMessage(examples) 
```

## `id`
identifies a session which usually consists only of a "request" ans "response" message.
* it allows to identify, that a "response" message answer to a certain "request" message that was sent.

## `status`
was roughly inspired by http status codes and is most interesting in "response" messages, but might also be interesting in other messages.
* The default normal successful message does not need a status or has a status of `undefined`
* if `status === 'error'` then something went wrong
* maybe, if a "response" or "notification" consists of a series of messages, the `status` could indicate,
  whether the last message has been received or if more are expected
* also the `status` could indicate if the permission for a "request" was denied, etc...

## `type`
is meant as `action/method/opcode/eventName/command/....`

## `key`
is meant as `address/origin/target/namespace/...`

## `value`
can be one or many (=array) and is meant as `arguments/data/payload/...`

**Comment by yann300** [comment]
just need to add a property that defines which type of message this is

**Comment by yann300** [comment]
- [ ] Update the current PluginManager.js to match the current spec.
 - [ ] Inject an object in plugin iframe that will abstract the underlying calls.
```
API consumers will then register to notifications:
windows.remix.notification.compiler.compilationFinished.register(function () {})
windows.remix.notification.tab.focus.register(function () {})
and make request
windows.remix.request.editor.setConfig('path', 'value', function () {})
windows.remix.request.editor.getConfig('path', function () {})
```

- [ ] Write tests in browser-test for the injected module

**Comment by serapath** [comment]
I imagine the example above could be the basic **plugin iframe api** and what you specify in the comment above and also the missing "type of message" field could be all wrapped in a special module.

```js
var remix = require('remix-plugin')

window.remix = remix // if somebody want's it as a global they can do

// otherwise they just use it
const log = (err, val) => err ? console.error(err) : console.log(val)

/*************************************************
  NOTIFICATIONS (register)
*************************************************/
remix.on(log) // listens to all/any notifications
remix.on('compilationFinished', log) // listens to specific notifications
/* or */ remix.on(['compiler', 'finish'], log)
/* or */ remix.on({ key: 'compiler', type: 'finish' }, log)
/* or */ remix.on('compiler/finish', log)

/*************************************************
  NOTIFICATIONS (unregister)
*************************************************/
remix.off(log) // stop listening to all notifications
remix.off('compilationFinished', log) // stop listening to specific notification
/* or */ remix.off(['compiler', 'finish'], log)
/* or */ remix.off({ key: 'compiler', type: 'finish' }, log)
/* or */ remix.off('compiler/finish', log)


/*************************************************
  REQUESTS and RESPONSES
*************************************************/
const response = (err, val) => err ? console.error(err) : console.log(val)

plugin.editor.setConfig('path', 'value', response)
plugin.editor.getConfig('path', response)

// one special help request we maybe want to add
plugin.help(function (err, value) {
  var { api, notifications } = response
  console.log('list of all notifications you can subscribe to', notifications)
  console.log('list of all supported requests', api)
})

----

@yann300
Do you think the above is good enough?
It would be a small module a plugin maker would require.
It is a convenience wrapper around the raw iframe api.

When using it, there is no need anymore to directly interact with the message objects and its `id`, `status`, `value`, etc... fields - so we don't even need to bother so much with them and would rather focus on that wrapper module

**Comment by serapath** [comment]
of course, we would still have them, but its just abstracted away from the user.

The point is - if we later change it, we can just say, that we only guarantee the module `require('remix-plugin')` to be stable but not the raw `postMessage(...)` and `addEventListener('message', ...)` api.

I like your recommendations. great.

One question i have regarding the "`remix`" plugin object injection.
Can we even do that?
If the plugin is on a different domain we can probably not just easily set it on the iframes window object.
So would the plugin window need to listen to the event that sends the remix object?

Did you do that already and know it works?

...i will need to revisit the web api docs maybe on **mdn** to check how to do it.

**Comment by yann300** [comment]
oh yes you are right, we would not be able to do that (the injection).
so having a `remix-plugin` module that user can require (and providing package version) is the way to go.

**Comment by yann300** [comment]
given the previous discussion , here is a proposal for the ground layer:
 - Notification sent by Remix:
```
{
 action: 'notification',
 key: <string>,
 type: <string>,
 value: <array>
}
```
 - Request sent by the plugin:
```
{
 id: <number>,
 action: 'request',
 key: <string>,
 type: <string>,
 value: <array>
}
```
 - Response sent by Remix and receive by the plugin:
```
{
 id: <number>,
 action: 'response',
 key: <string>,
 type: <string>,
 value: <array>
}
```

The spec above does not take of a request from remix-ide to the plugin.

The only change is the `action` property.

@serapath if everything is ok with the spec above, could you update `pluginManager.js` according to that?
I created this repo https://github.com/ethereum/remix-plugin where we would implement the wrapper around postMessage.

**Comment by serapath** [comment]
I would prefer to add a folder `remix-plugin/` in the `remix` repository, but publish it to npm as `remix-plugin/` ...do you think a separate github repository is better?

regarding your proposal to add `action`, i think it's fine, but i would still add also the `status` field.

The status field indicates what `value` means.
For example `status === 'error'` means the value is an error message, because something went wrong.

The iframe communicating to the parent (especially if users need to authorize certain things later on) ... would have very likely similar `status` possibilities similar to the HTTP protocol.
We don't need to use the exact same codes, and an empty status would probably reflect the `200` http status, while an error status might mean `500` or something... ...but i think similar to how callbacks have an error argument, we need a way to differentiate between at least normal success and error and maybe other status messages, so i think we should include the status field.
