### ISSUE TITLE
Compiler will not load in offline version.

### ISSUE THREAD

**Issue by devt3000** [ethereum/remix-ide#1163]
Every time I run npm run serve the console gets stuck at execr --silent http-server, but, when it was working, the command would run and terminate on its own. Meaning that going on to npm start will give a Url with version=builtin. I used the usual method to install remix-ide by cloning the repository etc. Some packages where not installed automatically when I ran npm install so I had to manually install them.

**Comment by yann300** [comment]
if you want to run remix-ide locally , please try to install the npm module `remix-ide`

**Comment by yann300** [comment]
I close just reopen if necessary

**Comment by devt3000** [comment]
@yann300 install it globally?

**Comment by yann300** [comment]
yes and run it with `remix-ide`

**Comment by devt3000** [comment]
@yann300 it worked but I'm still online. I hope it does when I'm not. Thanks!

**Comment by yann300** [comment]
ah :) well when you are offline you 'll have to switch the compiler to the local soljson.js, that should be ok

**Comment by devt3000** [comment]
@yann300 okay, thanks. :+1:
