### ISSUE TITLE
Move Style Guide To REMIX-IDE

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/remix-ide#1166]
This is quite urgent, I am very limited in building UI, since I have to always make 2 pull requests if I make additional styling for certain element in Remix-IDE. And if we sometimes lose track of which PRs go together all gets messed up. So, for really productive work it's necessary for me to have Style guide in the same repo! Can we please fix this very soon?

**Comment by yann300** [comment]
The best would be to extract from the style-guide the stuff related to the debugger, keep that part in remix-lib, and move the rest to remix-ide.
That also means that some basic styling will be replicated between remix-lib and remix-ide but that is ok.
I don't have a clear view of the current style guide. would it be hard to split that?

Another solution (easier), would be to keep a copy of the style guide in the remix-ide repo for dev purpose... well we should talk about this

In the meantime, if you name the PR in the remix repo with the id of the corresponding PR in remix-ide (like for terminalUI), that could be enough to keep track of PR dependencies.

**Comment by yann300** [comment]
After discussion, we move the entire remix-debugger ui to remix-ide.
In a subsequent PR remix-debugger will become a non ui module that wrap all the component necessary to debug a transaction
