### ISSUE TITLE
Error while call a function

### ISSUE THREAD

**Issue by gen4sp** [ethereum/remix-ide#1167]
I have a token and a control contract.  I try to get token totalSupply from the contract and got an error.
```
call to BankContract.totalTokenSupply errored: VM error: revert.
revert	The transaction has been reverted to the initial state.
Note: The constructor should be payable if you send value.	Debug the transaction to get more information. 
```

Which kind of senseless. 

Is it Remix issue?

Gist with the code here:
[https://gist.github.com/c600c66b7d8ce43c8fee7e0fbc698142](https://gist.github.com/c600c66b7d8ce43c8fee7e0fbc698142)

**Comment by yann300** [comment]
could you repost the code please?

**Comment by gen4sp** [comment]
Sorry, just an unexpected period in the link. fixed.
new link - [https://gist.github.com/c600c66b7d8ce43c8fee7e0fbc698142](https://gist.github.com/c600c66b7d8ce43c8fee7e0fbc698142)

**Comment by yann300** [comment]
please try minting in another function
A bug in javascript VM we need to solve
```
pragma solidity ^0.4.19;

import './BankToken.sol';
import './Ownable.sol';

contract BankContract is Ownable {
    /// @dev Token
    BankToken internal token;
    
    function BankContract() public {
        token = new BankToken();
        // token.mint(owner, token.initialSupply());
    }

    function totalTokenSupply() public view returns(uint256) {
        return token.getTotalSupply();
    }

}
```

**Comment by yann300** [comment]
note we also need to stop overriding the stateManager.js cause that may cause this issue too

**Comment by axic** [comment]
> note we also need to stop overriding the stateManager.js cause that may cause this issue too

See #1073.

**Comment by gen4sp** [comment]
@yann300 the problem has been found!
```
// doesn't work
function totalTokenSupply() public view returns(uint256) {
        return token.totalSupply();
    }
```

```
// works perfectly
function totalTokenSupply() public view returns(uint256 totalsupply_) {
        return token.totalSupply();
    }
```

**Comment by andrewkmin** [comment]
Why does this make a difference? @gen4sp
