### ISSUE TITLE
remix-7013ed1 :: index.html is blank

### ISSUE THREAD

**Issue by suvaio** [ethereum/remix-ide#1173]
Hi Team,

I have downloaded offline zip of solidity-browser. When I clicked on index.html, it's showing a blank white page. I have used "inspect-element" and I found the following errors in page.

![screen shot 2018-03-21 at 12 43 59 pm](https://user-images.githubusercontent.com/26338712/37697904-a3016e94-2d05-11e8-9db5-9401c4d73d0f.png)

**Comment by yann300** [comment]
better use `npm install remix-ide -g` to install locally. the zip contains the code but not the build
