### ISSUE TITLE
Resolve Truffle like import

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1183]
PR https://github.com/ethereum/remix-ide/pull/699#issuecomment-375201322

**Comment by yann300** [comment]
deployed to remix-alpah.ethereum.org

**Comment by santteegt** [comment]
Hi,

Is this feature supported on the current version of remix.ethereum.org ? I believe it was working before but it isn't currently resolving truffle-like imports. I had to switch to the old version in order to use this feature
