### ISSUE TITLE
experimental feature: function with string array parameter pending forever or yielding error

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/remix-ide#1192]
I am testing the following smart contract which I am compiling with the latest Solidity compiler (0.4.21)

```
pragma experimental ABIEncoderV2;
pragma solidity ^0.4.21;

contract test {
    string public s;
    
    function test123(string[] texts) public {
        s = texts[0];
    }
}
```

Calling `test123` with parameter `["bla", "blabla"]` is simply pending forever.

Just passing a single parameter `["bla"]` when calling that function is yielding a strange error: 
<img width="763" alt="screen shot 2018-03-25 at 1 20 03 am" src="https://user-images.githubusercontent.com/11379673/37870309-ae821580-2fca-11e8-8e92-7bc2c5ce47ef.png">

**Comment by yann300** [comment]
fix https://github.com/ethereum/remix-ide/issues/1187

**Comment by ondratra** [comment]
I encountered the same problem. It is "pending" everytime. Using current Solidity compiler 0.4.23 doesn't solve the issue.

**Comment by yann300** [comment]
unfortunately the fix is not yet merged..  coming pretty soon
