### ISSUE TITLE
Cannot read property 'themeChooser' of undefined

### ISSUE THREAD

**Issue by tntzho** [ethereum/remix-ide#1195]
I according to README.md:
git clone https://github.com/ethereum/remix-ide.git
cd remix-ide
npm install
npm run build && npm run serve

Succeed！

But I saw "Cannot read property 'themeChooser' of undefined" on console  when I request  "localhost:8080" in my chrome. Corresponding code is "var styleGuide = require('remix-lib').ui.themeChooser;" .

In the "https://github.com/ethereum/remix/commit/ee2f5ce73cfce4ba34df4148bafcf33353cbfc12",
the object  of ui have be removed.

**Comment by yann300** [comment]
uh this code should not be here anymore and I just tried successfully
could you please
 - try to clear the browser cache
 - check that you are browsing what you were actually building

**Comment by tntzho** [comment]
@yann300 
Thank you for your reply
I  removed all the code of remix-ide in my local and "git clone ..."  current code again.The issue did not occur again.
