### ISSUE TITLE
First run using Web3 provider exceeding block gas limit

### ISSUE THREAD

**Issue by warren8r** [ethereum/remix-ide#1197]
Hello,
Please excuse my naiveté - this is my first private block chain learning project.
I am trying to run the solidity code from https://github.com/Raviezz/SupplyChainManagement
using Web3 provider. I am getting the following error in Remix-ide:
**creation of supply_Chain errored: exceeds block gas limit**
Not sure how I could have exceeded my block gas limit already?
Any help is greatly appreciated.
Thank you

**Comment by Lursun** [comment]
![image](https://user-images.githubusercontent.com/11616295/37959693-43e29fc4-31e6-11e8-8f05-2f1fe35f39b8.png)

????

**Comment by Lursun** [comment]
![image](https://user-images.githubusercontent.com/11616295/37959914-d50b8b28-31e6-11e8-9feb-7698a2ae8d21.png)

Copy code from https://github.com/Raviezz/SupplyChainManagement/blob/master/SupplyChain.sol
Paste remix editor
Compiler -> Start to compile
Run -> Environment ( Javascript VM or Injected web3 )
Create

**Comment by yann300** [comment]
I was able to deploy the contract on ropsten.
If you use a private / test node, you should perhaps check the `target-gas-limit` option (in geth), you 'll have this error if this is too low
I close that one, please reopen if necessary
