### ISSUE TITLE
npm install remix-ide -g  error

### ISSUE THREAD

**Issue by shangmacun** [ethereum/remix-ide#1203]
14054 verbose stack Error: sha512-gcKEAnU/WZepA36xOQqSuwv2f2kuwPY35NB3yFyINLk8c+ykt/DwJc9Dx3gcpS3cDymshvBWXWIJHzfP0fzhyg== integrity checksum failed when using sha512:
wanted sha512-gcKEAnU/WZepA36xOQqSuwv2f2kuwPY35NB3yFyINLk8c+ykt/DwJc9Dx3gcpS3cDymshvBWXWIJHzfP0fzhyg== but got sha512-4iKH+Hk9pwdroRvipoVC62V0RiNKf2PLym1ss6FRNu9p8et7+Y
YhF3eI71qoJMUp7ip/0lyOoa2ZpTiu5z01IQ==. (7110182 bytes)

**Comment by yann300** [comment]
the install should be ok... could you please try perhaps to remove the npm cache

**Comment by yann300** [comment]
i m closing, please reopen if you still have this issue
