### ISSUE TITLE
Remove duplicated icon

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/remix-ide#1225]
![screen shot 2018-04-09 at 8 18 51 pm](https://user-images.githubusercontent.com/1076427/38517888-5231ee02-3c33-11e8-86d0-5e290739526e.png)

In left top corner, above the file explorer I noticed someone added a new Github icon. We now have 2 identical icons. This is not how it should be.

I can consult in these cases and help to find a better solution. In this case for a quick fix i would suggest to make on this Github icon a little dropdown with 2 options. But 2 same icons are really confusing and look like a visual bug.

**Comment by yann300** [comment]
yes my bad
- the first icon package to gist files that are in the browser explorer
- the second icon package to gist files that are in the gist explorer 

It seems that gist does not support anonymous uploading files. so we might need to remove the support of this anyway... and finding another way (like pastebin)
