### ISSUE TITLE
UI/UX IMPROVEMENTS - COMPILE TAB

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/remix-ide#1227]
## For the beginning just a list of visual bugs:
- rotating icon on compile tab showing that compilation is in process is not working
![screen shot 2018-04-09 at 10 39 29 pm](https://user-images.githubusercontent.com/1076427/38524619-29eff344-3c47-11e8-9089-b0d926269f19.png)

- auto compile tag should be wider when panel is open and Attention triangle and the tag should be closer together
![screen shot 2018-04-09 at 10 42 19 pm](https://user-images.githubusercontent.com/1076427/38524662-558cab00-3c47-11e8-806a-bc4d9feba94f.png)

- attention triangle (where suggest we turn off auto compile) should appear only when autocompile is on
- is this notification still needed?
![screen shot 2018-04-09 at 10 46 04 pm](https://user-images.githubusercontent.com/1076427/38524819-d8569a6e-3c47-11e8-95e4-30a3717cf9ae.png)

- buttons
- all buttons look the same, but one opens a modal dialog, one publishes to Swarm and two copy to clipboard. Try to find a way to visually communicate the function of each or at least to create different look for each.
![screenshot_2018-08-14_01-46-27](https://user-images.githubusercontent.com/1076427/44065669-ef049bec-9f63-11e8-9ba2-c0d9476a378e.png)

## Some inspiration
- Errors should be logged in the terminal
- on dropdown you should be able to select any .sol file with a contract and compile it (this would also auto open the file in the editor)

**Comment by yann300** [comment]
for the `is this notification still needed?` .
The reason of this is to clearly warn the user that there's no error, no warning and everything is ok.
but there are certainly better wasy to show that

**Comment by yann300** [comment]
`on dropdown you should be able to select any .sol ...` I don't completely get, cause the dropdown does not   show sol file but compiled contracts. let's check that when you have time

**Comment by yann300** [comment]
comment from @ninabreznik from another thread:

> i think compile button is not so nicely visible now, so I would maybe move it inside of the box above so compiler selection and compile button are there togethe

r.
