### ISSUE TITLE
[Plugin] Zokrates plugin

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1230]
https://github.com/JacobEberhardt/ZoKrates

 - [ ] Package Zokrates in remixd (osx, linux, windows)
 - [ ] API in remixd to interact with Zokrates trough websocket
 - [ ] Use API in a remix-ide plugin (still need to define what the plugin exactly does)

**Comment by LianaHus** [comment]
@yann300  can I close this or you plan to implement those?

**Comment by yann300** [comment]
for the moment we don't plan this. mostly depends what Zokrates plugin team want to do @edisinovcic

**Comment by LianaHus** [comment]
@edisinovcic should we close this?

**Comment by edisinovcic** [comment]
I think it's can be closed. @dark64 is working on that and he will be back from vacation on Monday so we can wait for him to confirm.
