### ISSUE TITLE
Improve the development section in the readme

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#1253]
See https://github.com/ethereum/remix-ide/pull/1251#issuecomment-380936667

It is not clear that all the commands, including `pullremix`, must be run.

**Comment by ninabreznik** [comment]
@yann300 I update my PR for Readme improvements and added also @axic's comment.

https://github.com/ethereum/remix-ide/pull/1190/files#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by yann300** [comment]
fixed by https://github.com/ethereum/remix-ide/pull/1190
