### ISSUE TITLE
Addresses are corrupted if not properly formatted

### ISSUE THREAD

**Issue by dmdque** [ethereum/remix-ide#1257]
When performing an action with an address, the address will be corrupted if not entered properly. For example, omitting the `0x` will cause the address to be interpreted differently.

[Example](https://kovan.etherscan.io/tx/0x62bfa2773d4d2d07731be9fc48a5848b42bce34d9d7e37926a876b15e7c19293): `"af863b90dc4d70924c4f6706c6cb9b01d8cc72e6"` -> `0x000000220CA72850d475DDD1C4c7DCa812b97c72 `

This can be devastating, for example when transferring ownership of a contract. Ideally Remix should produce a warning.

**Comment by yann300** [comment]
could you double check in remix-alpha.ethereum.org please ? but I think the new ABI coder we use should have fixed this issue.
