### ISSUE TITLE
Improve file explorer

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1262]
Is there a way to move my sol files from the browser into localhost? 
I have remixd setup and I can see the files in it. I just cant seem to find a way to get the files to move into their. Also when I create new I would like it to go into their as well. 
Again I have not found a way to direct it into localhost. So is there a way to tell remix to create files in localhost by default rather than browser? Thank you.
___________________
 - [x] Move file from one explorer to another EDIT: copy has been choosen
 - [x] Create file directly in a specific explorer EDIT: if applicable

**Comment by yann300** [comment]
yes from the chat. Feel free to move the content to your FILE EXPLORER improvement and close that one

**Comment by ninabreznik** [comment]
I just linked it there, so we can leave it open for now

**Comment by tsauvajon** [comment]
Regarding this issue - is there a way at the moment to either move files, or create a file in any folder but the first one ?

**Comment by yann300** [comment]
@LianaHus i checked and commented on the remaining items, I think it can be closed.
