### ISSUE TITLE
Constructor Warning

### ISSUE THREAD

**Issue by AencoCTO** [ethereum/remix-ide#1267]
Constructor recommendation in contract compile is  wrong.
If you change the constructor as recommended by the compile warning, the contract will compile, but the constructor will not execute, as such leaving a deployed contract disabled by the fact that the initialisation has not taken part.

**Comment by yann300** [comment]
Just tried now and the constructor was executed. Could you post a snippet to reproduce?

**Comment by cyberience** [comment]
I did a deployment on Ropsten here is the contract address.
[https://ropsten.etherscan.io/address/0xc4a8bf4d9dd312d54423b44107c2d75283f2d387](url)
If you change the constructor to AENToken it works ok: This had me puzzled for most of the day.

**Comment by yann300** [comment]
here is how you should define the ctor: 

```
constructor()
  {
    bytes memory empty;
    totalSupply = 4000000000 * (8 ** uint256(decimals));
    balances[msg.sender] = totalSupply;
    emit Transfer(0, this, totalSupply, empty);
    emit Transfer(this, msg.sender, totalSupply, empty);
  }
```

**Comment by yann300** [comment]
closing now, please reopen if necessary

**Comment by cyberience** [comment]
Thanks @yann300 I eventually figured that out, it wasn't so obvious. But Thanks for your review.
