### ISSUE TITLE
npm install Error: Cannot find module './soljson.js'

### ISSUE THREAD

**Issue by morolt** [ethereum/remix-ide#1269]
> remix-ide@0.6.2 prepublish /Users/apple/www/remix-ide
> mkdirp build; npm-run-all -ls downloadsolc_root build

[downloadsolc_root]
[downloadsolc_root] > remix-ide@0.6.2 downloadsolc_root /Users/apple/www/remix-ide
[downloadsolc_root] > wget --no-check-certificate https://solc-bin.ethereum.org/soljson.js
[downloadsolc_root]
[downloadsolc_root] --2018-04-20 16:18:21--  https://solc-bin.ethereum.org/soljson.js
[downloadsolc_root] Connecting to 127.0.0.1:1087... connected.
[downloadsolc_root] Proxy request sent, awaiting response... 200 OK
[downloadsolc_root] Length: 7964199 (7.6M) [application/javascript]
[downloadsolc_root] Saving to: ‘soljson.js’
[downloadsolc_root]
[downloadsolc_root]      0K .......... .......... .......... .......... ..........  0% 87.9K 88s
[downloadsolc_root]     50K .......... .......... .......... .......... ..........  1%  241K 60s
[downloadsolc_root]    100K .......... .......... .......... .......... ..........  1%  415K 46s
......... .......... .......... .......... .........
[downloadsolc_root]   7700K .......... .......... .......... .......... .......... 99% 2.59M 0s
[downloadsolc_root]   7750K .......... .......... .......                         100% 3.17M=5.8s
[downloadsolc_root]
[downloadsolc_root] 2018-04-20 16:18:30 (1.32 MB/s) - ‘soljson.js’ saved [7964199/7964199]
[downloadsolc_root]
[build            ]
[build            ] > remix-ide@0.6.2 build /Users/apple/www/remix-ide
[build            ] > browserify src/index.js -o build/app.js
[build            ]
[build            ] Error: Cannot find module './soljson.js' from '/Users/apple/www/remix-ide/node_modules/remix-solidity/node_modules/solc'
[build            ]     at /Users/apple/www/remix-ide/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
[build            ]     at load (/Users/apple/www/remix-ide/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
[build            ]     at onex (/Users/apple/www/remix-ide/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
[build            ]     at /Users/apple/www/remix-ide/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
[build            ]     at FSReqWrap.oncomplete (fs.js:170:21)
[build            ] npm ERR! code ELIFECYCLE
[build            ] npm ERR! errno 1
[build            ] npm ERR! remix-ide@0.6.2 build: `browserify src/index.js -o build/app.js`
[build            ] npm ERR! Exit status 1
[build            ] npm ERR!
[build            ] npm ERR! Failed at the remix-ide@0.6.2 build script.
[build            ] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[build            ]
[build            ] npm ERR! A complete log of this run can be found in:
[build            ] npm ERR!     /Users/apple/.npm/_logs/2018-04-20T08_18_39_930Z-debug.log
ERROR: "build" exited with 1.

npm -v
5.8.0

node -v
v9.11.1

**Comment by yann300** [comment]
sorry for the late answer, could you try removing the `node_modules` folder and rexecuting `npm install` ?
closing now, please reopen if you still have the issue, thanks.

**Comment by ndsun** [comment]
I have the same problem with him, have you solved the problem?
