### ISSUE TITLE
Where is the "linkremixdebugger" script

### ISSUE THREAD

**Issue by thonymg** [ethereum/remix-ide#1270]
Hello, 
I have some issues when i try to install remix-ide with the npm package. and now i try to install it by clonning the source and run some commandes.

But when i launch `npm run setupremix`, the installation fails. Beacuse:
- `pullremix` can't clone package from github 
-> i try to solve this by cloning the package miself, and remove the script from `setupremix`

- after i re-run the install and now `linkremixdebugger` is missing.
this script is not appear in [package.json](https://github.com/ethereum/remix-ide/blob/master/package.json)

Thanks

**Comment by yann300** [comment]
sorry for that, 
actually the script is not necessary anymore

**Comment by yann300** [comment]
addressed by https://github.com/ethereum/remix-ide/pull/1273
