### ISSUE TITLE
cannot input text into the CREATE field.

### ISSUE THREAD

**Issue by tysun** [ethereum/remix-ide#1275]
Sometimes I can enter text into the field beside the pink create button but most of the time it is disabled. I try clicking in it but it doesn't do anything even though the create button works properly. I have my functions set up properly etc.

**Comment by yann300** [comment]
are you sure that the ctor actually contains parameter?

**Comment by tysun** [comment]
I found out what it was. When the function name is the same as the contract name "**greeter**" the `string _greeting` parameter placeholder text shows in the text field and I can enter text. But when the name of this particular function is different there is no placeholder text and I cannot enter text into the text field. Is this a requirement of Solidity? The contract class needs a method with the same name?

Heres a snippet. 

```
    
    contract greeter {
    
    string greeting;
    
    function greeter(string _greeting) public {
        greeting = _greeting;
    }
    
    function setGreeting(string _greeting) public {
        greeting = _greeting;
    }
...// 
```

**Comment by yann300** [comment]
yes in that case the function greeter is the constructor and used for initialization.
