### ISSUE TITLE
Contract creation fails but MetaMask still offers to sign?

### ISSUE THREAD

**Issue by littlebenlittle** [ethereum/remix-ide#1276]
Just running the example contract (ballot.sol) on the Ropsten network. The output is here

https://pastebin.com/pshMkwmv

Remix dumps the error message into the terminal before MetaMask prompts to sign the transaction. Once you agree to sign, the contract appears in MetaMask as failed.

**Comment by yann300** [comment]
Seems to be related to metamask, are you on the last version? Best would be to ask in the metamask channel if they have already seen that...

**Comment by yann300** [comment]
closing, please reopen if needed
