### ISSUE TITLE
call to C.anyfunction errored: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Abdeljalil95** [ethereum/remix-ide#1279]
my contract gives the error when I deploy and I set 'Value: 2000000000 wei'

```
pragma solidity ^0.4.8;
contract A {
   // my functions
}
contract B {
    // my functions
}
contract C is A, B {
   function buy()public payable returns (uint amount){
     //in this function i use some ether
   }
}
```

any function give me 
**call to testaAFC.anyfunction errored: Cannot read property 'length' of undefined**

**Comment by yann300** [comment]
you got this calling `buy` ?
Are you using the javascript VM? in that case please try to switch to a testnet using metamask for instance. we have a bug in the internal VM that might cause this

**Comment by Abdeljalil95** [comment]
yees I use javascript VM.. but when i use metamask and ropsten network and I calling `bay` , remix give me 
that : ``Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending? ``

thank you

**Comment by yann300** [comment]
well you could force send, and then debug the transaction to check why it has failed.
Do you do in `buy` something that could cause a revert or a throw?

**Comment by Abdeljalil95** [comment]
that what i do in the `buy`
```
function buy()public payable returns (uint montant){
        require(!comptBloque[msg.sender]);        
        montant= msg.value * buyPrix;     
        require(balanceOf[this] >= montant);              
        balanceOf[msg.sender] += montant;                
        balanceOf[this] -= montant;                        
        emit Transfer(this, msg.sender, montant);          
        return montant;                                  
    }
```

**Comment by yann300** [comment]
After sending the tx try debugging it to check where it fails

**Comment by yann300** [comment]
a fix has been pushed to remix.ethereum.org (by bumping ethereumjs-vm version).
I close that one, please reopen if you still have the issue
