### ISSUE TITLE
Support EVM version as a configuration setting

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#1282]
THe standard JSON IO accepts an EVM version now (`settings.evmVersion`).

It would be nice to support it as a setting. (If not specified it currently defaults to Byzantium).

**Comment by axic** [comment]
This seems to be a more needed feature now, for more context:
> Recent compiler versions introduced `evmVersion` as a setting in the JSON. If the field is missing, it defaults to `byzantium` which enables the use of `returndatacopy`. This has caused some issues with non-compliant ERC20 token contracts (see https://github.com/ethereum/solidity/issues/4116 for more).
> 
> Other options include `homestead`, `spuriousDragon` and `tangerineWhistle`. It would make sense to support this option so that those requiring it could resort to the old, unsafe, behaviour.

I've also raised this at truffle: https://github.com/trufflesuite/truffle-compile/issues/72

**Comment by holgerd77** [comment]
[v2.4.0](https://github.com/ethereumjs/ethereumjs-vm/releases/tag/v2.4.0) release of the VM is now out. Let me know if you have questions on this or need any help! You can now instantiate the VM with the ``opts.hardfork`` parameter set to either ``byzantium`` or ``constantinople``.

**Comment by axic** [comment]
Depends on #1620.

**Comment by axic** [comment]
With 0.5.5 it will default to Petersburg (and not Byzantium), unless the field is specified. If Remix doesn't fix #1620, then the only quick solution is hardcoding `Byzantium` in Remix.

**Comment by axic** [comment]
To me it seems this was implemented. Please reopen if not, @yann300 @LianaHus.
