### ISSUE TITLE
[Terminal] Cannot expand Transaction result

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1283]
Expanding a transaction result in the terminal if the contract to whom the tx is sent is unknown throws a JavaScript error.

To reproduce: 
 - connect to a testnet using metamask
 - in the terminal, select "listen on network"
 - if necessary in the dropdown list on the left select "all transaction"
 - wait for txs to come in
 - and try to expand one

**Comment by ninabreznik** [comment]
Fixed with https://github.com/ethereum/remix-ide/pull/1287
