### ISSUE TITLE
JavaScript VM libraries don't work?

### ISSUE THREAD

**Issue by rainbowcreatures** [ethereum/remix-ide#1284]
Sorry if this is already known, but even with a simple "hello world" library I'm unable to deploy in JS VM on remix. Deployment of the library shows as 0x0 Transaction mined but execution failed, and subsequently, a contract function calling any library function will fail. 

When deploying the same library to ropsten, it works fine. 

And on remix-alpha, it seems to be working fine in JS VM - but I'm having a problem executing other parts of my contract, which work fine on stable remix...so I can't use JS VM for testing at all:(

**Comment by yann300** [comment]
sorry for that, the fix for libraries deployment is going to be released soon.
could you describe the other issue you have in remix-alpha.ethereum.org?

**Comment by rainbowcreatures** [comment]
cool, thanks! - any idea when this could be resolved? (I don't mind actually if alpha remix works fine).

as for the other issue, it was me being blind, set the gas too low and the contract wasn't even properly deployed. It was odd that I could still try to call functions through the inputs (but they were returning undefined errors). Also, I didn't notice the transaction result in the log like on the stable remix where it says "0x1 transaction mined and executed" or somesuch. That line is missing or is displayed in a different way? That added to my confusion.
