### ISSUE TITLE
sha256 returns "0x"

### ISSUE THREAD

**Issue by wenxinleong** [ethereum/remix-ide#1289]
a simple smart contract as below works ok on remix debugger, but failed on private network (`go-ethereum-1.8.6`). Deployment is ok, but `contract.getSha256.call()` will return `0x` . Same piece of code compiled on older remix (cannot recall the date) works ok, thus believe the bug is on remix than go-ethereum.

```
pragma solidity ^0.4.13;

/* Online compiler https://remix.ethereum.org */

contract test{
    function getSha256() external pure returns (bytes32) {

        bytes32 hash = sha256("12345678");

        return (hash);
    }
}
```

**Comment by yann300** [comment]
hmm I just tried can can't reproduce.. are you on remix.ethereum.org ?

**Comment by wenxinleong** [comment]
yes it is complied on remix.ethereum.org . You have to deploy it on a private net to see the problem.

**Comment by yann300** [comment]
I did that... trying again, which compiler version are you using?

**Comment by wenxinleong** [comment]
ok i did a quick check, 
it works ok on version: 0.4.21+commit.dfe3193c.Emscripten.clang
it failed since version: 0.4.22+commit.124ca40d.Emscripten.clang

**Comment by wenxinleong** [comment]
sorry typo i mean failed since "0.4.22+commit.4cb486ee.Emscripten.clang"

**Comment by yann300** [comment]
wow I really can't reproduce...
@axic @chriseth any ideas?

**Comment by wenxinleong** [comment]
I'll be out of office for 2 days, will do more testing when I return to determine which nightly commit causing it.

**Comment by chriseth** [comment]
@wenxinleong these problems are usually caused by not selecting the byzantium hard fork on the private network.

**Comment by wenxinleong** [comment]
ok i’ll check that once i return, update soon.

**Comment by wenxinleong** [comment]
Enabling byzantium in genesis config file do fixed the problem, thanks all!
