### ISSUE TITLE
clear params on udapp after submit

### ISSUE THREAD

**Issue by serapath** [ethereum/remix-ide#1295]
if udapp is expanded and filled out and submitted, the input field don't clear, so if you want to use it again you have to first manually clear and/or overwrite existing params

**Comment by yann300** [comment]
I believe this is fixed or about to be fixed in https://github.com/ethereum/remix-ide/pull/1307 right ? @ryestew

**Comment by ryestew** [comment]
yes - this is done in the PR that will be pushed in a few min
