### ISSUE TITLE
simplify development and reduce load times

### ISSUE THREAD

**Issue by serapath** [ethereum/remix-ide#1305]
We should:
1. cache compilers locally to save the time to reload them
2. change the app in a way that doesn't require a manual "clear cache + hard reload" to apply changes

It really takes a lot of time over time to use the devtools to reset the application cache and then hard reload the app just to see changes.

I think if we change that, we can actually even move to a real-time workflow where remix occupies one half of the screen and the other is occupied by your code editor and every time you save the file we get an instant update.

---

If this is a change we want we should maybe even give it a very high priority because this will speed up all other issues by saving us time during development and debugging processes

**Comment by yann300** [comment]
duplicate https://github.com/ethereum/remix-ide/issues/1245
