### ISSUE TITLE
Remix Tab hangs if a function is called recursively

### ISSUE THREAD

**Issue by prashantprabhakar** [ethereum/remix-ide#1306]
Hi just tried sending a transaction using Remix compiler and the remix tab in Chrome browser hanged immediately.  While all other tabs in the browser were working properly. 

I tried the same again, the same happened again. After some time tab crashes with **Aw, Snap !** page.

I will debug into this more so that I can provide a more clear way to reproduce, but I guess this can be reproduced with any complex contract. 

**EDIT:**
 I tried debugging the code, I realized that I was calling a function in same function. 

**Steps to replicate**

```
pragma solidity ^0.4.23;

contract TestRemix{
    uint a = 10;
    
    function calculateA() public view returns (uint){
        return calculateA();
    }
}
```

**Actual Behaviour**
If you deploy this contract and call function `calculate A()`, the tab becomes unresponsive. 

**Expected Behaviour**
The compiler should show and error message like `out of gas`.

**Comment by LianaHus** [comment]
is not hanging now.
