### ISSUE TITLE
error: Failed to decode output: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by RemyAZEMA** [ethereum/remix-ide#1315]
Hi,

I have this error when I call any function after deployment => **error: Failed to decode output: TypeError: Cannot read property 'length' of undefined**

I had this error a first time and I solved it by increasing the gas limit before deploying my contract.

Today I add some functions in my contract and this error is comme back. I tried to increase again gas limit by this time didn't work.

Is it possible my contract is too big ? Do you know a limit of size contract in Remix ?

I think this error is very generic and I have a lot of trouble finding what's wrong.

Please, could you tell me the different issues to slove this problem ?

Thanks you very much.
Rémy

**Comment by hypermine-bc** [comment]
Increase the gas price while deploying the contract... its an issues in the latest version(I think).. and then try it once again.. same happened with me once.

**Comment by hypermine-bc** [comment]
https://github.com/ethereum/remix-ide/issues/1303 checkout this thread

**Comment by RemyAZEMA** [comment]
Hi hypermine-bc,

Thanks for answers.
I tried this solution but it doesn't work in this case.

Currently I can't continue my dapp developpement.
The only issue I have found is to delete some secondaries fonctions to reduce contract's size. But this is not a good way. There is a lot of things I want to add in this dapp.

Do you know an other way to solves it ?

**Comment by yann300** [comment]
is the deployment of the contract was ok? @RemyAZEMA 
You could PM the contract code if you want, I can take look.

**Comment by RemyAZEMA** [comment]
@yann300 
Hi, I would like send you my contract code by PM but I don't know do that on github.
Is there a form on github to send private massage?

**Comment by RemyAZEMA** [comment]
I solved temporaly this problem by reduce the lines of code in my contract.
I suspect that Remix can not handle a large contract.

**Comment by yann300** [comment]
The issue was that the deployment failed (out of gas) for very large contract but the contract interfact was still appended to the UI, that was confusing.
