### ISSUE TITLE
Firefox requires page refresh to display contract's getter/ setter inputs in Run tab

### ISSUE THREAD

**Issue by morkeltry** [ethereum/remix-ide#1327]
After 'Deploy', contract is created and shows dropped down in Run tab, but only buttons relating to functions which were already in Storage when page loaded are shown.
Any changes since last page refresh show only in code pane and do not result in buttons in the drop down area of the contract in Run tab.

Refreshing page updates it and buttons then show after Deploy.

FF: 60.0.1 (64bit) for Ubuntu
url contains version=soljson-v0.4.24 - is that the IDE version? Anyway, IDE is the version at remix.ethereum.org today, 23 May 2018.

**Comment by yann300** [comment]
what do yo mean by `relating to functions which were already in Storage` ? browser storage?
I tried with an earlier version of firefox and it works. will investigate more though.
