### ISSUE TITLE
How can I push25 bytes?

### ISSUE THREAD

**Issue by zheng-bin** [ethereum/remix-ide#1338]
The reason：
1. My address is 50.
2. The ethereum address is 40.
3.  The  remix-ide only push 20.
4.  So  1&2,  The first ten will become 0.
Please see the picture:
![image](https://user-images.githubusercontent.com/18119716/40932463-fa132150-6860-11e8-8ca0-1d15924322ad.png)

I add the log like this:
```
diff --git a/core/vm/instructions.go b/core/vm/instructions.go
index 1d51796..6c21a3b 100755
--- a/core/vm/instructions.go
+++ b/core/vm/instructions.go
@@ -221,7 +221,9 @@ func opIszero(pc *uint64, evm *EVM, contract *Contract, memory *Memory, stack *S
 
 func opAnd(pc *uint64, evm *EVM, contract *Contract, memory *Memory, stack *Stack) ([]byte, error) {
        x, y := stack.pop(), stack.pop()
+       fmt.Println("opAnd stack.pop  x,y:", common.BigToAddress(x).String(),"   ", common.BigToAddress(y).String())
        stack.push(x.And(x, y))
+       fmt.Println("After x.And(x, y):", common.BigToAddress(x.And(x,y)).String())
 
        evm.interpreter.intPool.put(y)
        return nil, nil
diff --git a/core/vm/interpreter.go b/core/vm/interpreter.go
index 3faa987..7069ecc 100755
--- a/core/vm/interpreter.go
+++ b/core/vm/interpreter.go
@@ -133,6 +133,7 @@ func (in *Interpreter) Run(snapshot int, contract *Contract, input []byte) (ret
        for atomic.LoadInt32(&in.evm.abort) == 0 {
                // Get the memory location of pc
                op = contract.GetOp(pc)
+               fmt.Println("current opcode:", op, "     program counter:", pc)
 
                // get the operation from the jump table matching the opcode
                operation := in.cfg.JumpTable[op]

```
**Where should I modify the ide to push25?**
Thanks!!!

**Comment by zheng-bin** [comment]
**``**

**Comment by yann300** [comment]
could you pinpoint how the evm code is generated?

**Comment by zheng-bin** [comment]
The code REC20 is generated by http://remix.ethereum.org.
Using the same evm code,the following is a comparison of my chain and Ethereum.
Ethereum:
![image](https://user-images.githubusercontent.com/18119716/40965939-b1369db4-68e1-11e8-8b66-9b5d7f5b0c59.png)
 my chain:
![image](https://user-images.githubusercontent.com/18119716/40965843-72b47a98-68e1-11e8-90f4-3848fd57af08.png)

Should I change the code in https://github.com/ethereum/solidity?

**Comment by yann300** [comment]
Could you post the solidity code ? how your chain is generated? is this a private geth node?
