### ISSUE TITLE
Colors in Style Guide

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/remix-ide#1342]
I was checking out Remix-alpha and figured out I don't really like all the colors in this view for example. I took the colors we have defined in the style guide but this green for example doesn't feel right. I didn't check the dark theme, but I noticed once that some elements don't adapt nicely or they are in some cases not even visible.

![screenshot_2018-06-04_21-46-09](https://user-images.githubusercontent.com/1076427/40978367-5eb2ac4c-68cb-11e8-92a6-2045c93b3648.png)

Transactions recorded should also have a circle around like Transactions pending
![screenshot_2018-06-05_14-20-29](https://user-images.githubusercontent.com/1076427/40978518-bd1c3e74-68cb-11e8-8905-ba68510d7e7d.png)
![screenshot_2018-06-05_14-20-15](https://user-images.githubusercontent.com/1076427/40978519-bd389092-68cb-11e8-9b3c-585059fbc42e.png)

**Comment by thecryptofruit** [comment]
Is this issue considered only for alpha? Currently stable Remix dark theme doesn't make selections visible in some cases (e.g. partial select of a function parameter), though alpha is much nicer.
