### ISSUE TITLE
how can geth cmd deploy two dependency contracts?

### ISSUE THREAD

**Issue by huzhengkui** [ethereum/remix-ide#1348]
Hi, guys,
 I met a problem. there are two contracts A and B.A use B's function,and B use A's function 

Expected behaviour

1 contract A and contract B can deploy successfully
2 A can call the function of B

Actual behaviour

A call function of B failed

**Comment by yann300** [comment]
A should have a reference of B. is it the case?
please go to https://gitter.im/ethereum/remix for asking support
