### ISSUE TITLE
debug in remix

### ISSUE THREAD

**Issue by zhuimengshaonian66** [ethereum/remix-ide#1364]
pragma solidity ^0.4.18;

contract  myToken{
     mapping(address =>mapping(address =>uint)) allowed;

    
       function allowance(address af,address spender) public view returns (uint remaining) {
        return allowed[af][spender];
    }
    
    
}
when i want to test the function allowance when i transfer two address in bower remix it return fault:
call to FixedSupplyToken.allowance errored: Error encoding arguments: SyntaxError: Unexpected token x in JSON at position 47

**Comment by yann300** [comment]
this issue should be fixed in `remix-alpha`. 
in remix.ethereum.org please try to expand the param input editor, if that's not working try wrapping addresses with double quote.

**Comment by zhuimengshaonian66** [comment]
@yann300  thanks you but i can solve  ,   now  i also fund a new bug   ho  my god  sad

**Comment by yann300** [comment]
please could you reopen an issue with the bug you've found.
closing that one
