### ISSUE TITLE
Visual Bug (UI/UX)

### ISSUE THREAD

**Issue by aj07** [ethereum/remix-ide#1368]
Browser: Firefox
There should be proper alignment. Circled area are given as an reference.  

![screenshot from 2018-06-17 12-22-08](https://user-images.githubusercontent.com/9623159/41505572-6d0700b0-7229-11e8-8cb4-ee7ff9dac3b3.png)

Also 

![screenshot_2018-06-19_02-49-26](https://user-images.githubusercontent.com/1076427/41571515-76dca174-736b-11e8-86c9-b4b3b7d1d73b.png)

![screenshot_2018-06-19_02-50-44](https://user-images.githubusercontent.com/1076427/41571551-a1d62210-736b-11e8-8914-3f7e739b8a10.png)

![screenshot_2018-06-19_02-52-21](https://user-images.githubusercontent.com/1076427/41571627-f02cd774-736b-11e8-8f3c-39e6d4e59241.png)

PLUS - At Address and Deploy should be turned the same (first button, then input, or vice versa)

![screenshot_2018-06-19_02-51-59](https://user-images.githubusercontent.com/1076427/41571596-da4987cc-736b-11e8-9c34-c2d7eb9559f4.png)

Button has also a visual bug - on left side it has border radius and on the right not

![screenshot_2018-06-19_02-58-08](https://user-images.githubusercontent.com/1076427/41571761-a4d17ad6-736c-11e8-89b4-96c898b636fa.png)

**Comment by vendor77777** [comment]
Wie kann ich EIPs zurück geben?

atm0sphere <notifications@github.com> schrieb am So., 17. Juni 2018, 08:56:

**Comment by yann300** [comment]
@ninabreznik could this be closed?

**Comment by ryestew** [comment]
1. The transact button in the expanded view of a function still needs the rounded corners. 
2. The issue "At Address and Deploy should be turned the same (first button, then input, or vice versa)" still needs to be addressed.  But everything else I believe has been addressed.  I'll confer with @ninabreznik about the second.  I'll make a PR for updating the rounded edges.

**Comment by yann300** [comment]
thanks for the update @ryestew
