### ISSUE TITLE
remix-id has a code limit ?

### ISSUE THREAD

**Issue by KY-Jung** [ethereum/remix-ide#1371]
HI
I got message "Transaction mined but execution failed" after deploy.

My contract code is about 600 lines.
There is no compile error.
And I set much more gas.

Finally I started to delete my code.
After so many lines were deleted, my contract deployed sucessfully.

I think remix-ide has a code limit.

**Comment by yann300** [comment]
would you please try to deploy the code using a script and check if the deployment still fail?

**Comment by yann300** [comment]
we've added an alert that should warn you if the deployment fails with eip-170
