### ISSUE TITLE
Theme selection radio buttons are rendered as checkboxes in Chrome

### ISSUE THREAD

**Issue by arun1595** [ethereum/remix-ide#1372]
### Screenshot

![image](https://user-images.githubusercontent.com/7039523/41607159-fc4cb56c-73aa-11e8-8c59-9f7c68e6cc35.png)

I had a look at the code responsible for rendering the theme selection settings and we're indeed rendering radio buttons. I couldn't figure out why it's rendered as checkboxes.

Chrome version: 67.0.3396.79 (Official Build) (64-bit)

**Comment by yann300** [comment]
closing now as it is fixed in remix-alpha.ethereum.org, soon to be deployed live

**Comment by arun1595** [comment]
@yann300 Cool, didn't know it was already fixed.

May I know what the issue was?
