### ISSUE TITLE
Don't allow deleting localhost path from the UI or warn the user that "deleting" does not mean "disconnecting".

### ISSUE THREAD

**Issue by k06a** [ethereum/remix-ide#1379]
This is terrible. The directory should be just disconnected - not deleted of course! Can the directory be restored?

**Comment by yann300** [comment]
It is disconnected, it should not have been removed. Could you precise the use case so we can help on this?

**Comment by k06a** [comment]
@yann300 I clicked on `localhost` and selected `Delete`. I was sure this will mean deletion from the tree (disconnection)

**Comment by yann300** [comment]
Well yes in that case I am afraid there is not so much to do.
The action to disconnect is the same as the connect to localhost. But I guess your files are still in the trashbin.
We will update the semantic here

**Comment by k06a** [comment]
@yann300 for some reason trash bin does not contain this files (I am using latest macOS). I think this also should be fixed.
