### ISSUE TITLE
Remix v0.6.4-alpha.1 bug

### ISSUE THREAD

**Issue by aj07** [ethereum/remix-ide#1384]
" Unable to import code " Error msg appears. This bug is appearing only for Firefox not for Chrome.  
![screenshot from 2018-07-02 11-41-09-1 copy](https://user-images.githubusercontent.com/9623159/42149357-78e30fde-7df3-11e8-87d7-5b873b756c35.png)

**Comment by yann300** [comment]
addressed by https://github.com/ethereum/remix-ide/pull/1383
