### ISSUE TITLE
Sync up with remix repo

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1399]
A lot of renaming and refactor happened in remix repo, remix-ide need to be updated accordingly.
basically:
 - web3 is no more a global object in the debugger code
 - remix-solidity is splitted in remix-solidity-analyzer and remix-solidity-decoders and remix-solidity (compiler)

**Comment by ansermino** [comment]
Could I lend a hand with this?

**Comment by yann300** [comment]
Thanks for proposing your help, There are still some PR to merge in remix before before we can continue with this PR

**Comment by ansermino** [comment]
Okay cool. Would love to contribute as I use this project almost everyday. Let me know :smiley_cat:

**Comment by yann300** [comment]
@ansermino feel free to take issue you feel like to handle ;)
the sync is done now .
@iurimatias
