### ISSUE TITLE
Remix mock compiler error 

### ISSUE THREAD

**Issue by DroZeN3** [ethereum/remix-ide#1404]
I am trying to compile a contract and I am getting this error "mock compiler: source not found". Does anyone know why I am getting this?

**Comment by le4ker** [comment]
I have the same issue

**Comment by LianaHus** [comment]
@yann300 is this still relevant?

**Comment by gcsfred2** [comment]
Same issue.

**Comment by yann300** [comment]
@gcsfred2 can you give more info, are you usin remix.ethereum.org or the npm package?
