### ISSUE TITLE
Unable to  copy the whole input string from transaction detail .

### ISSUE THREAD

**Issue by aasimali141290** [ethereum/remix-ide#1408]
When I copy the input from the debug it is only copying the partial string like 0x0da...00b instead of the whole string.

<img width="764" alt="screen shot 2018-07-11 at 11 37 18 am" src="https://user-images.githubusercontent.com/23409265/42583467-ffb135ce-84fe-11e8-92f4-9b3b16c3d738.png">

**Comment by yann300** [comment]
fixed by https://github.com/ethereum/remix-ide/pull/1409
