### ISSUE TITLE
Cannot find module 'remix-core'

### ISSUE THREAD

**Issue by jilangsanqian** [ethereum/remix-ide#1413]
ubuntu@ubuntu-xenial:~/remix-ide$ npm start

> remix-ide@0.6.4 start /home/ubuntu/remix-ide
> npm-run-all -lpr serve watch onchange remixd

[serve   ]
[serve   ] > remix-ide@0.6.4 serve /home/ubuntu/remix-ide
[serve   ] > execr --silent http-server .
[serve   ]
[onchange]
[onchange] > remix-ide@0.6.4 onchange /home/ubuntu/remix-ide
[onchange] > onchange build/app.js -- npm-run-all lint
[onchange]
[remixd  ]
[remixd  ] > remix-ide@0.6.4 remixd /home/ubuntu/remix-ide
[remixd  ] > ./node_modules/remixd/bin/remixd -s ./contracts
[remixd  ]
[watch   ]
[watch   ] > remix-ide@0.6.4 watch /home/ubuntu/remix-ide
[watch   ] > watchify src/index.js -dv -p browserify-reload -o build/app.js
[watch   ]
[watch   ] WS server listening on  43452
[remixd  ] example: --dev-path /home/devchains/chain1 --mist --geth --frontend /home/frontend --frontend-port 8084 --auto-mine
[remixd  ]
[remixd  ]   Usage: remixd -s <shared folder>
[remixd  ]
[remixd  ]   Provide a two ways connection between the local computer and Remix IDE
[remixd  ]
[remixd  ]   Options:
[remixd  ]
[remixd  ]     -s, --shared-folder <path>            Folder to share with Remix IDE
[remixd  ]     -m, --mist                            start mist
[remixd  ]     -g, --geth                            start geth
[remixd  ]     -p, --dev-path <dev-path>             Folder used by mist/geth to start the development instance
[remixd  ]     -f, --frontend <front-end>            Folder that should be served by remixd
[remixd  ]     -p, --frontend-port <front-end-port>  Http port used by the frontend (default 8082)
[remixd  ]     -a, --auto-mine                       mine pending transactions
[remixd  ]     -r, --rpc <cors-domains>              start rpc server. Values are CORS domain
[remixd  ]     -rp, --rpc-port                       rpc server port (default 8545)
[remixd  ]     -h, --help                            output usage information
[remixd  ] [WARN] Any application that runs on your computer can potentially read from and write to all files in the directory.
[remixd  ] [WARN] Symbolinc links are not forwarded to Remix IDE
[remixd  ]
[remixd  ] [WARN] Symbolic link modification not allowed : ./contracts | /home/ubuntu/remix-ide/contracts
[remixd  ] Shared folder : ./contracts
[remixd  ] Mon Jul 16 2018 07:01:32 GMT+0000 (UTC) Remixd is listening on 127.0.0.1:65520
[watch   ] Error: Cannot find module 'remix-core' from '/home/ubuntu/remix-ide/src/app/debugger'
[onchange]
[onchange] > remix-ide@0.6.4 lint /home/ubuntu/remix-ide
[onchange] > standard | notify-error
[onchange]
[watch   ] Error: Cannot find module 'remix-core' from '/home/ubuntu/remix-ide/src/app/debugger/remix-debugger/src/ui'
[watch   ] Error: Cannot find module 'remix-core' from '/home/ubuntu/remix-ide/src/app/debugger/remix-debugger/src/ui'
[watch   ] Error: Cannot find module 'remix-core' from '/home/ubuntu/remix-ide/src/app/debugger/remix-debugger/src/ui'
[watch   ] Error: Cannot find module 'remix-core' from '/home/ubuntu/remix-ide/src/app/debugger/remix-debugger/src/ui'
[watch   ] Error: Cannot find module 'remix-core' from '/home/ubuntu/remix-ide/src/app/debugger/remix-debugger/src/ui'
[watch   ] Error: Cannot find module 'remix-core' from '/home/ubuntu/remix-ide/src/app/debugger/remix-debugger/src/ui'

ubuntu@ubuntu-xenial:~/remix-ide$ ll /home/ubuntu/remix-ide/src/app/debugger/remix-debugger/src/ui/
total 104
drwxrwxr-x 3 ubuntu ubuntu 4096 Jul 16 03:17 ./
drwxrwxr-x 3 ubuntu ubuntu 4096 Jul 16 03:17 ../
-rw-rw-r-- 1 ubuntu ubuntu 7295 Jul 16 03:17 ButtonNavigator.js
-rw-rw-r-- 1 ubuntu ubuntu  923 Jul 16 03:17 CalldataPanel.js
-rw-rw-r-- 1 ubuntu ubuntu  932 Jul 16 03:17 CallstackPanel.js
-rw-rw-r-- 1 ubuntu ubuntu 2755 Jul 16 03:17 CodeListView.js
-rw-rw-r-- 1 ubuntu ubuntu 6244 Jul 16 03:17 DropdownPanel.js
-rw-rw-r-- 1 ubuntu ubuntu 5917 Jul 16 03:17 Ethdebugger.js
-rw-rw-r-- 1 ubuntu ubuntu 1989 Jul 16 03:17 FullStoragesChanges.js
-rw-rw-r-- 1 ubuntu ubuntu 1046 Jul 16 03:17 MemoryPanel.js
-rw-rw-r-- 1 ubuntu ubuntu 1817 Jul 16 03:17 Slider.js
-rw-rw-r-- 1 ubuntu ubuntu 2389 Jul 16 03:17 SolidityLocals.js
-rw-rw-r-- 1 ubuntu ubuntu 3116 Jul 16 03:17 SolidityState.js
-rw-rw-r-- 1 ubuntu ubuntu 2093 Jul 16 03:17 SolidityTypeFormatter.js
-rw-rw-r-- 1 ubuntu ubuntu  895 Jul 16 03:17 StackPanel.js
-rw-rw-r-- 1 ubuntu ubuntu 2515 Jul 16 03:17 StepDetail.js
-rw-rw-r-- 1 ubuntu ubuntu 5615 Jul 16 03:17 StepManager.js
-rw-rw-r-- 1 ubuntu ubuntu 1574 Jul 16 03:17 StoragePanel.js
drwxrwxr-x 2 ubuntu ubuntu 4096 Jul 16 03:17 styles/
-rw-rw-r-- 1 ubuntu ubuntu 6270 Jul 16 03:17 TxBrowser.js
-rw-rw-r-- 1 ubuntu ubuntu 3424 Jul 16 03:17 VmDebugger.js

**Comment by yann300** [comment]
we are in the process of cleaning the remix repository so you might experience some issue...
will it work with `npm run build && npm run serve` ?

**Comment by cryptoserge** [comment]
I experienced the same situation. I  tried `npm run build && npm run serve`, but it didn't work.
I am waiting for the process of cleaning the remix repository.

**Comment by ethernodeio** [comment]
What happens is `npm run setupremix` removes the `remix-core/` and two other dirs from `./node-modules/ dirt. Clones the `remixe` repo into the root of `remix-ide` and sim 

``` 
#The problems start here. this repo is missing the dir remix-core that gets removed from node_modules and simlink to the new remix dir
git clone https://github.com/ethereum/remix

#This is the problem child, when the above repo gets cloned this dir does not exist in it.
#this line removes dir remix-core from the dir node_modules and sim links it in remix-ide/remix/remix-core
cd node_modules && rm -rf remix-core && ln -s ../remix/remix-core remix-core && cd ..

#this line removes dir remix-lib from the dir node_modules and sim links it in remix-ide/remix/remix-lib
> cd node_modules && rm -rf remix-lib && ln -s ../remix/remix-lib remix-lib && cd ..

#this line removes dir remix--solidity from the dir node_modules and sim links it in remix-ide/remix/-solidity
> cd node_modules && rm -rf remix-solidity && ln -s ../remix/remix-solidity remix-solidity && cd ..
```

Solution: make a backup of ./node_modules/remix-core dir
Run npm run setupremix
Then copy the backed up `remix-core` dir back into `remix-ide/remix/`

**Comment by jilangsanqian** [comment]
@ethernodeio 这样也可以，后来我直接修改的package.json 文件 ，将linkremixcore改为cd node_modules && cp -r remix-core ../remix/remix-core && rm -rf remix-core && ln -s ../remix/remix-core remix-core && cd ..   问题就解决啦。
 thank you!!

**Comment by jilangsanqian** [comment]
@yann300 thanks for your help
