### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by l3m0n** [ethereum/remix-ide#1419]
There is a big bug in the installation. I have repeated the installation for more than 10 times.

```
git clone https://github.com/ethereum/remix-ide.git
cd remix-ide
npm install
npm run setupremix  # this will clone https://github.com/ethereum/remix for you and link it to remix-ide
npm start
```

Why?

```
Error: Cannot find module 'remix-core' from ?
Error: Cannot find module './soljson.js' ????
```

so Do I need to run this command？`npm run build`？
Who can tell me to install it correctly？Why not give a DockerFile？

**Comment by l3m0n** [comment]
i install in ubuntu and macos by git. but all is failed!
so i think readme is really useless....

**Comment by yann300** [comment]
please don't run `npm run setupremix` .
we are in the process of cleaning up the remix repo, so that will be fixed soon.
