### ISSUE TITLE
Extension UX integration

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1423]
- Add a plugin tab, plugin started from there as panel in the tab but can be taken out of the tab as modal.
 - When Minimized / closed, just put the minimized to the plugin tab.
 - Ability to dock a plugin content.
 - Close is currently not in the style.
 - Dragging action sometimes doesn't work.
 - When minimized, go in a fixed place.

**Comment by ninabreznik** [comment]
Some UX for inspiration

![screenshot_2018-07-24_16-02-29](https://user-images.githubusercontent.com/1076427/43147727-97c97a72-8f5b-11e8-91a8-218765abd706.png)

**Comment by ryestew** [comment]
Here are 10 images:

![1-ux-redo_v0 1b_no-icon-col](https://user-images.githubusercontent.com/6050001/46028604-5aee0600-c0f1-11e8-8d70-03e56bbc8030.png)
![2- ux-redo_v0 1-rt-icons-over-panels](https://user-images.githubusercontent.com/6050001/46028616-604b5080-c0f1-11e8-9c48-bbff7d9cb4a6.png)
![3-ux-redo_v0 1-rt-icons-over-panels-a](https://user-images.githubusercontent.com/6050001/46028623-63464100-c0f1-11e8-8b3f-5266500d994e.png)

**Comment by ryestew** [comment]
![4-ux-redo_v0 1-icon-rt](https://user-images.githubusercontent.com/6050001/46028645-6f320300-c0f1-11e8-8913-b856512938d3.png)
![5-ux-redo_v0 1-icon-col-middle](https://user-images.githubusercontent.com/6050001/46028649-72c58a00-c0f1-11e8-848c-343593200a11.png)
![6-ux-redo_v0 1a](https://user-images.githubusercontent.com/6050001/46028652-7527e400-c0f1-11e8-9a99-46f462e1a8e6.png)

**Comment by ryestew** [comment]
Next Round

[0-zones.pdf](https://github.com/ethereum/remix-ide/files/2608510/0-zones.pdf)

**Comment by ryestew** [comment]
[1-info-screen.pdf](https://github.com/ethereum/remix-ide/files/2608515/1-info-screen.pdf)

**Comment by ryestew** [comment]
[2-collaped-fexpl.pdf](https://github.com/ethereum/remix-ide/files/2608518/2-collaped-fexpl.pdf)

**Comment by ryestew** [comment]
[3-exp-fexpl.pdf](https://github.com/ethereum/remix-ide/files/2608519/3-exp-fexpl.pdf)

**Comment by ryestew** [comment]
[4-plugins.pdf](https://github.com/ethereum/remix-ide/files/2608520/4-plugins.pdf)

**Comment by ryestew** [comment]
[5-debugger-left-icons-rt.pdf](https://github.com/ethereum/remix-ide/files/2608521/5-debugger-left-icons-rt.pdf)

**Comment by ryestew** [comment]
[6-plugins-docked.pdf](https://github.com/ethereum/remix-ide/files/2608523/6-plugins-docked.pdf)

**Comment by ryestew** [comment]
This image show the 3 main panels.
1. icon panel - The main switchbox 
2. swap panel - All the tabs currently on the right side will appear here - but they will be turned off and on by clicking on the icons in the icon panel.
3. tab panel - to allow for more than just Ace editor files ( like it currently is).  Will be able to accept iFrames and internal modules - if configured to show up here.

The terminal is not shown here in much detail - but it is not changed and is in its current position under the tab panel.
![remixui_v0 4_vsc](https://user-images.githubusercontent.com/6050001/49593386-bb13ea80-f973-11e8-9c9a-eb0f487f1f3c.jpg)
