### ISSUE TITLE
Problem on installing remix-ide

### ISSUE THREAD

**Issue by mbmone** [ethereum/remix-ide#1428]
40465 error code ELIFECYCLE
40466 error errno 1
40467 error remix-solidity@0.1.11 postinstall: `npm-run-all -ls downloadsolc`
40467 error Exit status 1
40468 error Failed at the remix-solidity@0.1.11 postinstall script.
40468 error This is probably not a problem with npm. There is likely additional logging output above.
40469 verbose exit [ 1, true ]

**Comment by iurimatias** [comment]
@mbmone do you get an error when installing scrypt? `npm -g install scrypt`? If so there are some development dependencies or tools missing in your environment. I need to know more information to help you. What OS are you using? and what node version?

**Comment by mbmone** [comment]
@iurimatias Thanks for your reply. I have work out my issues. I removed node.js and used nvm to install  node.js ,Then everything works fine.

**Comment by iurimatias** [comment]
@mbmone good to hear!
