### ISSUE TITLE
[BUG] Contract A doesn't work anymore when I deploy contract B

### ISSUE THREAD

**Issue by creazy231** [ethereum/remix-ide#1430]
I recently had to deploy my second contract on the local Ganache Blockchain (Windows) using http://remix.ethereum.org/.

But every single time I deploy contract B after I deployed contract A, contract A doesn't work anymore. No returns - nothing.

I really need both of the contracts to communicate with them and between.

Anyone else had the same issue or knows how to solve the problem? Thanks

PS: I'm using some of the openzeppelin libraries and get them via. a remote connection using the command "**remixd -s "\<PATH\>"**"
### Code to reproduce:

> test2.sol
```
pragma solidity ^0.4.24;

contract test2 {
    uint value = 1338;

    function getValue() public view returns(uint) {
        return value;
    }

    function setValue(uint _value) public {
        value = _value;
    }
}
```

> test.sol
```
pragma solidity ^0.4.24;

contract test {
    uint value = 1337;

    function getValue() public view returns(uint) {
        return value;
    }

    function setValue(uint _value) public {
        value = _value;
    }
}
```

When I deploy testCoin.sol and then deploy test.sol I cant access any function the testCoin.sol contract provides. The console says "call to test2.getValue" - that's all. No return, no message - simply nothing.

**Comment by yann300** [comment]
`testCoin.balanceOf` ? would it be possible to post the code of testCoin also?

**Comment by creazy231** [comment]
@yann300 updated my example code. Just have these two files open in remix and deploy them one by one. After I deployed the second contract, I cant access anything of the first one.

**Comment by creazy231** [comment]
also noticed, that the developer console in chrome says `Uncaught TypeError: Cannot read property 'status' of null`

**Comment by yann300** [comment]
fix https://github.com/ethereum/remix-ide/pull/1445

**Comment by yann300** [comment]
@creazy231 could you double check please? fix is deployed in remix-alpha.ethereum.org

**Comment by creazy231** [comment]
@yann300 I can confirm that its working on remix-alpha.ethereum.org
could you tell me any ETA when this fix will be pushed to remix.ethereum.org? Thanks

**Comment by yann300** [comment]
should have been pushed today... but probably postpone to the week after 7th september
