### ISSUE TITLE
SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by bitcoin4cashqc** [ethereum/remix-ide#1435]
Is this related to my Firefox or on the remix editor? :(

`SecurityError: The operation is insecure.
start
https://remix.ethereum.org/build/app.js:238497:21
ensureSocket
https://remix.ethereum.org/build/app.js:238576:7
call
https://remix.ethereum.org/build/app.js:238559:7
exists
https://remix.ethereum.org/build/app.js:232356:7
importFileCb
https://remix.ethereum.org/build/app.js:226008:7
[1330]</run/importFileCb/<
https://remix.ethereum.org/build/app.js:226020:9
tryEach/<
https://remix.ethereum.org/build/app.js:15913:9
_withoutIndex/<
https://remix.ethereum.org/build/app.js:13873:16
replenish
https://remix.ethereum.org/build/app.js:11774:17
_eachOfLimit/<
https://remix.ethereum.org/build/app.js:11779:9
eachLimit$1
https://remix.ethereum.org/build/app.js:13959:5
doLimit/<
https://remix.ethereum.org/build/app.js:11809:16
tryEach
https://remix.ethereum.org/build/app.js:15912:5
importFileCb
https://remix.ethereum.org/build/app.js:226019:7
gatherImports
https://remix.ethereum.org/build/app.js:171637:9
[1047]</Compiler/gatherImports/<
https://remix.ethereum.org/build/app.js:171642:13
[1365]</Files/this.get
https://remix.ethereum.org/build/app.js:231512:7
[1330]</run/importFileCb/<
https://remix.ethereum.org/build/app.js:226011:18
[1365]</Files/this.exists
https://remix.ethereum.org/build/app.js:231488:5
importFileCb
https://remix.ethereum.org/build/app.js:226008:7
gatherImports
https://remix.ethereum.org/build/app.js:171637:9
internalCompile
https://remix.ethereum.org/build/app.js:171349:5
compilationFinished
https://remix.ethereum.org/build/app.js:171514:7
[1047]</Compiler/loadWorker/<
https://remix.ethereum.org/build/app.js:171585:11
`

**Comment by yann300** [comment]
which file were you trying to import?
