### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by guyunzhe** [ethereum/remix-ide#1438]
Hello team, I'm a green hand for both linux. I was trying to install Remix IDE environment in my local "Windows Subsystem for Linux".

node version:
v8.11.3
npm version:
5.6.0

I opened the SUSE Linux Enterprise Server environment as administrator and logged in as root.
git clone https://github.com/ethereum/remix-ide.git
cd remix-ide

While I ran the command "npm install", an error occurred:
npm ERR! path /custom/softwares/remix-ide/node_modules/.browser-resolve.DELETE/node_modules/resolve
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rename
npm ERR! Error: EACCES: permission denied, rename '/custom/softwares/remix-ide/node_modules/.browser-resolve.DELETE/node_modules/resolve' -> '/custom/softwares/remix-ide/node_modules/browser-resolve/node_modules/resolve'
......
npm ERR! Please try running this command again as root/Administrator.

Would you please provide some suggestions? Appreciated.
Maybe there are some steps I missed.
Thanks a lot.
Andy

**Comment by yann300** [comment]
tying upgrading npm and node... and perhaps check permission given to the current account also
