### ISSUE TITLE
ACE should use 4 spaces by default and not tabs

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#144]
I think browser-solidity should follow the [style guide](http://solidity.readthedocs.io/en/latest/style-guide.html#indentation): it recommends 4 spaces.

**Comment by Denton-L** [comment]
Hmmm, it appears as if that's already set: https://github.com/ethereum/browser-solidity/blob/master/src/app/editor.js#L156,L157.

It definitely does not behave that way, though... Strange.

**Comment by axic** [comment]
It does actually. If you copy the content from ACE and paste it outside it will be 4 spaces. I guess this comes down to the `softTabs` feature.

**Comment by Denton-L** [comment]
Oh, interesting! I thought that it tabbing would actually insert four spaces that you would be able to manipulate individually... Guess not.
