### ISSUE TITLE
Are optimizations working?

### ISSUE THREAD

**Issue by ajsantander** [ethereum/remix-ide#1440]
I've observed that EVM output often contains sequences of ISZERO opcodes with more than 2 elements. For example, in the EVM opcode structure that returns a boolean value:

```
239 JUMPDEST
240 PUSH1 40
242 DUP1
243 MLOAD
244 SWAP2
245 ISZERO // <------- HERE
246 ISZERO
247 ISZERO
248 ISZERO
249 DUP3
250 MSTORE
251 MLOAD
252 PUSH1 20
254 SWAP1
255 SWAP2
256 ADD
257 DUP2
258 SWAP1
259 SUB
260 SWAP1
261 RETURN
```

This output was obtained with the Enable Optimizations combobox on in Settings.

As far as I can tell, Solidity's CommonSubexpressionEliminator optimizer should take care of this, reducing the four ISZERO sequence to just two.

I've verified this with my solc binary, using the --optimize option:

![screenshot from 2018-08-02 12-22-57](https://user-images.githubusercontent.com/550409/43593673-ce0126ea-964e-11e8-9285-7771e519fe1f.png)

Looking at the compilation metadata, I see that the optimizer is enabled:

![screenshot from 2018-08-02 12-24-25](https://user-images.githubusercontent.com/550409/43593756-fbbec2b8-964e-11e8-9a1a-c303016679b8.png)

So, I wonder, are the optimizations really running?

**Comment by chriseth** [comment]
If the metadata contain the flag, then the optimizer is running. This might be an issue with caching the compilation result, though.

**Comment by ajsantander** [comment]
To try to circumvent caching, I created a new contract:
```
pragma solidity ^0.4.24;

contract CSE {
    function test() public pure returns (bool) {
        return true;
    }
}
```
(Optimizations were enabled before the creation)

Then deployed it and see that the ISZERO quad is still there.

**Comment by chriseth** [comment]
@ajsantander sorry, I cannot reproduce that. Could you tell a bit more about your environment?
