### ISSUE TITLE
[BUG] It seems like always trying connect to localhost...

### ISSUE THREAD

**Issue by yarcowang** [ethereum/remix-ide#1441]
It is OK after clear whole site cache storage. It restores to the original state when visit: `remix.ethereum.org`.

But if you add:
`import "https://raw.githubusercontent.com/ethereum/dapp-bin/master/library/features.sol";`
in `.sol` file and try to compile, remix seems to try connecting to localhost... And then, you'll never go back except clear all cached storage.

**Comment by yann300** [comment]
> remix seems to try connecting to localhost...

how do you see that? by default, when remix is loaded, it connect to the injected provider if there is one. there is an option in the settings to force javascript VM by default

**Comment by yarcowang** [comment]
![remix_-_solidity_ide](https://user-images.githubusercontent.com/1576504/43990566-71c3f680-9d8f-11e8-9c0d-6f05cfec3eaf.png)
![remix_-_solidity_ide](https://user-images.githubusercontent.com/1576504/43990576-82a2b310-9d8f-11e8-913f-99f5a57863f3.png)
![remix_-_solidity_ide](https://user-images.githubusercontent.com/1576504/43990582-97889da8-9d8f-11e8-8236-ac4f431f96fd.png)

**Comment by yann300** [comment]
Remix does not support `raw.githubusercontent.com` like url. Please replace it by the classic url (without `blob/master`.
I put this issue as bug so we can take care of it soon

**Comment by yann300** [comment]
fix https://github.com/ethereum/remix-ide/pull/1456
