### ISSUE TITLE
Remix crashes when debugging a call to this function

### ISSUE THREAD

**Issue by ajsantander** [ethereum/remix-ide#1442]
```
    function run(uint[] _ids) public pure returns (uint[]) {
        return _ids;
    }
```

Passed in params `[1, 2, 3]`. Then clicked debug on the transaction. 1 or 2 steps into and Remix stops responding.

Chromium console displays "paused before potential out of memory crash" at L21983 of app.js
` BN.prototype._initNumber = function _initNumber (number, base, endian) {...`

**Comment by LianaHus** [comment]
can't reproduce
