### ISSUE TITLE
[BUG] "out of gas" but using MetaMask everything works

### ISSUE THREAD

**Issue by creazy231** [ethereum/remix-ide#1450]
I recently noticed, that there is a small bug calculating the gas price. When I run a simple function for example:
```
function giveOwnerTokensFromContract() public onlyOwner {
    uint tokens = tokenContract.balanceOf(address(this));
    tokenContract.transfer(msg.sender, tokens);
}
```
it returns the following error in console:
`VM Exception while processing transaction: out of gas `

but if I run the same function using MetaMask's web3 on my own backend, it calculates a gas price of `61117` and the function success.

**Comment by yann300** [comment]
would you be able to pm the contract code please? would be easier to reproduce
