### ISSUE TITLE
Error when npm start

### ISSUE THREAD

**Issue by Mike2017go** [ethereum/remix-ide#1458]
> remix-ide@0.6.4 start /home/remix-ide
> npm-run-all -lpr serve watch onchange remixd

[watch   ] 
[watch   ] > remix-ide@0.6.4 watch /home/remix-ide
[watch   ] > watchify src/index.js -dv -p browserify-reload -o build/app.js
[watch   ] 
[onchange] 
[onchange] > remix-ide@0.6.4 onchange /home/remix-ide
[onchange] > onchange build/app.js -- npm-run-all lint
[onchange] 
[serve   ] 
[serve   ] > remix-ide@0.6.4 serve /home/remix-ide
[serve   ] > execr --silent http-server .
[serve   ] 
[remixd  ] 
[remixd  ] > remix-ide@0.6.4 remixd /home/remix-ide
[remixd  ] > ./node_modules/remixd/bin/remixd -s ./contracts
[remixd  ] 
[watch   ] WS server listening on  39723
[remixd  ] example: --dev-path /home/devchains/chain1 --mist --geth --frontend /home/frontend --frontend-port 8084 --auto-mine
[remixd  ] 
[remixd  ]   Usage: remixd -s <shared folder>
[remixd  ] 
[remixd  ]   Provide a two ways connection between the local computer and Remix IDE
[remixd  ] 
[remixd  ]   Options:
[remixd  ] 
[remixd  ]     -s, --shared-folder <path>            Folder to share with Remix IDE
[remixd  ]     -m, --mist                            start mist
[remixd  ]     -g, --geth                            start geth
[remixd  ]     -p, --dev-path <dev-path>             Folder used by mist/geth to start the development instance
[remixd  ]     -f, --frontend <front-end>            Folder that should be served by remixd
[remixd  ]     -p, --frontend-port <front-end-port>  Http port used by the frontend (default 8082)
[remixd  ]     -a, --auto-mine                       mine pending transactions
[remixd  ]     -r, --rpc <cors-domains>              start rpc server. Values are CORS domain
[remixd  ]     -rp, --rpc-port                       rpc server port (default 8545)
[remixd  ]     -h, --help                            output usage information
[remixd  ] 
[remixd  ] [WARN] Any application that runs on your computer can potentially read from and write to all files in the directory.
[remixd  ] [WARN] Symbolinc links are not forwarded to Remix IDE
[remixd  ] 
[remixd  ] [WARN] Symbolic link modification not allowed : ./contracts | /home/remix-ide/contracts
[remixd  ] Shared folder : ./contracts
[remixd  ] events.js:165
[remixd  ]       throw er; // Unhandled 'error' event
[remixd  ]       ^
[remixd  ] 
[remixd  ] Error: listen EADDRINUSE 127.0.0.1:65520
[remixd  ]     at Server.setupListenHandle [as _listen2] (net.js:1346:14)
[remixd  ]     at listenInCluster (net.js:1387:12)
[remixd  ]     at doListen (net.js:1502:7)
[remixd  ]     at process._tickCallback (internal/process/next_tick.js:178:19)
[remixd  ]     at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
[remixd  ]     at startup (internal/bootstrap/node.js:201:19)
[remixd  ]     at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
[remixd  ] Emitted 'error' event at:
[remixd  ]     at emitErrorNT (net.js:1366:8)
[remixd  ]     at process._tickCallback (internal/process/next_tick.js:178:19)
[remixd  ]     [... lines matching original stack trace ...]
[remixd  ]     at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
[remixd  ] npm ERR! code ELIFECYCLE
[remixd  ] npm ERR! errno 1
[remixd  ] npm ERR! remix-ide@0.6.4 remixd: `./node_modules/remixd/bin/remixd -s ./contracts`
[remixd  ] npm ERR! Exit status 1
[remixd  ] npm ERR! 
[remixd  ] npm ERR! Failed at the remix-ide@0.6.4 remixd script.
[remixd  ] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[remixd  ] 
[remixd  ] npm ERR! A complete log of this run can be found in:
[remixd  ] npm ERR!     /root/.npm/_logs/2018-08-14T02_17_33_982Z-debug.log
ERROR: "remixd" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remix-ide@0.6.4 start: `npm-run-all -lpr serve watch onchange remixd`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remix-ide@0.6.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-14T02_17_34_085Z-debug.log

As the above log, how to fix it ?

node -v 9.11.2  npm 5.6.0 npm -v 0.33.11

**Comment by yann300** [comment]
look like remixd is already started. could you check that?
if you just want to use remix ide locally,
please take a look at https://github.com/ethereum/remix-ide/releases

**Comment by kennblvnp** [comment]
Yeah How do we fix this?
`npm start` cause an error

**Comment by yann300** [comment]
as an alternative you can use npm run build && npm run serve

**Comment by JacksonTom** [comment]
same problem

**Comment by yann300** [comment]
could you post the error you get please?

**Comment by leeduckgo** [comment]
same again

**Comment by leeduckgo** [comment]
at FSReqCallback.oncomplete (fs.js:169:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remix-ide@0.10.0 build: `browserify src/index.js -o build/app.js --exclude solc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remix-ide@0.10.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liaohua/.npm/_logs/2020-04-28T16_08_27_326Z-debug.log

**Comment by leeduckgo** [comment]
macOS
node: v12
