### ISSUE TITLE
right side UI disappear

### ISSUE THREAD

**Issue by louisliu2048** [ethereum/remix-ide#1471]
I install the latest remix-ide accrod to the instruction [https://github.com/ethereum/remix-ide#installation](url), when I ran the last step: npm start and open the localhost:8080, something strange happend, the right side ui gone! I have try the process many times, use different version of node and npm, but the result is the same.

**Comment by yann300** [comment]
Could you retry now please? we made some modification on remix-ide and remix repo recently, that could have lead to your issue...

**Comment by louisliu2048** [comment]
the latest version seems has some other bugs:

npm ERR! missing script: linkremixcore
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     linkremixlib

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-23T11_49_38_185Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remix-ide@0.7.0 setupremix: `npm run pullremix && npm run linkremixcore && npm run linkremixlib && npm run linkremixsolidity;`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remix-ide@0.7.0 setupremix script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-23T11_49_38_323Z-debug.log

**Comment by yann300** [comment]
yep sorry for that. I just pushed a fix.
by the way you don't need to execute `setupremix` if you just want to run remix without contributong on developement

**Comment by yann300** [comment]
also https://github.com/ethereum/remix-ide/releases/tag/v0.6.4 includes some ways to runu remix locally

**Comment by louisliu2048** [comment]
everything is ok now.  Besides, seems that the instructions need to add `npm run build && npm run serve`, for it will still report "Error: ENOENT: no such file or directory, open 'build/app.js'" before I ran the instruct.
