### ISSUE TITLE
How to switch port?

### ISSUE THREAD

**Issue by dexterchan** [ethereum/remix-ide#1498]
By default, port is 8080. I would like to switch to 8888 to avoid conflict.
When running 
npm start --frontend 8888, 

the application gave error:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remix-ide@0.6.4 start: `npm-run-all -lpr serve watch onchange remixd "8888"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remix-ide@0.6.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by dexterchan** [comment]
If anyone help, I am considering to help packing the ide into docker.... such that, people does not need to install....
Up to now, my MACOS High Serria failed in the installation. I can only manage to host the app on ubuntu 16.4 on Google GCP.

**Comment by dexterchan** [comment]
I try to branch out and contribute my docker file.... anyone would grant access?

**Comment by yann300** [comment]
please look at https://github.com/ethereum/remix-ide/releases/tag/v0.6.4 
but happy to update or add another one.

> anyone would grant access?

could you fork and you create a PR?

**Comment by yann300** [comment]
thanks for your help btw ;)

**Comment by dexterchan** [comment]
filed a pull request
https://github.com/ethereum/remix-ide/pull/1522
thank you!!!
