### ISSUE TITLE
remix.ethereum.org is down for more than a week

### ISSUE THREAD

**Issue by nourharidy** [ethereum/remix-ide#1499]
http://www.isitdownrightnow.com/remix.ethereum.org.html

**Comment by ndtuan89** [comment]
Same with me.

**Comment by kfichter** [comment]
I managed to temporarily fix this issue by switching to Cloudflare DNS (1.1.1.1).

**Comment by ndtuan89** [comment]
1.1.1.1 is working for me. Thank you @kfichter .

**Comment by maxsam4** [comment]
And it's down for me as well. Cloudflare DNS(was my default) isn't working anymore.

**Comment by yann300** [comment]
that's fixed

**Comment by kot-begemot** [comment]
I am facing this issue now. Has it been reintroduced?

**Comment by sharonsylu** [comment]
Seems to a DNS issue again. 

@kot-begemot:  Is your firewall using Google Public DNS as default? 

https://dns.google.com/query?name=remix.ethereum.org&type=ANY&dnssec=true

"DNSSEC validation failure. Check http://dnsviz.net/d/remix.ethereum.org/dnssec/ and http://dnssec-debugger.verisignlabs.com/remix.ethereum.org for errors"

**Comment by lucassaldanha** [comment]
Still down :(

**Comment by kot-begemot** [comment]
@maxsam4 Posted a solution with hosts file that worked for me

**Comment by lucassaldanha** [comment]
> @maxsam4 Posted a solution with hosts file that worked for me

Yep. The hosts file workaround works fine. Thanks!

Still a bad thing we are having these DNS issues though.
