### ISSUE TITLE
Cannot load compiler version list

### ISSUE THREAD

**Issue by vikas1188** [ethereum/remix-ide#1513]
Hi,
I've [disabled](https://github.com/ethereum/remix-ide/issues/1148) the Adblocker tool from Mozilla Firefox browser. restarted it. but still the compiler version is not getting loaded. 

is there something which I need to do. This issues came right after the v0.7.0 release of remix.

Thanks.

**Comment by yann300** [comment]
that should be back now 
sorry for the delay
