### ISSUE TITLE
Same addresses are getting generated in JavascriptVM environment

### ISSUE THREAD

**Issue by vikas1188** [ethereum/remix-ide#1515]
Hi,
When I select JavascriptVM as the environment, I can create more accounts by clicking on the plus icon just next to Accounts.

After clicking on it, I can see that it gives me two entries of the same address. check the last 4 addresses. you shall be able to see it. 

Thanks.

<img width="398" alt="screen shot 2018-09-13 at 6 03 55 pm" src="https://user-images.githubusercontent.com/7501308/45488565-6b13f600-b77f-11e8-9535-f94bd0f46cde.png">

**Comment by yann300** [comment]
fixed by https://github.com/ethereum/remix-ide/commit/0d60906e94e7da7ccaa08fdeaace2b30d6ee7e13
