### ISSUE TITLE
indicate modified unsaved files

### ISSUE THREAD

**Issue by 0mkara** [ethereum/remix-ide#1516]
Currently if a file is modified but not saved it does not give any indication. Unless a file is modified and saved operations are not performed on that file. Like other editors **remix-ide** should show a `*` sign after modified and unsaved files.

**Comment by yann300** [comment]
Now the current file is auto saved every 5 seconds, so there's no need to put a `*`.
and `ctrl+s` is used to start compiling if autocompile is off..
That said i think that's totally fine to put the editor in a "manual" mode where `*` is shown
