### ISSUE TITLE
[Static Analysis] Display the classification flag in the view

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1529]
from here https://github.com/ethereum/remix/blob/master/remix-analyzer/src/solidity-analyzer/modules/algorithmCategories.js

**Comment by LianaHus** [comment]
@Aniket-Engg

**Comment by Aniket-Engg** [comment]
duplicate of https://github.com/ethereum/remix-ide/issues/2821
Perhaps this can be tracked together with https://github.com/ethereum/remix-ide/issues/2812

**Comment by LianaHus** [comment]
I'm closing this as we have #2821
