### ISSUE TITLE
https only

### ISSUE THREAD

**Issue by fulldecent** [ethereum/remix-ide#1530]
Currently remix is serving through insecure http.

![screen shot 2018-09-19 at 10 39 55 am](https://user-images.githubusercontent.com/382183/45760611-7ee4af80-bbf8-11e8-87d3-2e3739a3aa45.png)

Billions of dollars worth of commerce are going through these systems, please only allow https.

**Comment by kavu** [comment]
Both http://remix.ethereum.org/ and https://remix.ethereum.org/ are available. And, you are right, there is no HSTS headers. But there is a reasonable explanation - on HTTPS version of Remix you would not available to connect to your local node, unless it's also served though HTTPS, which is rare.

**Comment by fulldecent** [comment]
My only recommendation is that the version deployed to http://remix.ethereum.org/  would include a redirect to the https version. It is not necessary (or appropriate) for this redirect to apply for local downloads.
