### ISSUE TITLE
Github import error

### ISSUE THREAD

**Issue by fulldecent** [ethereum/remix-ide#1531]
# Test case

```solidity
pragma solidity ^0.4.25;

import "https://github.com/0xcert/ethereum-erc721/contracts/tokens/NFToken.sol";
```

# Error

> file provider localhost not available while trying to resolve localhost/node_modules/@0xcert/contracts/ethereum-utils/contracts/utils/AddressUtils.sol

![screen shot 2018-09-19 at 10 46 27 am](https://user-images.githubusercontent.com/382183/45760984-54dfbd00-bbf9-11e8-8c43-d8d593a4cb2a.png)

# Documentation

I was expecting this to work because of the documentation at:

https://remix.readthedocs.io/en/latest/tutorial_import.html#importing-from-github

> It is possible to import files directly from github with URLs like `https://github.com/<owner>/<repo>/<path to the file>`.

**Comment by yann300** [comment]
yes we need to clean up that part. update coming soon.
please try `import "github.com/0xcert/ethereum-erc721/contracts/tokens/NFToken.sol";`

**Comment by fulldecent** [comment]
Thank you for the note. Still getting the same error with this suggestion.

![screen shot 2018-09-19 at 12 03 14 pm](https://user-images.githubusercontent.com/382183/45765842-0c79cc80-bc04-11e8-98bf-016264c7fd1c.png)

**Comment by yann300** [comment]
ah i see now.
could you expand the github explorer?
where are supposed to be located these import like `import "@0xcert/ethereum-utils/contracts/math/SafeMath.sol";`
if it's in your local computer you need to run remixd.

**Comment by fulldecent** [comment]
No, no, I'm trying to pull those dependencies from GitHub, not local computer. I recall that this feature worked as-is without remixd previously.

**Comment by fulldecent** [comment]
Ah, ah, I see. I'll get that updated

**Comment by yann300** [comment]
is everything fine? I m closing that one. please reopen if necessary.

**Comment by pjonson2** [comment]
I am getting the following error message. 

**file provider localhost not available while trying to resolve localhost/node_modules/openzeppelin-solidity/contracts/contracts/math/SafeMath.sol**

![screen shot 2018-11-30 at 2 08 17 pm](https://user-images.githubusercontent.com/13080825/49309521-81da0700-f4a9-11e8-954c-00daa5e6715e.png)


Then after importing openzeppelin-solidity/contracts/contracts/math/SafeMath.sol I am getting the following error.

**Unable to import "undefined": Not Found**

![screen shot 2018-11-30 at 2 10 25 pm](https://user-images.githubusercontent.com/13080825/49309542-93bbaa00-f4a9-11e8-9ed6-db46210d94fc.png)



Any help would be greatly appreciated!

**Comment by itstehkman** [comment]
@yann300 I am also having this issue - do you think you can reopen this issue and take a look? 🙏

**Comment by yann300** [comment]
@itstehkman could you ensure remixd has been turned on?

**Comment by fulldecent** [comment]
These recent comments seem unrelated to the original issue, please open a new issue
