### ISSUE TITLE
cleanup after close file

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-ide#1545]
steps to reproduce: close last open file
actual results: context of last file stays
expected results: empty view or some info/tutorial

**Comment by yann300** [comment]
seems it was fixed in a recent PR, could confirm that @LianaHus ?

**Comment by LianaHus** [comment]
this is fixed, but, as discussed, we should cleanup tabs after that. So I'll leave the issue open.

**Comment by LianaHus** [comment]
- display some info on file explorer if there is no file open
- clean warnings and errors
- disable some buttons on tabs

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-ide/pull/1891
