### ISSUE TITLE
"Copy value to clipboard" is hidden by scroll

### ISSUE THREAD

**Issue by un1t** [ethereum/remix-ide#1553]
On "Run" tab, near account, there is "Copy value to clipboard" button. But it is invisible, because it is under a scroll.

I use Ubuntu 16.04.
I tried Chrome and Firefox. This button is invisible in both.

**Comment by yann300** [comment]
could you post a screenshot please?
if you expand the run tab width?

**Comment by un1t** [comment]
here is a screenshot
![selection_358](https://user-images.githubusercontent.com/440376/47011761-26072900-d15c-11e8-98b2-6ae285a8131f.png)

> if you expand the run tab width?
If I expand run tab, it is visible.
