### ISSUE TITLE
✖ Install fail! Error: GET https://registry.npmjs.com/downloadsolc_root response 404 status

### ISSUE THREAD

**Issue by hunshenshi** [ethereum/remix-ide#1554]
when I run `cnpm install`

[downloadsolc_root] ✖ Install fail! Error: GET https://registry.npmjs.com/downloadsolc_root response 404 status
[downloadsolc_root] Error: GET https://registry.npmjs.com/downloadsolc_root response 404 status
[downloadsolc_root]     at get (/home/hadoop/blockchain/ethereum/node-v10.12.0-linux-x64/lib/node_modules/cnpm/node_modules/npminstall/lib/get.js:57:17)
[downloadsolc_root]     at get.next (<anonymous>)
[downloadsolc_root]     at onFulfilled (/home/hadoop/blockchain/ethereum/node-v10.12.0-linux-x64/lib/node_modules/cnpm/node_modules/co/index.js:65:19)
[downloadsolc_root]     at process._tickCallback (internal/process/next_tick.js:68:7)
[downloadsolc_root] npminstall version: 3.12.0
[downloadsolc_root] npminstall args: /home/hadoop/blockchain/ethereum/node-v10.12.0-linux-x64/bin/node /home/hadoop/blockchain/ethereum/node-v10.12.0-linux-x64/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js run downloadsolc_root
ERROR: "downloadsolc_root" exited with 1.
✖ Install fail! Error: Run "sh -c mkdirp build; npm-run-all -ls downloadsolc_root build" error, exit code 1
Error: Run "sh -c mkdirp build; npm-run-all -ls downloadsolc_root build" error, exit code 1
    at ChildProcess.proc.on.code (/home/hadoop/blockchain/ethereum/node-v10.12.0-linux-x64/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npminstall version: 3.12.0
npminstall args: /home/hadoop/blockchain/ethereum/node-v10.12.0-linux-x64/bin/node /home/hadoop/blockchain/ethereum/node-v10.12.0-linux-x64/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/home/hadoop/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org

my env
cnpm@6.0.0 (/home/hadoop/blockchain/ethereum/node-v10.12.0-linux-x64/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.4.1 (/home/hadoop/blockchain/ethereum/node-v10.12.0-linux-x64/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@10.12.0 (/home/hadoop/blockchain/ethereum/node-v10.12.0-linux-x64/bin/node)
npminstall@3.12.0 (/home/hadoop/blockchain/ethereum/node-v10.12.0-linux-x64/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/home/hadoop/blockchain/ethereum/node-v10.12.0-linux-x64 
linux x64 3.13.0-24-generic 
registry=https://registry.npm.taobao.org

**Comment by syslink** [comment]
same problem as hunshenshi mentioned.

**Comment by leeduckgo** [comment]
some problem
