### ISSUE TITLE
ETH sent during deployment goes to library address instead of contract address

### ISSUE THREAD

**Issue by 0xC0DE4C0FFEE** [ethereum/remix-ide#1558]
Using Solidity v0.4.25 and Remix-ide v0.7.3 (JS EVM) 
Browser : Firefox

![image](https://user-images.githubusercontent.com/43116881/47184811-67116000-d34b-11e8-902a-db5ec7caf555.png) 

My contract & library looks like this
```
pragma solidity 0.4.25;
pragma experimental ABIEncoderV2;
library LIBX {
        //....
}

contract ContractX is usingOraclize {
    using LIBX for *;
    LIBX.ZZ internal _zz;

    constructor () public payable {
        //...
    }
    
    //...
}```

**Comment by yann300** [comment]
work around would be to manually deploy the library:
in settings tab, check the first option, start compiling to generate metadata, then use it to provide the library address.
