### ISSUE TITLE
Log events: indexed event parameters not getting correctly displayed/logged

### ISSUE THREAD

**Issue by zmitton** [ethereum/remix-ide#157]
when using the keyword `indexed` for an event, the output on the side panel skips the field and displays a null value for the last element.

Here is some code to emphasize the problem: 

```
contract MyContract {
    event MyWorkingEvent(
        address thing1,
        address thing2,
        address thing3);

    event MyBrokenEvent(
        address indexed thing4,
        address thing5,
        address thing6);

    function logAllTheThings(){
        MyWorkingEvent(0x12, 0x34, 0x56); // works :)
        //output => MyWorkingEvent["0x12","0x34","0x56","0x78"]

        MyBrokenEvent(0x12, 0x34, 0x56); // doesnt work :( 
        //output  => MyBrokenEvent["0x34","0x56","0x78","0x0"]
    }
}
```

**Comment by axic** [comment]
Indexed events in VM mode are not supported yet. This has to be looked at.

Does it work as expected in Web3 mode?

**Comment by zmitton** [comment]
Actually now when I enable metamask, I get `Invalid JSON RPC response: ""` before I even type a thing.

**Comment by yann300** [comment]
closing as this should be fixed by now
