### ISSUE TITLE
remix should support metamask's privacy mode

### ISSUE THREAD

**Issue by BigMurry** [ethereum/remix-ide#1590]
Metamask has shipped the new release which introduced the new feature Privacy Mode based on [EIP-1102] (https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md). And when Privacy Mode is ON, remix should work properly.

some details: MetaMask/metamask-extension#4703

**Comment by yann300** [comment]
fix https://github.com/ethereum/remix/pull/1138

**Comment by snailking** [comment]
Despite the above fix, Remix still doesn't work on my machine with MetaMask Privacy Mode enabled.

**Comment by danfinlay** [comment]
This is not yet fixed because the fix was not yet published. Someone on the Remix team needs to publish their latest version to get the fix out to users:

https://github.com/ethereum/remix/pull/1138

**Comment by bdresser** [comment]
gentle bump! MetaMask is getting several issues & support emails per week about this issue.

**Comment by yann300** [comment]
Thanks for the patience, the fix is going to be deployed shortly , the latest mid may

**Comment by yann300** [comment]
the original issue (supporting `ethereum.enable()`) has been deployed.
