### ISSUE TITLE
Too much recursion error when loading compiler

### ISSUE THREAD

**Issue by justuswilhelm** [ethereum/remix-ide#1591]
I've been hitting this issue in Chrome and Firefox. Steps to reproduce

1. Go to remix.ethereum.org
2. Load a compiler
3. Nothing happens
4. Too much recursion error in JS console

![image](https://user-images.githubusercontent.com/1641042/48108401-5be48c80-e286-11e8-8a6a-4b4720481fce.png)

**Comment by yann300** [comment]
do you have the same behavior with remix-alpha.ethereum.org ?

**Comment by justuswilhelm** [comment]
@yann300 thanks for checking into this. With remix-alpha.ethereum.org I am encountering the same issue. See the attached screenshot 
![image](https://user-images.githubusercontent.com/1641042/48176975-e516c480-e355-11e8-9ce1-d24d52fe3b65.png)

**Comment by uhhhh2** [comment]
When my dependencies are flat (Contract depends on Library), compile and deploy work. When a third level is introduced (Contract depends on Library depends on Library), I get similar errors, even if I try to deploy manually in the correct order. Not sure if it is the same issue.

**Comment by yann300** [comment]
@uhhhh2 could you PM the source code please, i 'll check that ? gitter.im/yann300

**Comment by skfarhat** [comment]
I get the same `Too much recursion error` when trying to load pre-v5 compiler. It works fine on Chrome and Safari, but not on Firefox.

**Comment by PierBusDev** [comment]
Getting the same error recently any time I try to load pre-v5 version. I think this should have an high priority considering it is blocking for anyone who want to develop and compile on those versions.

**Comment by yann300** [comment]
@ekpyron @chriseth @axic weren't the previous version patched?

**Comment by ekpyron** [comment]
The previous versions weren't patched so far - we're now considering releasing "browser stack fix" variants for all past versions, but that requires manually splitting up the rule list function in each one of them, which is quite some work, so nobody has volunteered for it yet :-).

By the way: this is actually an issue of the browsers, since they just randomly lower their maximum javascript stack height between versions - so actually we should file an issue with them instead...

**Comment by ekpyron** [comment]
Do you think it'd be enough to have a patched version of ``0.4.25``? Remix could check whether the browser version is known to have the low stack limit and notify the user that it can only use specific versions because of that...
