### ISSUE TITLE
Plugin API - trigger Remix debugger for a JavaScriptVM txn made by the plugin

### ISSUE THREAD

**Issue by loredanacirstea** [ethereum/remix-ide#1594]
When I was making a transaction through the plugin API (`PluginAPI.call('udapp', 'runTx', [transaction], function(error, result) {})`), it did not show up in the Remix terminal, so I can debug it - am I missing something?

Also, what do you think about adding a plugin API for starting the debugger for a specific transaction hash?

**Comment by yann300** [comment]
that should be already in since a few releases
