### ISSUE TITLE
Wrong uint value displayed in debug panel

### ISSUE THREAD

**Issue by zupino** [ethereum/remix-ide#1599]
The Solidity Locals section in the debug panel seems to display wrong value for uint.
In the screenshot below, debug panel shows `3000000000000000000` as value for `closedTask`, but the actual value is (correctly) 3, in fact the if condition is `true` and `projectStatus` is correctly set to 2.

![image](https://user-images.githubusercontent.com/4855290/48317659-9ab37300-e5f5-11e8-9c1f-8e127d9b6e81.png)

I do not have a test to attach, but if this is an always issue, should be easily reproducible. 

https://ethereum.stackexchange.com/questions/62101/increment-a-uint-variable-results-in-unexpected-value

**Comment by zupino** [comment]
I forgot to mention that there is another unexpected behavior observed in the same use case: the function in the screenshot declares 2 local variables (`totalPayout` and `closedTask`), but the debug panel only shows 1.

**Comment by yann300** [comment]
sorry for the very late answer, I just tried and it work on my side? (with new interface).
I m closing it as it seems fixed. could you post the code and reopen if it isn't?
Thanks ;)
