### ISSUE TITLE
Only select known working major version of Solidity

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#1606]
Remix currently selects the last release from solc-bin.

Going forward with a plan to have more breaking releases, it would make sense for Remix to always select the last release of the major version it is tested with. It can still display other in the dropdown.

For example if Remix uses solc-js 0.4.25, then it should not offer 0.5.0 as the default item in the dropdown.

**Comment by axic** [comment]
One can use the [`semver`](https://www.npmjs.com/package/semver) package to achieve this:

`semver.satisfies(<compiler version>, “^0.4.0”)` returns `true` on a 0.4.x compatible version

Currently remix selects the last entry in the `releases` from `solc-bin/list.json`. It would need to iterate that list in reverse (i.e. 0.5.0 is the first entry) and stop when the `semver.satisfies` returns true.

**Comment by jhokkar** [comment]
@axic Can you please explain how to get the base version against which we will be checking(0.4.0 in above example)?

**Comment by axic** [comment]
The version has to be hardcoded in Remix. It is the version known to be working with Remix.

**Comment by yann300** [comment]
pushed during a refactor https://github.com/ethereum/remix-ide/blob/master/src/app/tabs/compile-tab.js#L68

should be definitely released in March

**Comment by yann300** [comment]
reopening for handling
> I suggest this to be <0.6.0 so that Remix works with all compilers til the next breaking release. The user intentionally can load a newer one, but it won't be loaded by default.

**Comment by axic** [comment]
Implementing https://github.com/ethereum/remix-ide/issues/1606#issuecomment-439048659 would still be nice.

cc @Aniket-Engg @LianaHus

**Comment by LianaHus** [comment]
this is implemented. we have a default version which is usually the last major release.
