### ISSUE TITLE
Deployed Contracts use the wrong type

### ISSUE THREAD

**Issue by wjmelements** [ethereum/remix-ide#1609]
If I deploy two contracts of a different type and then they both confirm, both will be typed as the second contract. Whatever tracks the pending contract deployment tx should also track contract name and ABI instead of assuming the currently selected contract was the one originally deployed.

**Comment by yann300** [comment]
fixed by https://github.com/ethereum/remix-ide/commit/a675156073a6ac554022caa2c207c15565f99157
