### ISSUE TITLE
npm run setupremix

### ISSUE THREAD

**Issue by Mojicode** [ethereum/remix-ide#1610]
when I execute five steps below:

- git clone https://github.com/ethereum/remix-ide.git
- cd remix-ide
- npm install
- npm run setupremix  
- npm start

It print error below:
**Error: Cannot find module 'remix-lib' 
 Error: Cannot find module 'remix-tests' 
 Error: Cannot find module 'remix-solidity'**

and I find out remix-lib doesn't exist indeed, why?

**Comment by Mojicode** [comment]
![menu saveimg savepath20181119164546](https://user-images.githubusercontent.com/30165217/48695743-ee881280-ec1a-11e8-93c7-6b54eb2eedb9.jpg)
I find @yann300 remove "npm run pullremix", why?

**Comment by yann300** [comment]
because we change the location of remix repositories (when you do `npm run setuplinkremix` for instance)

remix-ide and remix repositories should be siblings (I will update readme).
are you devloping on remix and remix-ide? (these scripts are only relevant if you plan to plan to update the code

**Comment by Mojicode** [comment]
> because we change the location of remix repositories (when you do `npm run setuplinkremix` for instance)
> 
> remix-ide and remix repositories should be siblings (I will update readme).
> are you devloping on remix and remix-ide? (these scripts are only relevant if you plan to plan to update the code

thank you, I have known why and modified the package.json scrip. Please updating readme in time.
