### ISSUE TITLE
compiler is loading

### ISSUE THREAD

**Issue by Mojicode** [ethereum/remix-ide#1611]
when I open remix-ide with browser, the "start to compile" begin keeping rotating, and never stop.
This remix-ide is from git, and start it by:

- git clone https://github.com/ethereum/remix-ide.git
- git clone https://github.com/ethereum/remix.git 
- cd remix-ide
- npm install
- npm run setupremix 
- npm start
![compilerisloading](https://user-images.githubusercontent.com/30165217/48747409-3ad06280-ecae-11e8-9811-c6ffc3f87cb3.jpg)

**Comment by yann300** [comment]
0.5 support has been added, issue should be fixed new

**Comment by Mojicode** [comment]
> 0.5 support has been added, issue should be fixed new

Uncaught abort("NO_DYNAMIC_EXECUTION was set, cannot eval - ccall/cwrap are not functional") at Error
![0-5-0compilerloading](https://user-images.githubusercontent.com/30165217/48879309-1ad3a700-ee46-11e8-9294-eaf22f06aa65.jpg)
