### ISSUE TITLE
Upgrade to ethereumjs-vm 2.5.0 for Constantinople

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#1620]
The VM has a new API, it is possible to specify a hard fork: https://github.com/ethereumjs/ethereumjs-vm/blob/master/docs/index.md#vm

It would be nice to expose this option on Remix.

cc @holgerd77

**Comment by holgerd77** [comment]
Yes, I am available for assistance and some guidance if needed.

**Comment by holgerd77** [comment]
Think the easiest way for integration would be to just add two entries for environment, so in:

``Run`` -> ``Environment``:

- ``JavaScript VM (Byzantium)``
- ``JavaScript VM (Constantinople)``

Should be a fairly local change (probably, hehe 😄).

**Comment by cdetrio** [comment]
Looks like there was some progress in https://github.com/ethereum/remix-ide/pull/1650

**Comment by yann300** [comment]
@axic we are using 2.6.0 by default now, but the switch isn't there

**Comment by cdetrio** [comment]
I get this warning:

```
browser/ballot.sol:8:20: Warning: The "shl" instruction is only available for Constantinople-compatible VMs. You are currently compiling for "byzantium", where it will be interpreted as an invalid instruction.
```

And it doesn't seem to work.

**Comment by axic** [comment]
The warning is there because Remix still sets `evmVersion` to byzantium for Solidity.

**Comment by yann300** [comment]
for the 0.8 release, we will:
 - display the fork name in the compile tab (depending of the compiler version)
 - display the fork name in the run tab

**Comment by axic** [comment]
Wasn't this done? :)

**Comment by LianaHus** [comment]
yes. the evmversion is Istanbul now and it is displayed in solidity plugin but not "run tab" 
Should we evm version also there @yann300 ?

**Comment by LianaHus** [comment]
@yann300 ?
