### ISSUE TITLE
[ERR] Unexpected Error servicesList[name][fn] is not a function

### ISSUE THREAD

**Issue by GravelCoin** [ethereum/remix-ide#1621]
Hi everybody!

Today, when I was trying to access a local folder from Remix IDE using remixd `remixd -s local folder` I found out that the contracts were not displayed on the menu, even the Connect Localhost was green.

Then I got this: "**[ERR] Unexpected Error servicesList[name][fn] is not a function**".

What can I do to solve this?

Thanks in Advance!!!
Details: I could access the folder with the contracts previously, and yesterday I was installing Tensorflow. Maybe this has an impact on the error.

**Comment by yann300** [comment]
please try updating remixd to latest version, which is ` 0.1.8-alpha.6 `
`npm install -g remixd`

**Comment by GravelCoin** [comment]
With version **0.1.8-alpha.4** remixd worked, then the chain icon on Remix IDE becomes **green** but the link "Localhost" nor the contracts are displayed.

**Comment by yann300** [comment]
the latest is ´0.1.8-alpha.6´ could you update to this one?

**Comment by GravelCoin** [comment]
Yes, I know 0.1.8-alpha.6 is the latest. It's not possible to install this version.

With .4 it's possible to install but the contracts don't show up.

**Comment by yann300** [comment]
>  It's not possible to install this version.

why?
