### ISSUE TITLE
problem while `npm start` 

### ISSUE THREAD

**Issue by JacksonTom** [ethereum/remix-ide#1622]
[remixd  ] [WARN] You may now only use IDE at http://127.0.0.1:8080 to connect to that instance
[remixd  ] [WARN] Any application that runs on your computer can potentially read from and write to all files in the directory.
[remixd  ] [WARN] Symbolinc links are not forwarded to Remix IDE
[remixd  ] 
[remixd  ] [WARN] Symbolic link modification not allowed : ./contracts | /opt/remix-ide/contracts
[remixd  ] Sun Nov 25 2018 13:37:05 GMT+0800 (China Standard Time) Remixd is listening on 127.0.0.1:65520
[watch   ] 26355434 bytes written to build/app.js (13.07 seconds) at 1:37:18 PM
[watch   ] { [Error: ENOENT: no such file or directory, open 'build/app.js']
[watch   ]   errno: -2,
[watch   ]   code: 'ENOENT',
[watch   ]   syscall: 'open',
[watch   ]   path: 'build/app.js' }

**Comment by JacksonTom** [comment]
so where is build/app.js?

**Comment by yann300** [comment]
could you run `npm run build` first?
