### ISSUE TITLE
Correction in error message.

### ISSUE THREAD

**Issue by gulshanvasnani** [ethereum/remix-ide#1624]
Consider following two contracts :-
1. Contract D which inherits contract E.

```pragma solidity ^0.4.23;
import "./E.sol";

contract D is E {
    
    // E's constructor is not called.
    constructor()
    public
   {
        
    }

    function add(uint a,uint b) returns (uint) {
        return (a + b);    
    }
}
```

2. Contract E :-

```pragma solidity ^0.4.23;

contract E {
    uint a;

    constructor(uint _a)
    public
   {
        a = _a;
    }
}
```

When we deploy contract D, remix throws **This contract does not implement all functions and thus cannot be created.** As we can see that there are no methods in contract E whose implementation is needed. The reason for error is we have to call constructor of contract E using constructor of contract D as follows :- 
``` 
     constructor(uint a)
       public
       E(a)
    {
        
    }
```

Truffle throws below error which seems to be a correct message :-
```Error: D error: contract binary not set. Can't deploy new instance.
This contract may be abstract, not implement an abstract parent's methods completely
or not invoke an inherited contract's constructor correctly.
```

**Comment by yann300** [comment]
thanks for the feed back, the message should be more accurate
