### ISSUE TITLE
Use NatSpec in the example contract

### ISSUE THREAD

**Issue by corollari** [ethereum/remix-ide#1632]
Before the example contract included in remix was updated in #1612 it used to be full natspec'd. 
That PR removed the natspec lines, should that be interpreted as a decision from the maintainers to not use natspec in the example contract moving forward or you simply didn't have time to add the NatSpec comments?
If it's the latter, I could submit a PR adding them (open to changing them after discussion).

**Comment by yann300** [comment]
you mean the Ballot.sol? The plan is to move to this implementation https://solidity.readthedocs.io/en/v0.4.24/solidity-by-example.html#voting? that involve updating the tests too.

**Comment by corollari** [comment]
Okay, I'll ask upstream about using NatSpec on this example contract then.
