### ISSUE TITLE
How to input a nested structure parameter in remix?

### ISSUE THREAD

**Issue by maoqianqian123456** [ethereum/remix-ide#1643]
This is my code.I want use function which name is init2,So anybody know how to input a nested structure parameter?thanks!!
pragma solidity ^0.5.1;
pragma experimental ABIEncoderV2;

contract simple {
    struct Teacher{
        int age1;
    }

  
    
  struct Student{
        int age2;
        Teacher teacher;
  }

function init( Teacher memory n)   public  returns (Student memory s, Teacher memory q){
 
    return (s,q);
  }
  
function init2(Student memory m)   public  returns (Student memory s){
  
  Teacher memory q1= Teacher(
    20
     );
 Student memory s1 =Student(
    18,
    q1
    );

    return s1;
  }
    

function get()   public  returns (Student memory e){
     Teacher memory q = Teacher(
    20
);
 Student memory s =Student(
    18,
    q
);
  
    return s;
  }
}

**Comment by LianaHus** [comment]
https://remix-ide.readthedocs.io/en/latest/udapp.html#example-of-passing-nested-struct-to-a-function
