### ISSUE TITLE
Please help. Why did the installation fail

### ISSUE THREAD

**Issue by BaiMingxu** [ethereum/remix-ide#1645]
<img width="1244" alt="2018-12-24 12 40 39" src="https://user-images.githubusercontent.com/22886455/50391025-96907e80-0779-11e9-9147-687f8f608ae3.png">

**Comment by yann300** [comment]
I would suggest updating node to latest version

**Comment by LianaHus** [comment]
@BaiMingxu  I'm closing the issue. If you still have problems you are free to ask for help in our [gitter channel ](https://gitter.im/ethereum/remix).
