### ISSUE TITLE
why click 'localhost connection' from ide, get rejected ( 403 response code) ?

### ISSUE THREAD

**Issue by code-brewer** [ethereum/remix-ide#1651]
The brower console print error:
app.js:263614 WebSocket connection to 'ws://localhost:65520/' failed: Error during WebSocket handshake: Unexpected response code: 403

and the in the terminall where innvoke remix-ide command print message: 
Wed Jan 02 2019 23:00:27 GMT+0800 (CST) Connection from origin http://localhost:8080 rejected.

If i open ide via 127.0.0.1:8080 URL, the same result: 
Wed Jan 02 2019 23:10:43 GMT+0800 (CST) Connection from origin http://127.0.0.1:8080 rejected.

**Comment by yann300** [comment]
what is the value of the `--remix-ide` option?

**Comment by code-brewer** [comment]
I use the version installed by 'npm install -g remix-ide' (i think it build-in with remixd, and no need to start remixd seperately).

then, i just invoke by 'remix-ide'  without any options.

Like this: 
➜  abigen_test remix-ide
Starting Remix IDE at http://localhost:8080 and sharing /xxx/abigen_test
Wed Jan 02 2019 23:17:00 GMT+0800 (CST) Remixd is listening on 127.0.0.1:65520

**Comment by yann300** [comment]
please try installing `remixd` instead , i will take a  closer look

**Comment by code-brewer** [comment]
Thx. I have try stand-alone remixd combine with online https://remix.ethereum.org/,  it work.

**Comment by yann300** [comment]
a fix has been published for remix-ide package, should be ok now.

**Comment by code-brewer** [comment]
@yann300  can you point out which merge or commit fix this issue? I am curious about how it was fixing.

**Comment by yann300** [comment]
npm install remix-ide should get the right version now.
commit https://github.com/ethereum/remix-ide/commit/8f706e485fb43e9a44dfe13e6909e32bf44dc51a
the URL has to be `localhost:8080` for now, that should set in an option I think. would you like to push a PR for adding that?
