### ISSUE TITLE
Internal exception in StandardCompiler

### ISSUE THREAD

**Issue by dgrmunch** [ethereum/remix-ide#1659]
I am having problems with my new solidity contracts in Remix.
For example, I get:

"Internal exception in StandardCompiler::compileInternal: /root/project/libevmasm/ExpressionClasses.cpp(187): Throw in function ExpressionClasses::Id dev::eth::ExpressionClasses::tryToSimplify(const dev::eth::ExpressionClasses::Expression &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::OptimizerException>
std::exception::what: Rule list not properly initialized.
[dev::tag_comment*] = Rule list not properly initialized."

for this simple contract:

pragma solidity ^0.5.0;

/* @title Lockable */
contract Lockable  {
  
  // State
  bool public isLocked;
 
  
}

**Comment by codydjango** [comment]
Anything I can do to help with this?

**Comment by axic** [comment]
This will hopefully work again with 0.5.3 next week.

**Comment by xerg0n** [comment]
Problem persists for me on Firefox Quantum 65.0 (64-bit)
OS is 4.19.20-1-MANJARO

**Comment by holiman** [comment]
I'm also getting this error
```
Internal exception in StandardCompiler::compileInternal: /root/project/libevmasm/ExpressionClasses.cpp(187): Throw in function ExpressionClasses::Id dev::eth::ExpressionClasses::tryToSimplify(const dev::eth::ExpressionClasses::Expression &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::OptimizerException>
std::exception::what: Rule list not properly initialized.
[dev::tag_comment*] = Rule list not properly initialized.
```
Firefox Quantum, 65.0, on Fedora

**Comment by holiman** [comment]
I get the error before `0.5.3`, no error with `0.5.3` and a few more versions, but after and including `0.5.5-nightly.2019.3.5+commit.c283f6d8.Emscripten.clang` produces the error

**Comment by Seenivasanseeni** [comment]
I am still facing this issue v0.7.7 FYI: `https://remix.ethereum.org/#appVersion=0.7.7&version=soljson-v0.5.1+commit.c8a2cb62.js`
