### ISSUE TITLE
Remix tries to encode Strings a JSON.

### ISSUE THREAD

**Issue by CamiloTD** [ethereum/remix-ide#1664]
When i try to send a string with some special characters (like comma), it tries to parse it, i cant test with it.

![image](https://user-images.githubusercontent.com/12549059/51153537-9cd8be80-183e-11e9-849b-1dc0680242d6.png)

**Comment by yann300** [comment]
you try here to encode an bytes array as string? why not having directly a byte array as parameter?
could you try `"['0x62', '0x62', '0x62']"`

**Comment by CamiloTD** [comment]
Hi yan300, i think the issue is in how the Remix is managing the data, when i try to send a string that contains some json special characters, it doesn't let me encode them.

im trying to upload an arbitrary html component
This Text: https://hastebin.com/xirihuzono.xml

its correctly quoted, and the " are scaped with \" but, it still tries to encode it as JSON
![image](https://user-images.githubusercontent.com/12549059/51200453-7f9c0280-18c7-11e9-929c-6c3875c8c8ec.png)

**Comment by LianaHus** [comment]
this should be fixed now, please reopen if it persists
