### ISSUE TITLE
How to change remix-ide's addr to public IP

### ISSUE THREAD

**Issue by bishaoqing** [ethereum/remix-ide#1668]
I want to set up a remix-ide server for my group members, it means that I want remix-ide run with a public IP instead of localhost, but i find there are lots of  hard-code just like "http:localhost:8080" everywhere, what should i do? change them all?

**Comment by yann300** [comment]
There's an issue for making this optional. in the meantime, you could checkout the latest release in github

https://github.com/ethereum/remix-ide/commit/18dffc7ab432cf05a244cce56d042566139deed1
in package.json, update `"serve": "execr --silent http-server .",` to serve on another port
then `npm install`
and `npm run build && npm run serve`

but if you want to a have a public IP for this, you could just have port redirection in your router. You don't necessarily need to change `package.json`
