### ISSUE TITLE
Embed the Remix IDE into a static website

### ISSUE THREAD

**Issue by omrllm** [ethereum/remix-ide#1674]
Hi!

Is it possible to embed the Remix IDE into a static website? What if the website is dynamic.. still not possible?

**Comment by yann300** [comment]
easy way it to put it in an iframe.
you could also rebuild it using a different `index.js`
https://github.com/ethereum/remix-ide/blob/master/src/index.js

**Comment by omrllm** [comment]
Yes, but I want just the place where I type and the compiler errors and output.

Something like JSBin.

**Comment by yann300** [comment]
in that case, you could use the https://github.com/ethereum/remix/tree/master/remix-solidity or directly sol-js for compiling and displaying output, you'll need in that case to write the UI.
We are currently updating the UX of remix IDE. It will allow selecting which module you want to be loaded (in your case, solidity compiler and file editor), available in a few weeks

**Comment by omrllm** [comment]
Alright!

In the meantime I'm gonna use something else. Is there anyway to get notified when you will allow module selection?
