### ISSUE TITLE
Integrating a linter

### ISSUE THREAD

**Issue by duaraghav8** [ethereum/remix-ide#168]
Hi,
I recently published my little project [Solium](https://github.com/duaraghav8/Solium) - A command-line based linter for Solidity with hot loading.

@Arachnid suggested that I make it browser compatible and make a PR to integrate it with browser-solidity. I think its a great idea.
Would you be interested in it?

Please feel free to check out the project and let me know-
`npm install -g solium`

**Comment by axic** [comment]
As mentioned on the channel, the rules should match http://solidity.readthedocs.io/en/latest/style-guide.html. Or at least the integrated version should have those exact rules preloaded and nothing else.

**Comment by duaraghav8** [comment]
@axic Of course. I'm already working on it, will notify once its fully compliant

**Comment by axic** [comment]
I was actually looking for a tool a while ago, which would be similar to JavasScript's `standard` or `semistandard` for Solidity. So no linting, just warning for mistakes.

Is that possible with your tool? I seems like it can lint only.

It would be very useful having these style errors shown as *style warnings* with file and line number.

**Comment by duaraghav8** [comment]
I believe it doesn't strictly fit your description right now.

But I plan to make this linter flexible like ```eslint```. So with a single shareable configuration file, you can disable the linting and turn it into a style checker. Something like [shareable configs](http://eslint.org/docs/developer-guide/shareable-configs)

This will be possible in the near future.
