### ISSUE TITLE
Allow recorder .json file to control timestamps of transactions

### ISSUE THREAD

**Issue by LeviBarnes** [ethereum/remix-ide#1680]
I'd like to modify the .json file created by the recorder to model the passing of time between calls. This is useful, for example, for testing a contract that computes time-based interest on a loan. 

But, when I play the .json file, the timestamps on the Txs are the time they were played by the recorder not those given in the .json.

Could we allow the .json file to specify the timestamps for the Txs as well?

**Comment by LeviBarnes** [comment]
I'm glad to take a stab at fixing this, but is it going to do any damage to anyone else's use model?

**Comment by LianaHus** [comment]
Hi @LeviBarnes . thanks for your proposal. Could you please provide more details on how are you going to implement this. It should not break the current behavior.

**Comment by LeviBarnes** [comment]
Here's a test case.

It's a one-to-one loan contract which charges interest. For testing purposes, it charges 134 wei per minute for each 1,000,000 wei outstanding. 

The lender, 0xca.., pays 1 ether. The borrower borrows and gets paid 1 ether by the contract. After two minutes, the borrower repays 1 ether via the fallback function. Because of interest, the borrower still owes 1.000268 ether. He repays the rest and the outstanding balance should be zero.

But when you replay from the .json file, the constructor, borrow and fallback calls happen within a few seconds of one another, so no interest is charged. Testing anything involving `now` with a .json is probably impossible at present.

I'm still getting acquainted with remix. Do you think it's possible to pass the timestamps from the .json file to the backend so that calls to `now` reflect the timestamps in the replay .json?

[interest_test.json.txt](https://github.com/ethereum/remix-ide/files/2784536/interest_test.json.txt)
[Loan.sol.txt](https://github.com/ethereum/remix-ide/files/2784537/Loan.sol.txt)

**Comment by LeviBarnes** [comment]
@LianaHus, what, then, do we think of this? IMO it's important to be able to use the recorder to replay contracts that use `now`. To do so, we'll need a change to remix-ide and one to remix. 

The change to remix can be made such that a timestamp passed to `txRunner.rawRun` will override the default behavior, which is to just use `Date.now()` as the timestamp. Without a passed timestamp, behavior reverts to default. I feel like this is safe. 

In remix-ide, we need a change to the recorder to send the timestamp to the UniversalDapp.runTransaction. udapp can do the same as the routines in remix. Use the timestamp if it's given. Otherwise, revert to using `Date.now()`.

My only hesitation is that it only makes sense to pass the timestamp when running with the VM. When running on an external node, we'll revert to passing `Date.now()` no matter what is passed to `txRunner.rawRun`. So the downside is that, with applications that involve references to `now`, you'll potentially see differences between the VM and your web3 node, etc. when replaying from the recorder.

I would prefer to give users (including me!) a way to test contracts involving `now` with the recorder. But I'm interested in your opinion. (Yours too, @yann300.)
