### ISSUE TITLE
Address to clipboard does not work on Chrome v72.0.3626.96

### ISSUE THREAD

**Issue by tadejrola** [ethereum/remix-ide#1685]
After updating Google Chrome to its latest version [72.0.3626.96] copying address value to clipboard, by pressing "Copy value to clipboard" button, does not work.

Steps to reproduce:

1. Use Windows (did not try on any other OS),
2. Use Google Chrome version 72.0.3626.96,
3. Go to https://remix.ethereum.org/ and tab 'Run'
4. Press 'Copy to clipboard' button in the 'Address' section
5. Try to paste the address. It is not there.

Works fine with any of previous Google Chrome versions.

**Comment by GrandSchtroumpf** [comment]
Yes I can reproduce it with 72.0.3626.96 on Windows 10. Didn't get this issue with version 71.
I'll check the changes of 72 to understand what's wrong.

**Comment by LianaHus** [comment]
managed to update to 72.x
Can reproduce it on linux as well. thanks for the report.

**Comment by enginguray** [comment]
> managed to update to 72.x
> Can reproduce it on linux as well. thanks for the report.

Same issue with me. What was your solution for the case?

**Comment by hapsody** [comment]
same problem here on chrome version 72.0.3626.109(official build) (64bit)

**Comment by juarezweiss** [comment]
Same problem here, just updated Chrome yesterday.

**Comment by Skyge** [comment]
Same problem here, just updated Chrome. 72.0.3626.109(official build) (64bit)

**Comment by maxsam4** [comment]
Fixed it in https://github.com/feross/clipboard-copy/pull/31

I'd recommend waiting a couple of days for upstream to merge fix/implement their own fix and updating the dependency version then. Alternatively, the fix(or the whole script) can be picked up and kept as a part of this repo.

**Comment by taylorjdawson** [comment]
Awesome, thanks @maxsam4!
