### ISSUE TITLE
Copy ABI and Bytecode buttons not working on Google Chrome

### ISSUE THREAD

**Issue by sindelio** [ethereum/remix-ide#1686]
The copy to clipboard buttons are not working properly on Google Chrome. When I try to copy the ABI or Bytecode, they don't actually copy those, so CTRL+V does not work. 
Works on Firefox tho.

Environment:
OS: Ubuntu 18.04
Browser: Chrome Version 72.0.3626.96 (Official Build) (64-bit)

**Comment by LianaHus** [comment]
I assume this is the same issue https://github.com/ethereum/remix-ide/issues/1685

**Comment by superman285** [comment]
I face the same problem, need help~

**Comment by LingTian** [comment]
Reproduce in following environment
Environment:
OS: MacOS 10.13.6 
Browser: Version 72.0.3626.109 
Also not working~

**Comment by taylorjdawson** [comment]
Can confirm not working for me either.

**Comment by maxsam4** [comment]
I think it might be best to close duplicate issues.

**Comment by taylorjdawson** [comment]
@maxsam4 Awesome, thanks!
