### ISSUE TITLE
UX feedbacks

### ISSUE THREAD

**Issue by GrandSchtroumpf** [ethereum/remix-ide#1695]
_Feedbacks 14 / 02 / 2019_
**User**: Developer web. Some experience with Remix.
**Feeling** : "Lost", "Confuse"
**Requests** : 
- [x] Add a header on top of each module.
- [x] Names of the modules should be more explicite.
- [x] Icons should be more explicite.
~~- [ ] Add colors theme for activated / deactivated modules.~~
- [x] Having a BIG "quick start" on the homepage page.

**Observations**: 
He thought the "+" to make the size of the font bigger was to create a file. he didn't understand because it doesn't apply on "homepage". Then he was surprised by a contract size 64px when he created a new file for real.

**Comment by yann300** [comment]
thanks for that!
for `* Add a header on top of each module.` 
you mean in the swap panel right? having a header title where we would display the current displayed module / plugin ?

**Comment by yann300** [comment]
`Then he was surprised by a contract size 64px` ? could you explain more?

**Comment by yann300** [comment]
I find all these comments very relevant.
shall you implement all these? 
@ryestew @LianaHus @GrandSchtroumpf 

beside that I am also a bit concerned that at the moment (in remix.ethereum.org) most of the users 80% of the time use the compile and run tab, and it is fairly easy to switch between them.
In the new interface it should be as easy as in the old one to have the flow : I compile / I run / I compile again / I run / (loop) / ...

**Comment by GrandSchtroumpf** [comment]
> you mean in the swap panel right?

He means a header at the top of the swap panel. Like "File Manager" for example or "Compiler".

> `Then he was surprised by a contract size 64px` ? could you explain more?

He clicked several times on the "+" button that makes the font-size bigger, but nothing changed on the "homepage". Then he created a new file, and the size of the font in the editor was 64px. So he was confused and thought it was the default size. I had to explained that was because he clicked on the "+" button before.

> In the new interface it should be as easy as in the old one to have the flow

I would recommend to have the compilation component between the editor and the terminal. Like that the dev can "edit code" <-> "compile" <-> "deploy" on the same view.

> shall we implement all these?

In this kind of tests it's better to have about 5 relevant samples before taking any actions based on the tests.

**Comment by GrandSchtroumpf** [comment]
_Feedbacks 18 / 02 / 2019_
**User**: Beginner web developer. Used Remix 4-5 times.
**Feeling** : "Lost", "not guided"
**Requests** :
- [ ] Having a "Getting Started"
- [ ] Compiler and Run Tx should be by default.
- [ ] Solidity module should be called "Solidity Compiler" and "Run Transaction" should be call "Deploy Contract" bacause this is what people look for it first.
- [ ] The sidebar should be open by default.
- [ ] The compiler should be below the editor.
**Observation** :
Used the "+" button for font-size to creating a new file. "Maybe because sidebar wasn't open" he said. I had to explain the concept of modules because he didn't understand where was the compiler.

**Comment by 0mkara** [comment]
`Run Transaction` or `Deploy Contract` should not be default action as we need to put `arguments` and change gas supply before deploying contracts.

**Comment by yann300** [comment]
_Feedbacks 26 / 03 / 2019_
**User**: Intermediate Web developer . Used twice a month.
**Feeling** : "Need to refocus"

**Requests** :
- [ ] Homepage to much information
- [ ] Better hierarchy in the home page (main focus is not highlighted. e.g only 2 buttons: "solidity" and "vyper"
- [ ] Do not show the terminal at first load
- [ ] Open a workspace should give user feedback (e.g open swap panel)
- [ ] Make it easier to open to file explorer / editor (perhaps show the file explorer by default)
- [ ] Headers for tabs are not readable (text is orange)
- [ ] Make it more obvious to click on compiler for compiling (he was on the run tab and did know how to actually compile)
- [ ] Change the icon for run tab (it looks like it would start to compile)
- [ ] In Runtab the `i` turns red when there is no compilation result (it should rather be orange)
- [ ] Universal dapp in the run tab (button to call contracts) are not readable, we should improve the contrast.
- [ ] More precise workspace selection (beginner, advanced, solidity, vyper, ...)

**Observation** :
- [ ] not easy access to the code editor (perhaps should display the file explorer by default)
- [ ] better contrast for the vertical icon list
- [ ] if homepage does not contains plugins list (like pipeline, solium or other), not sure how users will find them.

**Comment by yann300** [comment]
Meeting 03 / 04

 - [ ] icons more explicit  solidity, run icon, test icon. Instead of having an icon, if we don't find the right one - e.g solidity, we could perhaps use the first char of the module name ("S" for solidity)

 - [ ] Move to font awesome 5 https://github.com/ethereum/remix-ide/issues/1799

 - [ ] Ctrl +/- will increase the font-size of the editor only if it has focus @LianaHus 

 - [ ] the min width of the swap panel should be decreased.

 - [ ] terminal at first load . make the close/open icon more prominent.

 - [ ] when a workspace compiler is loaded, focus the swap panel to the corresponding compiler

 - [ ] Make it more obvious to click on compiler for compiling (he was on the run tab and did know how to actually compile). solution: `no compiled contract` should be in dropdown list

 - [ ] link to documentation in each header (i in the header)

**Comment by LianaHus** [comment]
_Feedbacks 05 / 04 / 2019_
**User**: Core developer.
**Feeling** : "curious, feels as easy/familiar, as the old one"

**Requests** :
- [ ] Homepage: Workspace title is confusing, looks clickable
- [ ] Homepage: Less text on the right. maybe some icons instead, but at the same time he said start is ok.
- [ ] Editor: was confused when tried to zoom in in editor with mouse
- [ ] Editor(tabs): was expecting mouse pointer on tab hover
- [ ] Homepage: was expecting feedback on viper activation from home. maybe open viper
- [ ] Homepage: Create new file should activate it
- [ ] Compiler: compilation details is not well organized, too long. too much info at the same time.
- [ ] IconPanel: was difficult to find Deploy. maybe rename Run transaction to Deploy and Run tx
- [ ] Terminal: menu should have different color or top border
- [ ] Run tab: text is not different enough from btn bg-color
- [ ] Debug: a strange color of selection when there is no source/scope
- [ ] Debug: check the fork
- [ ] Icon:
**Issues**
- [ ] delete tab from FE doesn't delete from tab (same issue is for rename

**Observation** :

**Comment by LianaHus** [comment]
_Feedbacks 05 / 04 / 2019_
**User**: solidity developer. Had already experience with old remix
**Feeling** : "nice, likes Plugin manager, likes remixd, likes unit tests, likes tx recording"

**Requests** :
- [x] Homepage: all fin, spend 1.5 sec to find solidity and click
- [x] Homepage: couldn't find it the second time. maybe icon on a tab will help.  _had to refresh_
- [x] Homepage: import from gist. file or folder? why is not working with project path? Maybe more info?
- [x]  Icon panel: couldn't understand where are all icons he had after he clicked on solidity workspace and then refreshed the page. they're gone.
- [x] Couldn't find Import from gist. checked FE
- [x] Ace editor. ctrl-C is not case sensitive, annoying
- [x] Debug Panel: blog N, tx N.. are those obligatory fields? he came from terminal. should be either disabled(for calls) or with switch
- [x] Debug Panel: the color of selection in the command list is very bad(bg-warning) couldn't read.
- [x]  Unit tests: Nice! couldn't make it work https://gist.github.com/135b395fc1a8c718177daa01abfb5b5a.
- [x]  remixd: tried remixd. Connection was rejected from remix-ide 
- [x]  Compile tab: after some time was not responding.  _had to refresh_

**Issues**
_to be added_

**Observation** :

**Comment by yann300** [comment]
closing ;)
