### ISSUE TITLE
Remix ide running throws console error

### ISSUE THREAD

**Issue by anistark** [ethereum/remix-ide#1699]
Installed dependencies with `npm install` and ran the project with `npm start`.

The webpage at `http://localhost:8080/` doesn't load completely and throws the following error on browser console:

```
Error: /Users/Anirudha/Documents/blockchain/ethereum/remix-ide/src/app/ui/renderer.js: multiple root elements must be wrapped in an enclosing tag while parsing file: /Users/Anirudha/Documents/blockchain/ethereum/remix-ide/src/app/ui/renderer.js
```

Anybody else facing this or fixed it ?

**Comment by yann300** [comment]
fix https://github.com/ethereum/remix-ide/pull/1704
that is due to an update in one of our dependencies.
