### ISSUE TITLE
Google Public DNS isn't validating

### ISSUE THREAD

**Issue by sharonsylu** [ethereum/remix-ide#1703]
Seems to a DNS issue again. 

Our firewall is set Google Public DNS as default by our administrator.  We can't access remix.ethereum.org. Please update!

https://dns.google.com/query?name=remix.ethereum.org&type=ANY&dnssec=true

"DNSSEC validation failure. Check http://dnsviz.net/d/remix.ethereum.org/dnssec/ and http://dnssec-debugger.verisignlabs.com/remix.ethereum.org for errors"

_Originally posted by @sharonsylu in https://github.com/ethereum/remix-ide/issues/1499#issuecomment-465393123_

**Comment by LianaHus** [comment]
@JeremiGendron

**Comment by LianaHus** [comment]
@jpitts

**Comment by mettinger** [comment]
I'm not a networking guy so this comment may be naive and irrelevant but when this issue first started happening to me I switched to Cloudfare DNS at 1.1.1.1 and it didn't fix the problem.
