### ISSUE TITLE
swap_it branch bug list

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1705]
- [x] When clicking on `Run Tests` under `Unit Testing` I've got `self.compileTab.importFileCb is not a function`

 - [x] When using `Vyper` the solidity compiler tries to compile and fails.

 - [x] Pipeline should open on activation (not current behavior), but vyper should not (current behavior)

 -  ~~[ ] When `ethdoc` is activated, an empty iframe pop at the bottom of the page. Maybe it should be `display: none` by default.~~

 - ~~[ ] When runTab becomes active, it doesn't check if there were a contract already compiled.~~ #1929

**Comment by GrandSchtroumpf** [comment]
- [ ] When opening a new plugin the height of the iframe shoud be 100% of the swap panel

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-ide/issues/1740
