### ISSUE TITLE
Swap_it UI notes

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-ide#1740]
1. resize swap panel
2. Opposite color for icons on panel (.fa {color : red;}?)
3. show description instead of a name as a tooltip for modules/plugins
4. Capital letter for DispleyName modules
4. row items of plugins should be thinner
![screenshot from 2019-03-05 10-09-41](https://user-images.githubusercontent.com/9685356/53793788-d79dcf80-3f2e-11e9-8549-561bdefd60c1.png)
5. what does this Home? doesn't work for me :( do we need this Title?(Home)
6. match Ace editor colors with the global theme(Bootstrap)

**Comment by yann300** [comment]
![20190321_111229](https://user-images.githubusercontent.com/6940742/54746869-99124100-4bcd-11e9-9f5c-c07842e33be8.jpg)

**Comment by yann300** [comment]
@ryestew  ^

**Comment by ryestew** [comment]
I think we need less class specifications - In this screen shot - I took out the contrasting background color for the header of the swap_panel and I took out all text & bg definitions for inactive tabs and I had the active tab be primary - but the text not defined.

<img width="896" alt="image" src="https://user-images.githubusercontent.com/6050001/55066603-6d380500-507e-11e9-91fa-3bef4fb3acb3.png">

**Comment by yann300** [comment]
let's close it, everything is handled
