### ISSUE TITLE
Status API

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1755]
related issue ethereum/remix-plugin#32

this API should perhaps be included in the `icon-list`, that would be used by plugin for updating their status

**Comment by yann300** [comment]
we should define here which information can be passed to the status API.
here's a rough proposal:

`setStatus({ title, text, cssclass, type, color })` (the `from` is passed as part of the current request)

`cssclass` is required to be a font awesome class (optional)
`text` describe long version of the status (optional)
`title` describe the status (required)
`type` info / warning / error / question / require action (required)
`color` hex color (override `type`)

@GrandSchtroumpf @LianaHus @GrandSchtroumpf

**Comment by GrandSchtroumpf** [comment]
Where should be used this `setStatus()` and where does the object you pass in parameter come from ?

**Comment by yann300** [comment]
`setStatus` should be called by a plugin / module that want to update its state. it should be implemented by a module which provide `status` information (in our case the icon-list).

instead of having a module to  implement `setStatus`. we could require the plugin which want to update the status to emit `setStatus` event (with the same parameter) - that 's more flexible.
