### ISSUE TITLE
Yul compiler

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1766]
the current `compile-tab` can easily be configurable for compiling `yul`.
there could be 3 ways of handling that:

 - a switch in the current solidity tab to compile `yul`
 - no switch but automatically switch the language if the file extension is `yul`
 - having a separate `yul` module (will to have create a new class inheriting from `compile-tab`

**Comment by axic** [comment]
Today's nightly contains support for Yul through standard JSON. It will be released as part of 0.5.7.

See https://solidity.readthedocs.io/en/latest/using-the-compiler.html#compiler-input-and-output-json-description

It supports the same input and output format, but the language key is set to `Yul` and it only returns evm bytecode.
