### ISSUE TITLE
Landing page feedback

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1777]
I switched the theme to https://bootswatch.com/4/cerulean/bootstrap.min.css - cerulean
I see that the div the says that it is a card ( in the homepage) has these classes:
class="card bg-primary text-success border-success p-3"
text-success is green and in cerulean - bg-primary is blue - so the text isn't legible.

Also the body text of the card is further defined in the csjs and it is:
.link_4m9f1c {
cursor: pointer;
background-color: var(--primary);
color: var(--success);
font-weight: normal;
text-decoration: none;
}

This makes all the links green with a background color of blue.
I think you are defining it too much. All the stuff in the .link_4m9f1c should be left to the theme - so it isn't needed.

Also the width of the cards is not specified - so they are each incredibly wide. This might be due to flex-box setting. I'm not sure why it doesn't show up in the fresca theme.

**Comment by LianaHus** [comment]
thanks, @yann300, for feedback!
this should be fixed in the second PR

**Comment by yann300** [comment]
oh this is rob's feedback... rob added this just after i merged the pr... making sure it is not lost...
cc @ryestew

**Comment by yann300** [comment]
@LianaHus could we close now?
