### ISSUE TITLE
Clear Permission Check

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1784]
The clear local storage for plugin permission should be somewhere place. perhaps in the settings module ?

**Comment by yann300** [comment]
@GrandSchtroumpf could we put that one in before release?

**Comment by GrandSchtroumpf** [comment]
I don't like the idea of putting that in the settings because it's not related to environment. The best place whould be inside PluginManager maybe. But not sure where exaclty.
But yes sure, it should be done before release.

**Comment by yann300** [comment]
right, plugin manager panel looks like a good place to put it.
