### ISSUE TITLE
Cannot connect to the newly-installed MetaMask

### ISSUE THREAD

**Issue by ChenchenYo** [ethereum/remix-ide#1789]
After a Chrome browser has added MetaMask extension for the first time and user creates their wallet, the Remix-IDE does not detect MetaMask under the environment "injected web3". The "accounts" drop down remains empty.

This problem has occurred on multiple PCs yesterday.

We have tried to re-launch the browser but nothing changed.

**Comment by yann300** [comment]
please try removing the privacy option of metamask.
we are updating this soon
