### ISSUE TITLE
Can't use `blockhash(block.number-1)` in JS VM

### ISSUE THREAD

**Issue by islishude** [ethereum/remix-ide#1794]
```Solidity
contract Test {
    uint256 public nonce;
    constructor() public {
        
    }

    
    function bhash() public returns (bytes32) {
        nonce++;
        return blockhash(block.number-1);
    }
 }
  ```

![image](https://user-images.githubusercontent.com/24730006/55372681-2a21da00-5535-11e9-8adb-83a9cbb7eb88.png)

**Comment by simibac** [comment]
I have the same problem. 

block.number seems to work but blockhash causes an issue with the JS VM. This is not the case with any of the official testnets or ganache.

```
pragma solidity ^0.5.0;

contract BlockHash{
    function getCurrentBlockNumber() public view returns(uint){
        return block.number;
    }
    
    function getPreviousBlockHash() public view returns(bytes32){
        return blockhash(block.number-1);
    }
}
```

**Comment by falcon-18** [comment]
I'm having the same issue on the JS VM. Have you found a workaround?

**Comment by simibac** [comment]
I simply don't use the JS VM. Instead I use [ganache-cli](https://github.com/trufflesuite/ganache-cli) to run a local blockchain. 

When ganache is running, you can connect to it through Run > Environment > Web3 Provider and set the the Web3 Provider Endpoint to "http://localhost:8545".

**Comment by Arachnid** [comment]
Why was this closed? As far as I can tell, it's still an issue.
