### ISSUE TITLE
Switch ApiFactory to BaseApi

### ISSUE THREAD

**Issue by GrandSchtroumpf** [ethereum/remix-ide#1805]
Switch the modules from `ApiFactory` to `BaseApi`. The profile is inside the `super(profile)`

**Comment by LianaHus** [comment]
@GrandSchtroumpf can I close this?

**Comment by GrandSchtroumpf** [comment]
Sure

Le sam. 13 avr. 2019 à 13:46, Liana Husikyan <notifications@github.com<mailto:notifications@github.com>> a écrit :

@GrandSchtroumpf<https://github.com/GrandSchtroumpf> can I close this?
