### ISSUE TITLE
Not able to deploy with Injected web3

### ISSUE THREAD

**Issue by kevinsimper** [ethereum/remix-ide#1818]
You can't deploy a contract with Metamask, something has broken and the account is not showing in the interface. 

And if you click the Deploy button you get this error in the console

```
creation of helloWorld errored: Send transaction failed: invalid address . if you use an injected provider, please check it is properly unlocked. 
```

and my metamask account is unlocked, I click the metamask icon and it does not prompt me anything.

I have tried reinstalling the extension.

I also tried it on 2 other computers and it didn't work there.

It used to work fine :)

![image](https://user-images.githubusercontent.com/1126497/55693640-f267c780-5964-11e9-958c-954e2413ce4f.png)

and it doesn't matter if it is Rinkeby or the Mainnet

**Comment by kevinsimper** [comment]
There is this error when the page load but I don't know it is related or another bug 
![image](https://user-images.githubusercontent.com/1126497/55693690-407ccb00-5965-11e9-80a9-453757094e7c.png)

**Comment by yann300** [comment]
Could you disable the privacy mode in metamask? we'll push a fix soon

**Comment by kevinsimper** [comment]
@yann300 It works by disabling privacy mode.

Weird, because it has worked after the privacy mode was introduced in November

**Comment by Solid-Code** [comment]
I have the same problem with metamask 6.3.2 not in privacy mode.
No popup from metamask or waiting transaction.  Does not work on Kovan or Mainnet.  remix from remix.ethereum.org is working.

remix-ide@0.8.0-alpha

Uncaught TypeError: Cannot read property 'getUnpersistedProperty' of undefined
    at app.js:197699
    at continueCb (app.js:266838)
    at Object.callback (app.js:197695)
    at app.js:192743
    at app.js:194040
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1)
    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1)
    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1

**Comment by yann300** [comment]
the original issue (supporting `ethereum.enable()`) has been deployed.
