### ISSUE TITLE
Solidity Compiler in the swap panel

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-ide#1829]
the spinner isn't spinning - when compiling.  Actually I got it to spin but only when there was an error in the code.

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-ide/pull/1891

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-ide/pull/1859

**Comment by yann300** [comment]
the spinner from the compile tab is spinning now. see PR above
