### ISSUE TITLE
Static Analysis Scrollbars

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-ide#1831]
- Update the static analysis scroll bars so that they is never 3 scrollbars.  Also the top one should be a fixed height and the bottom one should take the remaining height - so that there is never unused space at the bottom of the page.

- create accordions for modules

**Comment by ryestew** [comment]
The compile tab has 2 scroll bars - side by side.  Well they are side by side at the top of the panel but the inside one is only for the checkboxes.  The side by side scroll bars-in general- are a sign of a UX problem.  In this case it isn't the worst.  So the current is an OK temporary solution.
Here are a couple of solutions:
1. Make the top div with the checkboxes smaller with a max-height: of 200 or 150px and grab the height of the screen with JS and do the math so that max-height of the lower results is the remainder of the screen size - and make that the max-height.
2. Make the checkboxes or both for that matter with a bootstrap collapse -so that by default you only see the results - but you could view the checkboxes by clicking on a button.  The idea is that you'd only see one or the other.

**Comment by yann300** [comment]
fix https://github.com/ethereum/remix-ide/pull/2773
