### ISSUE TITLE
Implement remix-plugin@0.0.2-alpha.2

### ISSUE THREAD

**Issue by GrandSchtroumpf** [ethereum/remix-ide#1835]
- [x] Change `ApiFactory` to `BaseApi`
- [x] Change `SourceHighlighter` to `Editor`
- [x] Remove `TxListenerModule` and add it inside `UdappModule`
- [x] Split `App` classes into two classes : `App` and `NetworkModule`

Update methods/events names for : 
- [x] `Network` 
- [x] `Editor`
- [x] `Compiler`
- [x] `FileSystem`
- [x] `Udapp`
- [x] `Theme`

**Comment by yann300** [comment]
@GrandSchtroumpf i think that can be closed isn't it?

**Comment by GrandSchtroumpf** [comment]
Yes thx
