### ISSUE TITLE
Where will the plugin appear?

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-ide#1846]
I just activated pipeline and instinctively looked in the icon panel for the pipeline icon.  But it wasn't there - because it is in the main panel - duhh.  But this needs to be explained somehow in the plugin manager - as to where it will appear - Icon panel - or main panel.

**Comment by yann300** [comment]
in the last version, the tab automatically focus on the newly activated plugin. Would that be enough?

**Comment by yann300** [comment]
@ryestew closing that now, please reopen if necessary
