### ISSUE TITLE
Swap panel inner layout

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-ide#1849]
all tabs should fit in min-width of swap panel.
should use % to resize with swap's width

currently Deploy and Viper look bad in min-width of Swap panel

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-ide/pull/1845

**Comment by LianaHus** [comment]
@ryestew could you please link with you pr so we can close this after merge. TIA!

**Comment by yann300** [comment]
@ryestew @LianaHus  could you link the PR?

**Comment by yann300** [comment]
@LianaHus @ryestew  can we close it?

**Comment by LianaHus** [comment]
if Rob is done with it I guess yes.
