### ISSUE TITLE
Solidity plugin: error selection should open the file and select the location of error contract

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-ide#1851]

**Comment by LianaHus** [comment]
I can't reproduce this but happens to me twice.

**Comment by LianaHus** [comment]
The problem is compile tab is not updating the result part of it when the selected file has been changed.

**Comment by yann300** [comment]
At the moment when we activate `solidity` we do not autoselect a file. Then the compile tab displays `No file Selected`. is that what you mean?

> the result part of it

the result part update only if the compilation is triggered. so if you just select a new file, it is normal to not update the result cause the compilation is not triggered.
We could force recompilation upon file selection if the `autocompile` is on, but we might have performances issues for heavy contracts.

**Comment by yann300** [comment]
I think this was part of https://github.com/ethereum/remix-ide/pull/1891 . 
closing it, @LianaHus please reopen if this still need attention ;)
