### ISSUE TITLE
how am i suppose do?

### ISSUE THREAD

**Issue by wangyuyuer** [ethereum/remix-ide#1873]
how am i suppose do ?
![image](https://user-images.githubusercontent.com/48520185/56287231-5bfa8980-614e-11e9-8690-655903113382.png)

**Comment by yann300** [comment]
that's an issue with node / npm, please try updating to latest version

**Comment by LianaHus** [comment]
I'm closing the issue. @wangyuyuer  if you still have problems with this feel free to contact us in the gitter chanel https://gitter.im/ethereum/remix
