### ISSUE TITLE
SSL Certificate Expired: solc-bin.ethereum.org

### ISSUE THREAD

**Issue by touhonoob** [ethereum/remix-ide#1881]
The certificate is expired and breaking remix.ethereum.org
![Selection_086](https://user-images.githubusercontent.com/1391892/56423939-cf340500-62e0-11e9-82d4-fcb2f3db5f23.png)
![Selection_085](https://user-images.githubusercontent.com/1391892/56423946-d3f8b900-62e0-11e9-9fbc-774ee2db001a.png)

**Comment by rynomad** [comment]
If anyone is being blocked by this, until it get fixed, a (horrible) workaround is to manually change your date/time settings to have it be march.

**Comment by yann300** [comment]
should be fixed by now. closing it
