### ISSUE TITLE
Cannot get account list: Error: The method personal_listAccounts does not exist/is not available

### ISSUE THREAD

**Issue by industral** [ethereum/remix-ide#1937]
Chrome: 74.0.3729.131 (macOS)
Metamask: 6.4.1

When selected "Injected Web3" get "Cannot get account list: Error: The method personal_listAccounts does not exist/is not available".

<img width="1675" alt="Screen Shot 2019-05-05 at 5 41 03 PM" src="https://user-images.githubusercontent.com/331772/57195571-0a7b3880-6f5d-11e9-974e-b4d564f2d6a1.png">

**Comment by industral** [comment]
@yann300 I found that remix doesn't **EIP-1102** compatible. To fix it, just open Console on remix page, and execute `window.ethereum.enable()` (new way) or `web3.currentProvider.enable()` (old way). That will bring popup with connection request. After accept everything works fine.

**Comment by yann300** [comment]
the original issue (supporting `ethereum.enable()`) has been deployed.
