### ISSUE TITLE
FileManager should expose a "setCurrentFile" method

### ISSUE THREAD

**Issue by GrandSchtroumpf** [ethereum/remix-ide#1978]
Right now we can getFile, setFile and getCurrentFile, but we should also be able to set the current file like that plugin could focus the attention of the user when they "setFile".

**Comment by yann300** [comment]
shouldn't that be `switchFile` ?

**Comment by GrandSchtroumpf** [comment]
For me "switch" is more when you have only two options, like in "switch the light".
Also the idea was to match the get / set pattern.
getFile <-> setFile
getCurrentFile <-> setCurrentFile
But it can be missunderstood as "set the content of the current file" instead of "set the current file"...

**Comment by yann300** [comment]
or `switchToFile`
