### ISSUE TITLE
use remix to sign message

### ISSUE THREAD

**Issue by yanyanho** [ethereum/remix-ide#1986]
I  use js to test my solidity and want to sign some message(contains some address and int type; like this: 
"0x610033b6dd5a08004e46f2097ca09b693d744118",100,"0x0000000000000000000000000000000000000000",200,77784606,1 )   I konw I cannot get the privatekey of the test account ,yet I used sign message function and found that the hash is not right. What formate should I tranform into it.

**Comment by yann300** [comment]
we fixed it with the new version, please check the new interface.
closing this, please reopen if you still have the issue. thanks ;)
