### ISSUE TITLE
Run contract at a given Address fails

### ISSUE THREAD

**Issue by taylorjdawson** [ethereum/remix-ide#2013]
Steps to replicate:
- Open remix
- Click **Run** tab
- Enter address in **at Address** box (see image below)
- Click the button **at Address**
- ...and nothing 

Example:
![image](https://user-images.githubusercontent.com/29665732/58212516-e54c3100-7ca3-11e9-8b96-35eb141d4f54.png)
Console output:
![image](https://user-images.githubusercontent.com/29665732/58212581-1e84a100-7ca4-11e9-8907-7075e56f5e74.png)

**Comment by yann300** [comment]
the message is unfortunate, we'll fix that.
anyway, for using this action you first need to compile a contract

**Comment by taylorjdawson** [comment]
Right! Thanks! 👍
