### ISSUE TITLE
While debugging, it is very hard to see all relevant information

### ISSUE THREAD

**Issue by chriseth** [ethereum/remix-ide#2019]
During debugging, it is very hard to see both the instructions, the stack and the memory content at the same time, which forces the developer to scroll up and down all the time.

![image](https://user-images.githubusercontent.com/9073706/58257481-4988f680-7d71-11e9-8bce-4c2d6477e277.png)

Some suggestions to improve this:
 - add possibility to completely hide the "instruction details" part, so that a button that would open it occupies zero vertical space (or put it right of the instruction list)
 - also allow to collapse the other detail panes (solidity locals, etc) so that they use zero vertical space
 - use less vertical separation between the lines in the stack

**Comment by LianaHus** [comment]
closing this now with #2925 but we also plan to make those dockable and movable
