### ISSUE TITLE
Inputting bytes32 argument on new version causes => Error: invalid bytes32 value  

### ISSUE THREAD

**Issue by hilmarx** [ethereum/remix-ide#2027]
**Trying to pass a hex as an argument to function with a bytes32 parameter on the new interface like so:**

<img width="1237" alt="Screenshot 2019-05-27 at 17 47 57" src="https://user-images.githubusercontent.com/19579480/58429973-db616e00-80a7-11e9-9416-8bc418c1c8f2.png">

**Respective function:**

<img width="564" alt="Screenshot 2019-05-27 at 17 48 08" src="https://user-images.githubusercontent.com/19579480/58429981-e3b9a900-80a7-11e9-8879-19c833aca28c.png">

**Terminal Output:**

<img width="1068" alt="Screenshot 2019-05-27 at 17 48 19" src="https://user-images.githubusercontent.com/19579480/58429989-ef0cd480-80a7-11e9-8c12-baba38d1fa01.png">

**However, using the old interface with exactly the same code + same compiler (0.5.1) + input, everything works fine:**

<img width="876" alt="Screenshot 2019-05-27 at 17 48 38" src="https://user-images.githubusercontent.com/19579480/58430000-fcc25a00-80a7-11e9-81a6-38f0f1d3a8d9.png">

**Terminal Output:**

<img width="844" alt="Screenshot 2019-05-27 at 17 49 00" src="https://user-images.githubusercontent.com/19579480/58430017-09df4900-80a8-11e9-93d2-37c7130f53c4.png">

Maybe a bug in passing the argument through the new interface?

**Comment by yann300** [comment]
we've updated ethers to use the latest version (4.0.27). In that version `0x12` is not a valid `bytes32` ...
Let's keep this issue open for now
cc @LianaHus

**Comment by hilmarx** [comment]
other keccak hashes seem to work fine as inputs in the new interface, was just confused as ```0x12``` worked with the old one.
