### ISSUE TITLE
when i install remix-ide, something wrong

### ISSUE THREAD

**Issue by uhmhaha** [ethereum/remix-ide#2053]
node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/skyang/.npm-global/lib/node_modules/remix-ide/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> scrypt@6.0.3 install /Users/skyang/.npm-global/lib/node_modules/remix-ide/node_modules/scrypt
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:430:11)
gyp ERR! stack     at Socket.emit (events.js:200:13)
gyp ERR! stack     at Pipe.<anonymous> (net.js:586:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/12.3.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/skyang/.npm-global/lib/node_modules/remix-ide/node_modules/scrypt
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/skyang/.npm/_logs/2019-05-30T06_55_32_741Z-debug.log

**Comment by Donaldhan** [comment]
no answer， happened same question， is the node version？

**Comment by librauee** [comment]
I meet the same problem with you.
I search the internet find python2 may help.

**Comment by uhmhaha** [comment]
Hi, Xiao.You maybe need to down grade your python version!!I solved this problem.If u have more question, let me know.
------ Original Message ------
Date: Saturday, Jan 4, 2020 07:43:08 PM

**Comment by librauee** [comment]
> Hi, Xiao.You maybe need to down grade your python version!!I solved this problem.If u have more question, let me know. ------ Original Message ------ Date: Saturday, Jan 4, 2020 07:43:08 PM From: "Xiao Li" <notifications@github.com> To: "ethereum/remix-ide" <remix-ide@noreply.github.com> Cc: "uhmhaha" <uhmhaha@nate.com>, "Author" <author@noreply.github.com> Subject: Re: [ethereum/remix-ide] when i install remix-ide, something wrong (#2053) I meet the same problem with you. I search the internet find python2 may help. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you very much, I have solved this problem!
