### ISSUE TITLE
GuessTheSecretNumberChallenge.guess errored: gas required exceeds allowance or always failing transaction 

### ISSUE THREAD

**Issue by runcone** [ethereum/remix-ide#2068]
When I try to run this code and I click the guess button in the deployed contracts area I get the error: GuessTheSecretNumberChallenge.guess errored: gas required exceeds allowance or always failing transaction. Which results in me being unable to change the iscomplete result to get the bool to be true.

pragma solidity ^0.4.21;

contract Solution {
    bytes32 answer = 0xdb81b4d58595fbbbb592d3661a34cdca14d7ab379441400cbfa1b78bc447c365;
    
    function test() public view returns (uint8) {
        for (uint8 i=0; i<256; i++) {
            if (keccak256(i) == answer) {
                
            }
        }
    }
}

**Comment by yann300** [comment]
are you using javascript VM or metamask or other provider?

**Comment by runcone** [comment]
I’m using metamask. I’m trying to complete the capture the ether challenge aswell but I’m struggling to get it to call back to CTE would you happen to know anything about that aswell?

**Comment by yann300** [comment]
are you the last release? 0.8.1?

**Comment by LianaHus** [comment]
closing this. please reopen if you still have a problem
