### ISSUE TITLE
mythx plugin issue

### ISSUE THREAD

**Issue by snaketh4x0r** [ethereum/remix-ide#2084]
when solidity code is compiled and mythx analyze clicked,it shows page not responsive error.
also the mythx plugin page is blank as shown in screenshot so had to deactivate and then activate again to show my credentials box.
here are following screenshots
my friend also was getting same issue on his browser 
chrome Version:75.0.3770.90 (Official Build) (64-bit)

![Capture](https://user-images.githubusercontent.com/48221232/59602569-a5eaf600-9124-11e9-8480-fed0209d2992.png)

![Capture2](https://user-images.githubusercontent.com/48221232/59602577-ac796d80-9124-11e9-9e1a-4d682cb3438a.png)

would like to provide more details

**Comment by yann300** [comment]
are you using `Brave`? if this is the case perhaps the `localStorage` is not accessible (I suppose we should not fail here...)

**Comment by yann300** [comment]
could you check for any javascript error?

**Comment by snaketh4x0r** [comment]
no not using brave
here are errors

app.js:44739 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 "currentFileChanged" listeners added. Use emitter.setMaxListeners() to increase limit.
_addListener @ app.js:44739
app.js:200212 Loading https://solc-bin.ethereum.org/bin/soljson-v0.5.0+commit.1d4f565a.js without worker
soljson-v0.5.0+commit.1d4f565a.js:3 Invalid asm.js: Invalid member of stdlib
DevTools failed to parse SourceMap: https://remix-mythx-plugin.surge.sh/static/js/2.62a897f9.chunk.js.map

after loading webpage once again and activating mythx plugin,this is the error
![Capture3](https://user-images.githubusercontent.com/48221232/59605300-2103da80-912c-11e9-9df2-284d77e948d2.PNG)

**Comment by yann300** [comment]
just tried with the classic Ballot.sol, it works. Perhaps something specific to your contract... could you post it?
cc @b-mueller

**Comment by snaketh4x0r** [comment]
sorry I can't provide code due to non disclosure policy of our startup.
I hope you can understand.

have you tried it on different contracts other than default ballot.sol
also on browser version I mentioned.

I ran it additionally on other contracts to check if it was a problem with my contract,on first contract it gave result shown in first screenshot.on second analyze button kept spinning and when I changed tabs and came back it just showed blank page as before 
below are both contracts I ran it on
https://github.com/openberry-ac/Auction/blob/master/contracts/AuctionBox.sol
https://etherscan.io/address/0xb3775fb83f7d12a36e0475abdd1fca35c091efbe#contracts

errors it produced
/build/app.js:44739 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 "currentFileChanged" listeners added. Use emitter.setMaxListeners() to increase limit.
_addListener @ /build/app.js:44739
/build/app.js:200212 Loading https://solc-bin.ethereum.org/bin/soljson-v0.5.3+commit.10d17f24.js without worker
app.js:200212 Loading https://solc-bin.ethereum.org/bin/soljson-v0.4.20+commit.3155dd80.js without worker
soljson-v0.4.20+commit.3155dd80.js:3 Invalid asm.js: Invalid member of stdlib


screenshots

![Capture4](https://user-images.githubusercontent.com/48221232/59609496-1f8ae000-9135-11e9-8063-108e13687fe1.PNG)

![Capture5](https://user-images.githubusercontent.com/48221232/59609477-169a0e80-9135-11e9-9b16-20c4fd482e0b.PNG)

**Comment by Gtonizuka** [comment]
I just tried to upload and analyze the AuctionBox.sol contract and seems to work just fine for me (see screenshot below). Everything looks good on the Chrome console too.

@snaketh4x0r from your logs it seems that there was an issue with the compiler? Can you make sure that you are running the contract I mentioned above using Solidity compiler plugin on version 0.5.3+commit.10d17f24? I am using Chrome 74.0.3729.169 . 
Also after you click could you leave the current tab open? Should not take longer than 120 secs to be analysed on MythX backend.
[https://imgur.com/a/7Q1kPQq](url)

**Comment by snaketh4x0r** [comment]
I think green tick means it was compiled prroperly
![Capture6](https://user-images.githubusercontent.com/48221232/59617534-22d99800-9144-11e9-9884-75d220ff70e7.PNG)

**Comment by snaketh4x0r** [comment]
I will just downgrade chrome to your version after some time and try it

**Comment by yann300** [comment]
@snaketh4x0r what is the status of this issue? which version of chrome were you using?

**Comment by snaketh4x0r** [comment]
this is the error I m getting @yann300 
I m sure it is problem of integration with mythx plugin
other static analysis plugin works fine 
the error could help to trace the issue
current chrome version:75.0.3770.90 (Official Build) (64-bit)
also tested it on latest brave browser,there were more errors
![Capture9](https://user-images.githubusercontent.com/48221232/59803746-0ab37580-930a-11e9-9167-5cddc90ce65c.PNG)

before activating mythX plugin on brave
![Capture11](https://user-images.githubusercontent.com/48221232/59804319-a42f5700-930b-11e9-95ea-b327fa201aea.PNG)

after activating mythX plugin on brave
![Capture12](https://user-images.githubusercontent.com/48221232/59804401-d5a82280-930b-11e9-83eb-53ecb1c0086d.PNG)

**Comment by snaketh4x0r** [comment]
is there a tool which helps me test website on different versions of chrome.
could be helpful

**Comment by snaketh4x0r** [comment]
@yann300 looks like contract Auction gets analyzed but AuctionBox gives that error
https://github.com/openberry-ac/Auction/blob/master/contracts/AuctionBox.sol
mirko from mythX will look into it.
a check would be to introduce bug in AuctionBox contract and check if mythX analysis it
if it does then there are no problems but if it doesn't analyze then there might be problem
 
you may close this issue if you feel so

**Comment by aquiladev** [comment]
I'm facing issues with brave too, I think we need to address it separately.

I did fixes for Mythx report conversion. Mythx returns unknown file references (it can be because of external import is present `import "https://github.com...`)

Plugin treats it as a error (`Error: File not found`) right now:

![image](https://user-images.githubusercontent.com/1164492/59841272-483cf080-9354-11e9-8ba8-0ccda0ad5faf.png)

**Comment by aquiladev** [comment]
the new version needs to be deployed

**Comment by snaketh4x0r** [comment]
ok the issue was solved thank you
I m closing this now

**Comment by t4sk** [comment]
I am using Brave browses, turning off the shield solve the problem.
