### ISSUE TITLE
List of outdated images to update in docs

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-ide#2086]
Please add to this list:

1. https://remix-ide.readthedocs.io/en/latest/run.html https://remix-ide.readthedocs.io/en/latest/_images/a-runtab1.png

**Comment by ChrisChinchilla** [comment]
Images on these pages:

- https://remix-ide.readthedocs.io/en/latest/import.html

For bonus points, you could use something like robots framework to autogenerate and annotate images so they are never out of date.
