### ISSUE TITLE
How to input struct in the run module

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#2095]
for input struct the easiest way is to use array `[]`;
If the struct members has name, using js object should work `{name: value, name1: value}`

**Comment by ChrisChinchilla** [comment]
If you try to use `struct`s into a function call (when using the run module) you need to use ABIEncoderV2. The easiest way to do this is to use an array instead, for example:

If the struct is

```
struct r 
{
   string t,
   uint r
}
```

The you can use:

```
["this is a string", 23]
```

Instead.

**Comment by ryestew** [comment]
Is this something that should go in the FAQ below how to pass a tuple? This issue is responding to a solidity question - right?

**Comment by ryestew** [comment]
I'm not sure where ABIEncoder V2 is.  

And is there fixed order in Structs - like in mappings?  By not writing the names of the members, we update the values by the order in the array. ( in Chris's example)
