### ISSUE TITLE
https://remix.ethereum.org new version. Button "add local files" doesn't work.

### ISSUE THREAD

**Issue by IvanMolodtsov** [ethereum/remix-ide#2097]
File explorer tab. Button "add local files" doesn't work. Checked on Google Chrome and Mozila Firefox. Instead of opening "choose file" window it expands/wraps browser folder.

**Comment by LianaHus** [comment]
just checked on master it works for me. @yann300 are you able to reproduce it?

**Comment by LianaHus** [comment]
it's broken on alpha though.

**Comment by LianaHus** [comment]
fixed on alpha. I'm closing the issue, thanks for the report
