### ISSUE TITLE
Button "copy value to clipboard" in deployed contract doesn't work properly.

### ISSUE THREAD

**Issue by IvanMolodtsov** [ethereum/remix-ide#2102]
function to copy contract address isn't triggered when the button is clicked. It works only when the icon inside the button is clicked, causing a lot of missclicks.

**Comment by yann300** [comment]
which button in Remix are you talking about?

**Comment by IvanMolodtsov** [comment]
on tab "Deploy & Run transactions" in deployed contrats, button which is next to  contract address.
<img width="205" alt="btn" src="https://user-images.githubusercontent.com/47519770/60009070-01723200-9697-11e9-8fcb-1f690aa09c8d.PNG">
