### ISSUE TITLE
when run remix-ide , localhost:8080  show ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by MikeBKC** [ethereum/remix-ide#2133]
Environment：windows10
remix-ide 
setup notifications for D:\Blockchain
Starting Remix IDE at http://localhost:8080 and sharing D:\Blockchain
Sun Jun 30 2019 15:57:08 GMT+0800 (GMT+08:00) Remixd is listening on 127.0.0.1:65520

http://localhost:8080   
show  ERR_CONNECTION_REFUSED

**Comment by yann300** [comment]
@GrandSchtroumpf could you give a try please - do you get the same?

**Comment by GrandSchtroumpf** [comment]
Yes I've the same. It's because of http-server. I use live-server now.

**Comment by Mwuxiaoyu** [comment]
@GrandSchtroumpf  Not on windows ,but No problem with Linux.

**Comment by Solexplorer** [comment]
I'm also experiencing this issue

**Comment by GrandSchtroumpf** [comment]
Can you try to run on two separated terminal : 
`npm run watch`  : rebuild on changes
`npx live-server` : run and reload http server on changes

**Comment by Solexplorer** [comment]
@GrandSchtroumpf Actually this workaround doesn't show me anymore `ERR_CONNECTION_REFUSED` but now it's loading the page infinitely, this what I've done:
`npm run watch`
`npx live-server`
`cd remix`
`npm run bootstrap`

**Comment by GrandSchtroumpf** [comment]
`npx live-server` might be long the load (10-15sec). I'm not sure to understand why you do `cd remix` though. Here is the all process : 
`git clone https://github.com/ethereum/remix-ide.git`
`cd remix-ide`
`npm install`
`npm run watch`
`npx live-server` (on a second terminal)

**Comment by Solexplorer** [comment]
I've cloned the repo downloaded in another folder and followed your steps but it's not loading the app, this is what I see:
![image](https://user-images.githubusercontent.com/50027175/62358527-3040bb00-b515-11e9-899f-5c44ad5d15ec.png)

**Comment by Solexplorer** [comment]
EDIT: It actually worked 😄 , looks like that it takes 1 minute to get the app fully functional

**Comment by GrandSchtroumpf** [comment]
Yeah... that is another issue ^^

**Comment by santanaruben** [comment]
Just as a clarification of what worked for me.
I used to connect using `localhost:8080`, but on an update, I got the error `ERR_CONNECTION_REFUSED`, so looking for a little, I found a solution, it seems to be that you have to put `localhost:8080/index.html`
