### ISSUE TITLE
build_debugger: Cannot find module 'src/app/debugger/remix-debugger/index.js'

### ISSUE THREAD

**Issue by 0yi0** [ethereum/remix-ide#2135]
# Description

`npm run build_debugger` results in
> Cannot find module 'src/app/debugger/remix-debugger/index.js'

# Version
- `remix-ide` `32ae568157bea47da1a72415bb1933e7f0b90afa`
- `remix` `57ebf16ec5a4aa4a733560d3abd3facebbed7439`

# Steps
```
cd remix
npm i
npm run bootstrap
cd -

cd remix-ide
npm i
npm run setupremix
npm run build
npm run build_debugger
```

# Error Message
```
> remix-ide@0.8.3 build_debugger /root/remix-ide
> browserify src/app/debugger/remix-debugger/index.js -o src/app/debugger/remix-debugger/build/app.js

Error: Cannot find module '/root/remix-ide/src/app/debugger/remix-debugger/index.js' from '/root/remix-ide'
    at /root/remix-ide/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/root/remix-ide/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/root/remix-ide/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /root/remix-ide/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (fs.js:158:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remix-ide@0.8.3 build_debugger: `browserify src/app/debugger/remix-debugger/index.js -o src/app/debugger/remix-debugger/build/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remix-ide@0.8.3 build_debugger script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-01T07_45_12_413Z-debug.log
```

# Environment
I'm using docker image `ubuntu:18.04`.
```
$ uname -a
Linux 9e6dff0d5203 4.15.0-1041-aws #43-Ubuntu SMP Thu Jun 6 13:39:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ node --version
v11.15.0
$ npm --version
6.7.0
$ nvm --version
bash: nvm: command not found
```

**Comment by yann300** [comment]
where do you see that `npm run build_debugger` should be run? so we can remove it from the doc

**Comment by 0yi0** [comment]
Oops I didn't see it from the doc, I see it from `package.json`.

I followed [README#L42](https://github.com/ethereum/remix-ide/blame/91ed294e47236a49717a3509fb2f7e73fa2cc386/README.md#L42) and failed to run `npm start` because `build/app.js` doesn't exist.
I asked my fellow developers and succeeded after executing `npm run build`, so I continued to try on `npm run build_debugger` since I wanna try changing few things on debugger.

So my real question should be, how to get started with developing on debugger?

I apologize for the messy issue report, and thanks for reading.

**Comment by yann300** [comment]
> So my real question should be, how to get started with developing on debugger?

do you mean `remix-debug` or improving the debugger UI ?

**Comment by 0yi0** [comment]
I think the change would mostly be in `remix-debug`, only minor edit would be needed in debugger UI.

Is `npm run build_debugger` for the deprecated `remix-debugger`?
I thought I need to `npm run build_debugger` to use it on Remix IDE but I may misunderstand it.

**Comment by yann300** [comment]
I think running: 
```
cd remix
npm i
npm run bootstrap
cd -

cd remix-ide
npm i
npm run setupremix
npm run build
npm run serve
```

you should be ok with that (or running `npm run start`)

**Comment by yann300** [comment]
closing now
