### ISSUE TITLE
https version of https://remix-plugin.provable.xyz/ doesn't work

### ISSUE THREAD

**Issue by gpersoon** [ethereum/remix-ide#2144]
When trying out the PROVABLE - ORACLE SERVICE plugin in remix-ide i saw the following error message:
```xml
Error 521 Ray ID: 4ef9a3346d39c863 • 2019-07-01 16:08:14 UTC
Web server is down You Browser Working Amsterdam Cloudflare Working remix- plugin.provable.xyz Host Error
```
When i access http://remix-plugin.provable.xyz/ it works fine:
```xml
v0.2.0 Provable oracle environment is ready and is waiting for queries. Queries
```
However https://remix-plugin.provable.xyz/ says:
```xml
Error 521 Ray ID: 4ef9a3be7d5cd8f5 • 2019-07-01 16:08:36 UTC
Web server is down
```
So this is probably a config error with https

**Comment by yann300** [comment]
cc @D-Nice @ryestew

**Comment by gpersoon** [comment]
Both url's are working now.
=> Close

**Comment by D-Nice** [comment]
Apologies, there was a misconfiguration that occurred and was fixed several days ago (July 4th).
