### ISSUE TITLE
meet Unknown key "details" error when using v0.8.4

### ISSUE THREAD

**Issue by BohengLiu** [ethereum/remix-ide#2157]
Today, I compiled my contracts and found all contract were compiled unsuccessfully. The error was Unknown key "details". 
I found a new release last day. Then I install remix-ide in local at v0.8.3 and it works.

So I think if it relates to the newest release version.

**Comment by LianaHus** [comment]
@chriseth @yann300 could this be because of optimizer?

**Comment by yann300** [comment]
Probably yes, @BohengLiu which compilerror version are you using?

**Comment by chriseth** [comment]
Just FYI: the key was added in Solidity 0.5.5

**Comment by BohengLiu** [comment]
Oh, that's it. I use 0.5.3

**Comment by LianaHus** [comment]
thanks Chris, I was about to ask you
