### ISSUE TITLE
Run and Deploy Side Panel - Needs text wrapping in output from function calls

### ISSUE THREAD

**Issue by KevinSmall** [ethereum/remix-ide#2170]
In the "run and deploy" side panel window, the output from function calls should be word wrapped.

The output from a call displays on a single line and does not word wrap. So when a call returns eg an array of addresses, it is hard to see results, even when stretching window very wide:

![image](https://user-images.githubusercontent.com/5543867/60879951-939f3c00-a23a-11e9-91e1-998c92ebe5dc.png)

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-ide/pull/2185
