### ISSUE TITLE
Remix: 0x0 Transaction mined but execution failed due to construction

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/remix-ide#2171]
I have the following example smart contract, where I cannot deploy using `remix` into my private network using environment `Web3 provider`. The error I am getting is `Transaction mined but execution failed due to construction`.

*Please note,* that my actual smart contract takes around 6.500.000 gas to deploy. I can deploy it if its constructor is empty, but I cannot if I set a storage variable in the constructor like I shown on the example.

```solidity
pragma solidity ^0.5.7;

contract Contract {
    address public owner;
    constructor() public
    {
    	owner = msg.sender; 	
    }
}
```

Transaction receipt:

[![enter image description here][1]][1]

----------

When I comment out `owner = msg.sender;` the contract deploys successfully. What may cause this error?

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/HnBc3.png
  [2]: https://i.stack.imgur.com/26KPz.png

**Comment by avatar-lavventura** [comment]
@yann300: I am using a `Proof-of-Authority` private chain that is generated via geth clique, please see https://github.com/ebloc/eBlocPOA

**Comment by yann300** [comment]
that's pretty weird ... can you debug it? and do you have the same with rinkeby?

**Comment by yann300** [comment]
perhaps some configuration issue (like contract size limit or block gas limit)

**Comment by yann300** [comment]
in ropsten tx costs are 132051 gas (solidity 0.5.7)

**Comment by avatar-lavventura** [comment]
I have check and block gas limit is 8,000,000 on the private chain I am using. I haven't tried with rinkeby @yann300

**Comment by avatar-lavventura** [comment]
I am able to fix by using `solidity ^0.5.0` instead of its higher version and update the miners' geth version to 1.8.23. Any contract with higher `solidity ^0.5.0` fail on gas if a storage variable is updated no matter what

**Comment by yann300** [comment]
@chriseth any idea on this one?

**Comment by chriseth** [comment]
@avatar-lavventura most certainly, this is caused by a non-matching EVM version between Solidity and your private chain. Please debug the transaction and see on which opcode it fails.

**Comment by avatar-lavventura** [comment]
You are right @chriseth : My private chain uses `Byzantium EVM`, when I change compiler default to `Byzantium` it worked. 

Based on the following [answer](https://ethereum.stackexchange.com/a/72775/4575) on stack:
> Is your private network using the Constantinople EVM? If you can deploy 0.5.0 but not 0.5.7, you might be on Byzantium. In Remix, on the compiler tab, try changing the EVM version from "compiler default" to "Byzantium" and see if you're able to deploy successfully.
