### ISSUE TITLE
Run and Deploy Side Panel - Function call buttons should widen as window widens

### ISSUE THREAD

**Issue by KevinSmall** [ethereum/remix-ide#2173]
When the "Run and Deploy" side panel is made wider, the orange and blue buttons do not widen in proportion to the window. This means that, in cases where function names have similar name, I cannot see what a function call button will do, without doing a mouse-over to see the description.

See screenshot below. I cannot easily distinguish between functions "transferOutToBuyer" and "transferOutToSeller" because they both show as "transferOut...". Can the button widths be made wider when window is made wider?

![image](https://user-images.githubusercontent.com/5543867/60896639-9a3faa80-a25e-11e9-955a-f8f1b21855bf.png)

**Comment by LianaHus** [comment]
dublicates https://github.com/ethereum/remix-ide/issues/2022
