### ISSUE TITLE
fileManager.switchFile throw "File.match is not a function"

### ISSUE THREAD

**Issue by GrandSchtroumpf** [ethereum/remix-ide#2183]
When a plugin call method "switchFile" of "fileManage", it throw "file.match" is not a function.

**Comment by yann300** [comment]
what is the input param?

**Comment by GrandSchtroumpf** [comment]
`call('fileManage', 'switchFile', 'browser/ballot.sol)`

**Comment by yann300** [comment]
in `switchFile` param is an array of length 1 with value `browser/ballot.sol`,
it should be a string

**Comment by LianaHus** [comment]
#2199 same issue
