### ISSUE TITLE
Add watch mode for remix dependancies

### ISSUE THREAD

**Issue by GrandSchtroumpf** [ethereum/remix-ide#2186]
We deeply rely on other libraries from remix in the ide (plugin, lib, test, ...), but the watch mode doesn't run `build` when the libs change (event with `npm link`).
We should implement a building pipeline that trigger build when any of linked dependancies update, and reload the page after build is finish.
Personally I only know webpack, but there is also parcel for example.

**Comment by LianaHus** [comment]
done when we switched to monorepo
