### ISSUE TITLE
Does not accept valid bytes32 argument in the ui

### ISSUE THREAD

**Issue by joshuahannan** [ethereum/remix-ide#2194]
I am trying to call a function in a contract on the ropsten testnet that has a bytes32 parameter and I have tried a bunch of different ways of submitting it and they all give me the same error message, 

`transact to CaptureTheEther.setNickname errored: Error encoding arguments: Error: invalid bytes32 value (arg="", coderType="bytes32", value="0xname", version=4.0.32)`

Is this a problem with the way I am submitting or is it a problem with the UI?

**Comment by yann300** [comment]
if you specify `bytes32`, then the value *has* to be 32 bytes long. 
If you don't mean that, you could use a shorter length, the types `string` or `bytes`

**Comment by joshuahannan** [comment]
I'm trying to call someone elses contract that has already been deployed? what is the correct format?
I've tried a bunch of formats that should be 32 bytes long but still aren't working

**Comment by joshuahannan** [comment]
do you know what the correct format is?  say if I wanted to send `deadbeef` as my parameter?

I've tried:

000000000000000000000000deadbeef
0x000000000000000000000000deadbeef
"000000000000000000000000deadbeef"
"0x000000000000000000000000deadbeef"

**Comment by yann300** [comment]
should be that long `0xdeadbeef00000000000000000000000000000000000000000000000000000000`

**Comment by yann300** [comment]
closing that one, please reopen if needed

**Comment by BinaRam** [comment]
Yes; of course. it is a 256bit world, you see.
use 256 bits as value for 32bytes.
