### ISSUE TITLE
remix webpage comes blank with FireFox

### ISSUE THREAD

**Issue by thecircleoflifefree** [ethereum/remix-ide#2200]
remix webpage comes blank with FireFox, so basically nothing loads.

I checked doc https://remix-ide.readthedocs.io/en/latest/index.html and do not see reference to supported browsers.

FF version 60.8.0esr (64-bit)

**Comment by LianaHus** [comment]
Hi, thanks for the report. Do you mean https://remix.ethereum.org/ ? it works fine for me (66.0.5 (64-bit))
Unfortunately, I can't reproduce this.

**Comment by thecircleoflifefree** [comment]
Thanks for your prompt response, yes indeed https://remix.ethereum.org/ 

FF 60.8 esr 64bit.

From the browser console this is the information I get:

Object { https: true, httpsAutoUpgrade: true, privacyScore: 2, entitiesBlocked: Object, entitiesNotBlocked: Object, scores: null }  background.js:20780:25
tab.status: complete. site took 0.924 seconds to load.  background.js:19350:13
Successfully compiled asm.js code (loaded from cache in 10ms)  app.js
unreachable code after return statement  app.js:26605:81
window.controllers/Controllers is deprecated. Do not use it for UA detection.  app.js:2401:520
TypeError: window.customElements is undefined  app.js:19554:13194

**Comment by LianaHus** [comment]
I see. I think the problem is that Firefox supports webcomponents only after v63 and we use webcomponents in our projects. Do you think you can update your browser?

**Comment by thecircleoflifefree** [comment]
Installed latest available which is v68. Issue is solved, thanks very much for your support. Cheers!
