### ISSUE TITLE
replace browserify-reload with browserify-hmr

### ISSUE THREAD

**Issue by qifuren1985** [ethereum/remix-ide#2267]
browserify-reload insert 13 line code at begin of build/app.js, it will cause sourcemap to not work properly（breakpoint is not on the correct line.）。

node_modules/browserify-reload/index.js
```
//late plugin registration, it's okay
var prefix = `(${connect})(${hostname}, ${port});`;
b.plugin(wrap, {prefix});
```

![image](https://user-images.githubusercontent.com/187371/63069845-5752b000-bf4b-11e9-9b5a-8456f32eb09c.png)

**Comment by LianaHus** [comment]
we no longer use browserify since we moved to monorepo
