### ISSUE TITLE
Please leave the old UI up as a secondary option forever

### ISSUE THREAD

**Issue by VexyCats** [ethereum/remix-ide#2282]
Currently the new UI has a warning when switching to the old UI that the old version will only be up for a little bit. 

Please, I urge you to just leave it as it is, without the warning, accessible via switching from a button somewhere. 

I do not like the new UI, granted, I've seen no videos on how to use it, so maybe that would change my mind, but removing it completely seems like a bad UX experience. 

The benefit of remix is that you can open it anywhere and have an environment set up instantly without any clicks. The new UI requires multiple clicks. 

Just my feedback, hope it will stay up.

**Comment by LianaHus** [comment]
@VexyCats with one click on "soldity" environment buttotn in "Home tab" you would basically have everything loaded and ready to work as in old version.
