### ISSUE TITLE
How to debug transaction on testnet/mainnet, and see solidity source?

### ISSUE THREAD

**Issue by drortirosh** [ethereum/remix-ide#2290]
It is possible to walk through the EVM assembly code of a transaction on testnet or mainnet.
But it doesn't help much, since its very hard to map those assembly lines back into solidity code.

Is it possible to load contracts code into the remix debugger, in order to see the source of debugged transaction?

A full AST and local variables are not required - only the source code line...

**Comment by yann300** [comment]
if you before click on debug, you should compile the code source using the same solidity version used for deploying it. You should see then source highlighting.
For the source code, you could check on etherscan if it has been verified.

**Comment by yann300** [comment]
cc @LianaHus @ryestew

**Comment by drortirosh** [comment]
It works with ganache. but when connected to external network, I keep getting "Invalid RPC call"

**Comment by yann300** [comment]
which network?

**Comment by drortirosh** [comment]
any (mainnet, kovan, ropsten)
But I found the source of that: I opened  {{https}}://remix.ethereum.org instead of {{http}}://remix.ethereum.org" 
Now I can debug existing mainnet transaction, but can't see the source.
What I did:
1. I want to debug transaction https://etherscan.io/tx/0x92d3e993acb693ef723bf681d74f5990f24cbea7774cbc99db9004be597d0e86
2. I opened it up, and loaded the published source of the contract in a "rhub.sol" in remix, and compiled it in the right version.
3. I switched to the "Debugger" in remix, and enter the transcation
4. now it can trace through it - but only in assembly, not in the solidity code.

**Comment by yann300** [comment]
@djrtwo thanks for the details process, fix has been added to https://github.com/ethereum/remix/pull/1270 and soon to remix-alpha.ethereum.org at least.
cc @LianaHus

**Comment by drortirosh** [comment]
> fix has been added to [ethereum/remix#1270](https://github.com/ethereum/remix/pull/1270) and soon to remix-alpha.ethereum.org at least.

How can I test it manually? I tried to clone remix (branch yann300-patch-26) and remix-ide, but it still debug transaction through assembly only. How can it reference solidity code?

**Comment by drortirosh** [comment]
@yann300, I see you closed this PR. is it deployed? How can I see it works?

**Comment by yann300** [comment]
probably today on remix-alpha.ethereum.org

**Comment by drortirosh** [comment]
I still can't trace through ethereum source, even though I see this version was changed (when opening with https connection, it shows an error)
What am I doing wrong?

1. started remix: http://remix-alpha.ethereum.org/#optimize=true&evmVersion=null&version=soljson-v0.5.10+commit.5a6ea5b1.js
2. selected "injected web3" and mainnet
3. I loaded the source of my contract from (https://etherscan.io/address/0xd216153c06e857cd7f72665e0af1d7d82172f494#code) into a new "sol" file
4. verified version and compiled.
5. now I loaded the transaction to debug (0x266761ec3859dcb3b8bb5eafad1488875a5d6a0236a5eb7e51b55bc12ded3ec8)
6. I can trace through the transaction assembly, but it doesn't show source position in the editor.

**Comment by drortirosh** [comment]
Still waiting for some comment, on how to debug tranasction through solidity code...

**Comment by yann300** [comment]
still not merged, will ping here when it is (hopefully today ;) )

**Comment by yann300** [comment]
The fix is deployed in remix-alpha.ethereum.org.
another PR will be pushed some improving the source mapping.

**Comment by drortirosh** [comment]
I'm sorry, this issue was about  how to debug a transaction, and step through the source.
I still didn't get an answer for that, so this  issue should be left **open**.
Its either possible, and only missing documentation - or some more fixes is required.
Currently, debugging through the transaction still only step through the assembly code.

**Comment by yann300** [comment]
I followed the steps above and I could debug through the source code, so I think it is fixed. Let me know..

**Comment by drortirosh** [comment]
@yann300 , 
Yay, indeed, the above tx can be traced (with a small UI glitch of 3-char offset)
strangely, trying to debug a later transaction on the same contract - e.g. 0x5461e16f3cb5b48c6f61de2faf308c31928f4ab82bf191fdca11d13d44ebdaad 
fails.
any idea why?

**Comment by drortirosh** [comment]
I think I found the cause some transaction can't be traced through: It is because the source is not complete: the above failed transaction (0x266761e...) failed inside our `RelayHub` contract.
But the successful transaction `0x5461e16` relayed the request into another contract, which I didn't load the source of.
Once I tracked down the source for that contract and compiled it (which also happened to be in a different compiler version than our relayhub..) , it was possible to trace through.

**Comment by RuslanMirov** [comment]
Hello, when I try do debug, I get this message.

unable to retrieve tx 0xac1525525c1e3774ab598e60d1be6f492a1d1eafd33a488388b0cad3c3494d67

**Comment by kot-begemot** [comment]
I was able to record debugging of a transaction on Ropsten with Remix IDE. Weird thing is I can't do it again, although I am making exactly the same steps. Why? 

![vokoscreen-2020-03-01-12-27-40](https://user-images.githubusercontent.com/780077/75663176-10bf6b80-5c79-11ea-9fb4-1f99517014e4.gif)

**Comment by yann300** [comment]
do you mean that the debugger can't fetch the trace of the transaction?

**Comment by kot-begemot** [comment]
It can fetch it, but now I can't debug it anymore. 

![Selection_705](https://user-images.githubusercontent.com/780077/75663855-35681300-5c7a-11ea-929c-d7671066bf3d.png)

**Comment by yann300** [comment]
it this the same transaction? we don't keep the whole state very long.
Could you retry with a recent transaction?

**Comment by kot-begemot** [comment]
Well, I am checking the Network tab and here are are requests and responses I see (extracted as cURL)

**Request 1:**
```
curl 'https://remix-ropsten.ethdevops.io/' -H 'Referer: https://remix.ethereum.org/' -H 'Origin: https://remix.ethereum.org' -H 'Content-Type: application/json' --data-binary '{"jsonrpc":"2.0","id":956,"method":"eth_getTransactionByHash","params":["0xd8fa66c71065f74e458ca62ab2e2a338f72df9c4929f8f1334aaed5220fba8cc"]}' 
```

Response 1:
```
{"jsonrpc":"2.0","id":956,"result":{"blockHash":"0x9fdd909649005a24ef64866255fe8d9e189756f970ca22441032b15404393655","blockNumber":"0x716474","from":"0xb62bcb140eeaf2d61a0b20c167465f0f80d096dc","gas":"0x1cf03","gasPrice":"0x3b9aca00","hash":"0xd8fa66c71065f74e458ca62ab2e2a338f72df9c4929f8f1334aaed5220fba8cc","input":"0x095ea7b3000000000000000000000000760b97e60a7e2bb133616b58a23b9d29f8b8fe52000000000000000000000000000000000000000000000000163054db2a410000","nonce":"0x13","to":"0xbf17840bf3dd894c5ae66b7635d8104a6977fd53","transactionIndex":"0xa","value":"0x0","v":"0x2a","r":"0x3415e9966d81692539b039ef6256906c931bb377c23c2c22dcbdd24343f26b38","s":"0x7e167f2f41d3856a76bd5b413d976c33db09c9e64363e9972a4a430c0001b9b6"}}
```

**Request 2:**
```
curl 'https://remix-ropsten.ethdevops.io/' -H 'Referer: https://remix.ethereum.org/' -H 'Origin: https://remix.ethereum.org' -H 'Content-Type: application/json' --data-binary '{"jsonrpc":"2.0","id":957,"method":"debug_traceTransaction","params":["0xd8fa66c71065f74e458ca62ab2e2a338f72df9c4929f8f1334aaed5220fba8cc",{"disableStorage":true,"disableMemory":false,"disableStack":false,"fullStorage":false}]}' 
```

Response 2:
```
{"jsonrpc":"2.0","id":957,"error":{"code":-32000,"message":"required historical state unavailable (reexec=128)"}}
```

**Comment by yann300** [comment]
yes please could you try it again with a recent transaction?

**Comment by kot-begemot** [comment]
> yes please could you try it again with a recent transaction?

Same, it says "Empty" where ASM code should be

I have a local Ropsten node, synced as following

```
geth --testnet --rpcapi "eth,debug,net" --rpcaddr 127.0.0.1 --rpcport 8545 -vmdebug --rpc --rpccorsdomain https://remix.ethereum.org
```

I can switch to that one, if needed. I enabled there ** -vmdebug** thinking that will make the trick with this missing state

**Comment by yann300** [comment]
maybe with the `--dev` and `--vmdebug`
could you send the transaction hash? is it ropsten?

**Comment by kot-begemot** [comment]
> maybe with the `--dev` and `--vmdebug`

Geth complains then `Fatal: Flags --dev, --testnet can't be used at the same time`

> could you send the transaction hash? is it ropsten?

Yes, it is Ropsten. Here is contract I was debugging

https://ropsten.etherscan.io/address/0xbf17840bf3dd894c5ae66b7635d8104a6977fd53

Here is a transaction I was debugging in the video

https://ropsten.etherscan.io/tx/0xd8fa66c71065f74e458ca62ab2e2a338f72df9c4929f8f1334aaed5220fba8cc

**Comment by yann300** [comment]
I tried with a very recent tx and debugging was ok, I will check with our devops how to best deal with that...
is your geth node already synced to ropsten?

**Comment by kot-begemot** [comment]
> I tried with a very recent tx and debugging was ok, I will check with our devops how to best deal with that...

Looking forward to an update

> is your geth node already synced to ropsten?

Yes, it is. If needed I can resync. It was ~10 hours for me. No issue there.

**Comment by kot-begemot** [comment]
Any update on that?
