### ISSUE TITLE
Compilation artefact

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#2310]
This section
https://github.com/ethereum/remix-ide/blob/master/docs/contract_metadata.md#build-artifact
should also contains some information about what is in this artefact file:

 - deploy section for linking libraries depending on the current network
 - data section (bytecode, abi, gasestimation, ...)

**Comment by ryestew** [comment]
Similarly in the settings module, where you select to build the json file it currently says:
```
Generate contract metadata. Generate a JSON file in the contract folder. Allows to specify library addresses the contract depends on. If nothing is specified, Remix deploys libraries automatically.
```
But should this say Generate `contract artifact` ?

**Comment by yann300** [comment]
Well yes I suppose so then,
Usually `metadata` does not contain stuff like `bytecode`.. the different between metadata and artefact is really thin tough ...
