### ISSUE TITLE
JS Error when the http://remix.ethereum.org updated recently

### ISSUE THREAD

**Issue by ethbc** [ethereum/remix-ide#2315]
When I open the transaction confirm dialog（the dialog is show you to confirm the gas price） and click the confirm button,I see a js error occurred,so the transaction can't send to the net.
When I want to close the dialog,everything is Invalid ，I must refresh the chrome browser to reload the web.

**Comment by yann300** [comment]
I can't reproduce...
could you drop the Javascript error you get (or PM)

**Comment by yann300** [comment]
are you using metamask or an external node?

**Comment by ethbc** [comment]
> I can't reproduce...
> could you drop the Javascript error you get (or PM)

The wrong js is app.js，line 293053,
"self.udapp._deps.config.setUnpersistedProperty('doNotShowTransactionConfirmationAgain', content.querySelector('input#confirmsetting').checked);"
in modalDialog('Confirm transaction', content....) method, and the error tip is :"Uncaught TypeError: Cannot read property 'config' of undefined".
I used the metamesk。

**Comment by yann300** [comment]
https://github.com/ethereum/remix-ide/pull/2318 fix

**Comment by ethbc** [comment]
sorry , the problem still exists.I've forced the cache to refresh。

**Comment by yann300** [comment]
that's deployed now
