### ISSUE TITLE
Learn more button goes to wrong URL

### ISSUE THREAD

**Issue by kayuzee** [ethereum/remix-ide#2316]
https://remix.ethereum.org 
- Learn more button on homepage links to https://remix.readthedocs.io/en/latest/layout.html which does not work

This should change to https://remix-ide.readthedocs.io/en/latest/layout.html

<img width="1680" alt="Screen Shot 2019-09-03 at 10 59 17 AM" src="https://user-images.githubusercontent.com/19885765/64197279-8073ab80-ce3a-11e9-9094-28d8bcb5dc42.png">

<img width="1680" alt="Screen Shot 2019-09-03 at 10 59 25 AM" src="https://user-images.githubusercontent.com/19885765/64197274-7baef780-ce3a-11e9-9ac3-dd9723ade2fa.png">

**Comment by ryestew** [comment]
I thought we fixed this a while ago.  The link is working now for me.
