### ISSUE TITLE
Remix pending transaction pool

### ISSUE THREAD

**Issue by reterik** [ethereum/remix-ide#2324]
I am using remix to send contracts and the transactions have been pending for over a day.  In general the pending transaction pool is at a peak, and the transaction cost is going up.  Do you know what is causing the backlog? Has ethereum filled up, is the  end nigh?
https://etherscan.io/chart/pendingtx

**Comment by yann300** [comment]
in general we should perhaps warn in remix if the provided gas price is not enough regarding the current load of the network.

**Comment by yann300** [comment]
>  Do you know what is causing the backlog

I don't exactly remember what was the reason of this issue..  but pretty sure it will happen again..
