### ISSUE TITLE
Connection to local remixd repository

### ISSUE THREAD

**Issue by podgostar** [ethereum/remix-ide#2329]
Hi,

I have a recommendation related to Remixd plugin. 

_Current solution:_
To connect to local remixd running daemon the Remixd plugin need to be activated - (OK). But assume that the connection is lost from some reason (i.e., remixd daemon crashes, etc.,) if this happens users need to (1) DEACTIVATE and then (2) ACTIVATE remixd plugin to again establish connection to local remixd node.

_Proposed solution:_
Because after the connection is with local remixd daemon is lost the status of Remixd plugin remains ACTIVATED, there are two possible solutions:
1. Automatically DEACTIVATE Remixd plugin after the connection is lost, so to reconnect user just needs to ACTIVATE it again or
2. Add button to file explorer - "connect to remixd local repo" when Remixd plugin is activated, that users, after the local remixd daemon is re-established, can again connect to local repo, without unnecessary steps (deactivate and activate) related to the plugin.

If I misunderstood something about the current solution feel free to correct me and close the issue.

Best

**Comment by LianaHus** [comment]
deactivate remixd plugin when connection is lost.
for the button https://github.com/ethereum/remix-ide/issues/2297

**Comment by LianaHus** [comment]
closing since it's fixed
