### ISSUE TITLE
file explorers

### ISSUE THREAD

**Issue by wangjiahan** [ethereum/remix-ide#2333]
How do I use file explorers alone

**Comment by LianaHus** [comment]
sorry can you tell me more about your issue? what exactly do you want to do with File explorers?

**Comment by wangjiahan** [comment]
Want to use file upload function, file directory management and file editing function. Pictures uploaded








------------------ 原始邮件 ------------------
发件人: "Liana Husikyan"<notifications@github.com>;
发送时间: 2019年9月18日(星期三) 下午4:27
收件人: "ethereum/remix-ide"<remix-ide@noreply.github.com>;
抄送: "一笑坐对云起时"<1799738687@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ethereum/remix-ide] file explorers (#2333)




sorry can you tell me more about your issue? what exactly do you want to do with File explorers?

**Comment by LianaHus** [comment]
I don't see any pic.
