### ISSUE TITLE
Integrate with oraclize/ethereum-bridge

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#237]
See https://github.com/oraclize/ethereum-bridge

@bertani if you could write this, that would be great 😃

**Comment by chriseth** [comment]
Please add more explanation.

**Comment by axic** [comment]
As far as I understand, the bridge enables one to retrieve data via HTTP requests through Oraclize. It also implements an Ethereum event listener and transaction sender.

This means that contracts running in browser-solidity could interact with Oraclize.

**Comment by chriseth** [comment]
"running in browser-solidity" - do you mean inside the vm? If they run in an actual node I don't see any integration work to be done.

**Comment by axic** [comment]
It would add the Oraclize feature to the VM mode - internally browser-solidity would connect to Oraclize via an HTTP api, but for the contracts running the VM mode the only change is specifying the contract address (the same way they have to select whether they run on testnet or mainnet).

**Comment by bertani** [comment]
I add here some further explanation and a sum up serving as a future reference for readers.

The abovementioned integration is to enable [Oraclize](http://oraclize.it)-based contracts to work when tested in the "VM mode" of browser-solidity. As @chriseth suggests, there is no need for an ad-hoc integration to be done when using browser-solidity along with an actual node ("injected web3"/"web3 provider" modes).
When using the "VM mode", the in-memory vm execution can be interfaced with Oraclize thanks to something similar to our [ethereum-bridge](https://github.com/oraclize/ethereum-bridge) tool (which is already being used for local network deployments, for testrpc, etc..).

Such integration, along with an extra "tab" enabling the inspection of Oraclize queries and results, is now working and being actively maintained in [a dedicated browser-solidity fork here](https://github.com/oraclize/browser-solidity).
At this point we don't have a plugin friendly structure into browser-solidity, so for now I guess it is better to keep it a separate project. Ideally we want this to become a browser-solidity plugin that anybody can install with no need to setup the forked version. In the meanwhile, we are maintaining a [dedicated browser-solidity deployment (in-sync with the github forked repo) here](http://dapps.oraclize.it/browser-solidity/#gist=fb5b158c589aa3b15d1fad44e217349b).
