### ISSUE TITLE
Provide extra details about unit-testing plugin (how it works and restrictions).

### ISSUE THREAD

**Issue by earizon** [ethereum/remix-ide#2408]
https://github.com/ethereum/remix-ide/blob/master/docs/unittesting.md doesn't clarify important aspects about testing.

- I would expect each test to be executed through an external transaction, but it doesn't look to be the case. Correct/false? What is the run-time/context used for testing? 

- What is the expected value of the msg.sender in the contract during testing?

**Comment by LianaHus** [comment]
@Aniket-Engg  @ryestew

**Comment by Aniket-Engg** [comment]
I think we have added lot more details related to unit testing including contexts, points to remember, assert library doc & related examples here https://remix-ide.readthedocs.io/en/latest/unittesting.html
