### ISSUE TITLE
Desktop: link for help / stackexchange is incorrect

### ISSUE THREAD

**Issue by gpersoon** [ethereum/remix-ide#2418]
In the Remix - Desktop version, the help section contains a link to Remix in StackExchange.
This resolves to: 
```JS
https://ethereum.stackexchange.com/?tags=remix
```
However this should be:
```JS
https://ethereum.stackexchange.com/questions/tagged/remix
```

**Comment by LianaHus** [comment]
@gpersoon thanks for the report 
https://github.com/ethereum/remix-desktop/pull/5
