### ISSUE TITLE
Shortcut key to compile

### ISSUE THREAD

**Issue by ethernomad** [ethereum/remix-ide#242]
When auto-compile is disabled it would be great if Ctrl+C compiled the file.

**Comment by axic** [comment]
Ctrl+C shouldn't do that because that's for copy & paste.

**Comment by ethernomad** [comment]
Doh!

**Comment by ethernomad** [comment]
Ctrl+Enter ?

**Comment by yann300** [comment]
ctrl+S is used now for triggering compilation
