### ISSUE TITLE
Solidity compiler: "browser maximum call stack size exceeded"

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-ide#2461]
**Currently working versions:**
OSX + chrome are fine for every version
Win + chrome are fine for > 0.5.2 + 0.4.26
Ubuntu + chrome are fine for 0.4.26 + 0.5.3 + 0.5.4 + 0.5.5
Firefox is fine

**Solutions**:
To fix the problem with chrome in certain browsers we should load blacklisted versions without web worker. Keep in touch with the solidity team to remove from the list rereleased versions later.

Also, we can cash versions already loaded once by user locally to make them load fast in a future.

**Comment by Aniket-Engg** [comment]
Closed #2463
