### ISSUE TITLE
MythX extension: Security analysis results are not scrollable

### ISSUE THREAD

**Issue by b-mueller** [ethereum/remix-ide#2472]
The latest MythX update adds verbose vulnerability information and call traces. However the traces are cut off on the right and there is no horizontal scrolling so there's no way to get the complete calldata in some cases. 

<img width="480" alt="Screenshot 2019-12-03 at 12 25 03" src="https://user-images.githubusercontent.com/5194767/70047460-63c94a00-15c8-11ea-9a92-004ffb49f260.png">

**Possible solutions**

1. Allow horizontal scrolling in the plugin sidebar, or put tx data into a scrollable text field;
2. Accept that this is not possible but add a "copy all" button so the user can get the complete information.

**Comment by yann300** [comment]
closing it now, please reopen if needed
cc @LianaHus
