### ISSUE TITLE
Cursor keeps moving to top of file being edited

### ISSUE THREAD

**Issue by mallapurbharat** [ethereum/remix-ide#2476]
This is an issue since the past two days at least. If I am _**editing**_ the contents of a file, the cursor moves to the top of the active sol file and whatever I type gets placed at the top of the file.

However, turning off "auto-compile" feature solves this issue mostly. Looks like the page gets reloaded or something when auto-compile is selected, and the cursor goes to the top of the file by default.

![cursor-top-move](https://user-images.githubusercontent.com/10878214/70384750-02c7ba80-19aa-11ea-892b-97d4863d0d4f.gif)

**Comment by GustavoContreiras** [comment]
Same here.

Tried Firefox and Chrome on Windows.
Tried Firefox on Ubuntu.

Tried cleaning PC and Browser with CCleaner.

Tried check/uncheck every option from Remix IDE.

Nothing worked.

**Comment by LianaHus** [comment]
Thanks! We are aware of the issue. This will be fixed soon.
