### ISSUE TITLE
Each method interaction is a transaction with Solidity 0.6.0

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-ide#2498]
As per Solidity changelog, `Remove the deprecated constant and payable fields.` 

This is leading to all contract method interaction as transaction. Variable, mapping and method getters are treated as methods changing state.

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-ide/blob/d3f75c88a193f0b302a35d13ad12b59ab49cf407/src/app/ui/universal-dapp-ui.js#L148

**Comment by Aniket-Engg** [comment]
fixed by #2499
