### ISSUE TITLE
update remix logo on home tab

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-ide#2502]

**Comment by LianaHus** [comment]
I was suggesting to create a stickerboard from our and plugin stickers.

**Comment by Aniket-Engg** [comment]
![home_tab](https://user-images.githubusercontent.com/30843294/71398315-0879fd00-2646-11ea-93ec-f29f8d829508.png)

I am talking about this one.

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-ide/pull/2645
