### ISSUE TITLE
Solidity 0.6.* constant methods are shown in orange (in deployed contracts section).

### ISSUE THREAD

**Issue by zemse** [ethereum/remix-ide#2535]
Using Remix IDE v0.9.2

I noticed that ethers.js version 4.0.40 is being used this has this bug. Please refer issue [#688](https://github.com/ethers-io/ethers.js/issues/688). The bug is fixed in immediate next update 4.0.41 (latest is 4.0.43). So I think updating the ethers library might be enough to solve this issue.

**Comment by yann300** [comment]
cc @LianaHus @Aniket-Engg  I think you were working on this right?

**Comment by Aniket-Engg** [comment]
This is fixed by #2499 . @zemse Please check if remix-alpha.ethereum.org works as expected.

**Comment by zemse** [comment]
Thanks for the fix! Also, are these fixes ready to be pushed to the main site yet? Because we are very much dependent on Remix to deploy contracts. We want to deploy a [contract](https://github.com/KMPARDS/certificate-contract/blob/variableNameSize/contracts/CertificateStorage.sol) which needs ABIEncoderV2 and deploying on mainnet seems to be restricted in alpha.

**Comment by zemse** [comment]
Is there a way to enable working with the main network in alpha?

**Comment by zemse** [comment]
Hi, @yann300 @LianaHus @Aniket-Engg, we want to deploy a Solidity 0.6+ contract to mainnet and the main site is giving errors while there are absolutely no issues in the alpha site. 

I understand that it will take time for the community to test the alpha fixes and other features. We have tested the deployment process multiple times using remix alpha on the test net and find the outcome as expected. 

Since we (at our company) are running late for a contract deployment and we are confident to use the alpha in mainnet just for deployment purposes. 

> Is there a way to enable working with the main network in alpha?

**Comment by Aniket-Engg** [comment]
This is fixed and live on remix.ethereum.org. Closing it.
