### ISSUE TITLE
Metadata Inconsistency 

### ISSUE THREAD

**Issue by ligi** [ethereum/remix-ide#2540]
![Selection_323](https://user-images.githubusercontent.com/111600/72587281-f9a90200-38f4-11ea-82c7-f2eb39de5634.png)

How can I check the gateway? I have a local node running - but also get the same error without the gateway.
Also there seems to be some error in the structure of the sentence of the error message there.
Fun fact: publish to swarm gave me this:

![Selection_324](https://user-images.githubusercontent.com/111600/72587884-e6973180-38f6-11ea-8a7d-82e44734b4a9.png)

but after trying to access it I get: 

![Selection_325](https://user-images.githubusercontent.com/111600/72587896-edbe3f80-38f6-11ea-9843-371e28940e9c.png)

**Comment by yann300** [comment]
did you get `metadata inconsistency` while using ipfs or swarm?

**Comment by ligi** [comment]
ipfs

**Comment by yann300** [comment]
could you send me the code you tried to publish?

**Comment by ligi** [comment]
sure https://github.com/goerli/goerli_test_token
