### ISSUE TITLE
Compiler settings not working and solidity.getCompilationResult()

### ISSUE THREAD

**Issue by bmcd87** [ethereum/remix-ide#2543]
@Aniket-Engg I noticed that my plugin (in remix-alpha) was receiving null from its call to client.solidity.getCompilationResult(). So I went digging and saw that CompilerTab is returning  this.compiler.latestCompilationResult:

https://github.com/ethereum/remix-ide/blob/master/src/app/tabs/compile-tab.js#L190

From there I saw that ethereum/remix#1377 converted remix-solidity to typescript, and in doing so moved all the state variables that were located at compiler.xxxx to compiler.state.xxxx. So this seems to be what broke that call, it should be returning this.compiler.state.latestCompilationResult.

I checked a little more and saw that https://github.com/ethereum/remix-ide/blob/master/src/app/tabs/compileTab/compileTab.js is setting all the stuff like optimize, evmVersion, etc on the compiler instance instead of the state object as well. So I don't think any of that is working either (didn't do too much testing, but did see that compiler.optimize was getting out of sync with compiler.state.optimize).

Please take a look when you get a chance, thanks!

**Comment by Aniket-Engg** [comment]
Hi @bmcd87 , regarding setting state parameters, we use this `set` function: https://github.com/ethereum/remix/blob/master/remix-solidity/src/compiler/compiler.ts#L54

Regarding getting the data, i will look into it.
