### ISSUE TITLE
published Metadata missing userdoc (via @notice)

### ISSUE THREAD

**Issue by ligi** [ethereum/remix-ide#2548]
Given a contract where a function has a @notice:

![Selection_333](https://user-images.githubusercontent.com/111600/72850579-b8747180-3ca9-11ea-853d-91dfde0db9bf.png)

here the hashes:
 QmacMxwjUuzpo33DU4A1UJyskicz27R9PtdiPGJtvqAmMa
and 
 QmUQdSeJUz8rN8T29CAJmBsMifasHGqjjBtDjcvNWq2BPb

the metadata published by solidity does not contain the userdoc - but when compiling on the command line with solc (also 0.5.11) I see the userdoc in the metadata. 
Perhaps @chriseth has some hint

**Comment by chriseth** [comment]
Can you check if it is "Compilation Details"?
