### ISSUE TITLE
[HELP] Running remix-ide locally - change default directory

### ISSUE THREAD

**Issue by 27aume** [ethereum/remix-ide#2564]
I am trying to install and run remix locally.
I've followed the installation guide for linux using git. Everything is working well.

Now when I do npm start, remix-ide open with localhost located in  the contracts directory of the installation dir. e.g:
remixd -s home/user/remix-ide/contracts --remix-ide http://127.0.0.1:8080

I'm wondering how to change this and be able to run remix-ide from other projects directories.
Sorry I know its probably basic knowledge. Thank you in advance.
Regards.

**Comment by 27aume** [comment]
I want for this method of using remix. Because I've tried simply connecting to localhost with remixd and i connects but I get
`[WARN] Symbolic link modification not allowed`
When i try to open a file. But I dont have any symlink in my setup. Which makes me unable to use only remixd.

**Comment by sespaces** [comment]
@27aume: I just wrote up an installation how-to that may be of use (https://github.com/sespaces/remix-ide-server-hosting/blob/master/README.md)

From the information you provided, it is too difficult for me to determine where the error is in your current remix-ide installation.

As this problem isn't actually an issue with remix-ide (except needing more documentation), it is likely more appropriate to bring this up in the Gitter channel -- https://gitter.im/ethereum/remix .

Best wishes.

**Comment by yann300** [comment]
@27aume you have to change the paramater `-s` to a new folder.
You could also download https://github.com/ethereum/remix-desktop/releases/tag/v1.0.4 and menu bar click on `open folder`

**Comment by yann300** [comment]
just reopen it if you need more

**Comment by 27aume** [comment]
> @27aume: I just wrote up an installation how-to that may be of use (https://github.com/sespaces/remix-ide-server-hosting/blob/master/README.md)
> 

Thank you appreciate it. Great guide btw :) bookmarked.
