### ISSUE TITLE
Flattener plugin doesn't seem to work

### ISSUE THREAD

**Issue by gpersoon** [ethereum/remix-ide#2566]
When i try to flatten a contract, on either of the following sites:

- https://remix-alpha.ethereum.org/
- http://remix.ethereum.org/

Then it always says I need to compile it, even if i have just done that:
![image](https://user-images.githubusercontent.com/5469459/73593197-83fe8200-4501-11ea-9ad4-2b6d938982f5.png)

In the developer viewer I see the following error message as soon as I activate the flattener
```js
app.js:46 Uncaught (in promise) Error: Message should be a notification, request or response
    at t.<anonymous> (app.js:46)
    at app.js:46
    at Object.next (app.js:46)
    at app.js:46
    at new Promise (<anonymous>)
    at s (app.js:46)
    at t.getMessage (app.js:46)
    at n.listener (app.js:46)
```

**Comment by GrandSchtroumpf** [comment]
Should be solved. Feel free to reopen this issue if you still encounter the issue.
