### ISSUE TITLE
Cannot read property 'getGasPrice' of undefined

### ISSUE THREAD

**Issue by x5engine** [ethereum/remix-ide#2575]
When trying to deploy to mainnet this happens but on Ropsten the smart contract deploys perfectly and works fine.

In the remix logs it shows only 'creation of ContractName.sol pending ...'

![image](https://user-images.githubusercontent.com/12363020/73687430-4e58c500-46ca-11ea-88f4-920a38116815.png)

![image](https://user-images.githubusercontent.com/12363020/73687467-6af4fd00-46ca-11ea-9e4d-f549ff58cea1.png)

![image](https://user-images.githubusercontent.com/12363020/73687548-97107e00-46ca-11ea-8965-1ad9235b028b.png)

**Comment by yann300** [comment]
fix #2577

**Comment by x5engine** [comment]
@yann300 @Aniket-Engg  you are welcome
