### ISSUE TITLE
Editor: incomplete keyword color scheme for Dark theme of Editor

### ISSUE THREAD

**Issue by amany9000** [ethereum/remix-ide#2594]
Hello, the colour scheme of all Dark Themes of Remix are not using separate colour for most keywords like "event", "struct", "string", "address" etc. 

Distinguishing keywords while working help, could you please include it. 

Light Theme has coloured keywords - 
![Screenshot 2020-02-11 at 12 12 07 PM](https://user-images.githubusercontent.com/25260406/74222740-2a553f00-4cdb-11ea-88d8-5250de7961c2.png)

Dark Theme does not. - 
![Screenshot 2020-02-11 at 12 11 59 PM](https://user-images.githubusercontent.com/25260406/74223322-6d63e200-4cdc-11ea-919d-f3074f4a2cb6.png)

**Comment by LianaHus** [comment]
this is done
