### ISSUE TITLE
Example of CallData required for Remix IDE

### ISSUE THREAD

**Issue by zak100** [ethereum/remix-ide#2597]
Hi,
I have posted  question at:
https://ethereum.stackexchange.com/questions/79784/remix-ide-what-is-the-purpose-of-calldata-and-transact-tab

regarding an example for call data. I have put an image on the stack Exchange related to the execution of  a contract on Remix IDE which is asking calldata. If I am putting 10  Ether, I am getting a message in red font that only hash values required. I got the answer:
•  from: address (signed by this)
•  to: address
•  value: uint (ether)
•  data: message data bytes

Kindly provide an example of calldata
Zulfi.

**Comment by LianaHus** [comment]
hi @zak100, this section is to use low level interactions with the contract, like send ethers or/and calldata to receive and fallback functions if any. https://remix-ide.readthedocs.io/en/latest/udapp.html#low-level-interactions

**Comment by LianaHus** [comment]
https://ethereum.stackexchange.com/questions/79855/why-remix-ide-asks-for-calldata-and-what-value-we-have-to-give/79864#79864
