### ISSUE TITLE
Remove i to right of Environment in Deploy & Run

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-ide#2603]
Currently the i - icon to the right of the Environment pulldown menu in Deploy & Run goes to an EIP: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md

We should remove the i - it is not clear what information it is revealing.

**Comment by LianaHus** [comment]
I'm replacing it to https://remix-ide.readthedocs.io/en/latest/run.html#run-setup
