### ISSUE TITLE
Fallback function is not available anymore.

### ISSUE THREAD

**Issue by BogdanVidrean** [ethereum/remix-ide#2608]
The fallback function is not displayed anymore in new remix in the list of functions available for a deployed contract.

How to reproduce:
1) Create a dummy contract using the latest version of solidity:
```
pragma solidity ^0.6.2;
contract derp {
    fallback () external payable {}
}

```

2) Compile it and then deploy it using either the JavaScriptVM or a connection to a Geth node.
3) See that the fallback function is not available.
<img width="1171" alt="Screenshot 2020-02-17 at 20 56 53" src="https://user-images.githubusercontent.com/13217082/74683067-13758780-51c8-11ea-8380-9b1c9d5e51c6.png">

Notes:
1) It doesn't work for 0.5.x versions of Solidity and the new version of Remix.
2) I still use 0.5.9 with old version of Remix and it works perfectly (see below capture)
<img width="1449" alt="Screenshot 2020-02-17 at 20 58 18" src="https://user-images.githubusercontent.com/13217082/74683142-46b81680-51c8-11ea-94c9-cae22c0a7993.png">

**Comment by yann300** [comment]
instead of the fallback function, you can use the "Low level interaction"
