### ISSUE TITLE
deploy code to IPFS

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#2622]
It is now possible to deploy the Solidity source + metadata to IPFS from the compile tab.

This issue is about showing a modal when a deployment is done on mainnet or one of the testnet and offer the user to push source + metadata to IPFS at this moment.

Usually users don't really want to push their source to a public store, in case of the ethereum blockchain, this feeling doesn't really make sense because the bytecode is already public to everyone.

So here is a proposition for the modal:

`Title` : Publish to IPFS.

`Body` : 
`Button` : `Publish to IPFS`
"Why should I do that?"
`By publishing to IPFS, you are making sure that the solidity code will be verified (e.g that the code will be associated with its address). Don't be afraid that everyone will have access to it, because that's anyway already the case: in any case the bytecode is stored transparently in the blockchain.
But allowing users to have access to the source code and its ABI will greatly foster contract adoption (auditing, debugging, calling it, etc...)
`

**Comment by LianaHus** [comment]
as we discussed in gitter channel we will go with checkbox under Deploy button with tooltip

**Comment by LianaHus** [comment]
maybe a bitshorter? "By publishing to IPFS is allowing to verify the contract code. The bytecode is already stored transparently in the blockchain. Publishing the source code and its ABI will greatly foster contract adoption (auditing, debugging, calling it, etc...)

**Comment by LianaHus** [comment]
Writing down the details discussed on standup. 
1. The checkbox should be _disabled_ if VM is checked
2. if the network id is for _Mainnet_, we have it **checked by default**
3. If the network id is for one of the _Testnets_ we **uncheck it by default** 
4. Better save the decision in the localstorage
5. The checkbox should be near **Deploy** button. To be discussed where exactly.

**Comment by yann300** [comment]
looks good, some comments:
 - The contract verification tools (verification.komputing.org) works well for mainnet and testnet, we should check by default in both cases.
 - Sending to ipfs should happen only when the deploy button is hit (not sure that's the case in current PR).
 - No need to display any alert if something fail, logging in the console is enough.

**Comment by yann300** [comment]
just tried the PR, i remove the last comment (that's indeed ok an open a modal showing the ipfs URLs).

**Comment by yann300** [comment]
also, the `deploy to IPFS` checkbox should be close to the Deploy button
