### ISSUE TITLE
Solidity Locals in the debugger

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-ide#2628]
Occasionally the debugger doesn’t show solidity locals - when using the recorder in particular.

**Comment by yann300** [comment]
With no other information, that will be quite complicated to reproduce.
Could you provide a code sample?

**Comment by LianaHus** [comment]
@ryestew

**Comment by yann300** [comment]
@ryestew if you compile the code before starting debugging, it should work. Could you try it and reopen if needed?
