### ISSUE TITLE
web3 is not working in the console 

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-ide#2629]
web3 is not working in the console (e.g do web3.eth.getBlockNumber() or web3.eth.getBalance(“0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c”) it results in a provider error)

**Comment by yann300** [comment]
if you are using the javascript VM that's expected, should work with injected provider
That feature will be added by https://github.com/ethereum/remix-ide/pull/2590 though
