### ISSUE TITLE
using setFile API trigger the toaster 2 time.

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#2642]
When calling the `setFile` from a plugin named `workshop2` (ipfs: QmNzkrogWi8ZDAkPh41cTenSUrdoA3f8qkSM4PFotziRVR) (box plugin (3box) being activated)

 - starting the `helloworld` from `GrandSchtroumpf/solidity-school`
 - toaster shows `box is trying to create or modify HelloWorld.sol` and `workshop2 is trying to create or modify HelloWorld.sol`.

why `box`? this plugin should not update nor change the content of a file.

**Comment by yann300** [comment]
This also happens for other call,
Basically when a call is made from a plugin A to a plugin B.someFunction(),
`someFunction` is called several times. for each call, the `currentRequest` is different.

**Comment by LianaHus** [comment]
this happens twice for vyper but for example once for flattener

**Comment by yann300** [comment]
just retried now, here are the steps for reproducing the issue:
 - start Vyper plugin
 - start ethdoc plugin
 - from vyper plugin, click on "Create Ballot.vy" example
 - `setFile` is called 3 times. one from "scriptRunner", one from "vyper", one from "ethdoc"

**Comment by LianaHus** [comment]
looks like the queue is not cleaned up somewhere

**Comment by yann300** [comment]
some news info about this issue:

 - in https://github.com/ethereum/remix-plugin/blob/v0.2.0/projects/engine/src/plugin/iframe.ts#L72
`AddEventListener` is called each time an iframe plugin is activated. 
Thus the callback is also called x times. Which could be ok, but there's seems to have no way in the code to identify which is the caller, then the call is made x times (one time for each plugin)
 - also the fact that some plugins have the same origin seems to make things worse..

**Comment by yann300** [comment]
That should fix this https://github.com/ethereum/remix-plugin/pull/179
I got it working locally but could someone double check please?
