### ISSUE TITLE
plugin permission typo

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#2663]
`allow` is written as the plugin name

```
solidity permissions:

Allow allow to call quorum

Allow allow to call mythx

Allow allow to call cfg

```

**Comment by LianaHus** [comment]
but then users will loose their saved data. is it fine?

**Comment by yann300** [comment]
they will loose current stored permission, yes I think that's ok

**Comment by yann300** [comment]
they won't loose all the saved data. we need to only clear the stored permission
