### ISSUE TITLE
Incorrect data display for contract method 'call'

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-ide#2686]
Steps to Reproduce:
* Compile & deploy `2_Owner.sol` with `Injected web3`
* call `getOwner` method

Issues:
1. On terminal, it shows call details as:
```
transaction hash | call0xaE55E6A96769C7E472f56358B74C16372021890A0x048672bDb4d8A4e001c667330272324ba3c31aA60x893d20e8
-- | --
from | 0xaE55E6A96769C7E472f56358B74C16372021890A
to | Owner.getOwner() 0x048672bDb4d8A4e001c667330272324ba3c31aA6
hash | call0xaE55E6A96769C7E472f56358B74C16372021890A0x048672bDb4d8A4e001c667330272324ba3c31aA60x893d20e8
input | 0x893...d20e8
decoded input | {}
decoded output | { 	"0": "address: 0xaE55E6A96769C7E472f56358B74C16372021890A" }
logs | []
```
Check `transaction hash` & `hash` details.

2. It shows `0x0000000000000000000000000000000000000000 `  as a result of `getOwner` call which should be an address same as shown in the `decoded output ` of call.

See this for above two issues:
<img width="1198" alt="calldisplay" src="https://user-images.githubusercontent.com/30843294/77753589-d23a8800-704f-11ea-936a-cb124888f0c7.png">

3. I call `getOwner` once again. Now if details are previous call is already expanded and I click on new call to expand details, it does nothing. On browser console, an error is displayed as:

`Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at txDetails (http://remix-alpha.ethereum.org/build/app.js:275834:8)
    at HTMLDivElement._8.onclick (http://remix-alpha.ethereum.org/build/app.js:275733:12)`

I tested it on remix-alpha with ropsten testnet.

**Comment by Aniket-Engg** [comment]
Also on contract deployment, terminal shows tx details as:
<img width="237" alt="constructor" src="https://user-images.githubusercontent.com/30843294/77890992-ebc91300-728d-11ea-8f3f-ab8cd794e6c6.png">
 
Notice the text inside brackets.

**Comment by yann300** [comment]
For the first issue `Check transaction hash & hash details.`
calls doesn't have hash, this is a made up hash, that I think is used for debugging calls when being connected to the `Javascript VM`

**Comment by yann300** [comment]
these section (hash and transaction hash) should probably be removed from the UI (when this is a call)

**Comment by Aniket-Engg** [comment]
> these section (hash and transaction hash) should probably be removed from the UI (when this is a call)

Yes, I agree, we can remove them if we are preparing them manually.

**Comment by yann300** [comment]
1) and 2) fixed by https://github.com/ethereum/remix-ide/pull/2708

**Comment by LianaHus** [comment]
3) fixed by https://github.com/ethereum/remix-ide/pull/2714
