### ISSUE TITLE
Improve UI of unit testing plugin

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-ide#2711]
- [x] Add 'Stop' button to stop running tests
- [x] Add icons to 'Generate test file', 'Run Tests' & 'Stop' buttons
- [x] Remove parentheses from testcase title

**Comment by LianaHus** [comment]
fix checkbox spaces

**Comment by Aniket-Engg** [comment]
May be we can also show/hide all the explanatory text there as revisiting users may like it clean next time.

**Comment by Aniket-Engg** [comment]
fixed by https://github.com/ethereum/remix-ide/pull/2746
