### ISSUE TITLE
Remember and reload local plugins from localstorage

### ISSUE THREAD

**Issue by ioedeveloper** [ethereum/remix-ide#2759]
Currently, remixIde does not support reloading of local plugins after webpage refresh. This will be a nice feature addition to remixIde.

**Comment by LianaHus** [comment]
I'm not sure about this. Soon we will preload solidity environment(https://github.com/ethereum/remix-ide/issues/2795) but currently, our plugins are not mature and some of them are quite heavy(pipeline for example) . Other problem is we don't have "vertical scroll"  in vertical panel yet.

**Comment by LianaHus** [comment]
fixed
