### ISSUE TITLE
Discuss and decide where should generated sample test file reside in file explorer

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-ide#2765]
- decide where should generated sample test file reside in file explorer ( browser/, browser/test, browser/samples/tests/ ... or somewhere else)
- remove dependency from file selection in Unit Testing plugin as it is a UX issue
- update a Unit Testing UI to input path for generate

**Comment by yann300** [comment]
- [ ] put all tests file in a folder by default `tests`.
 - [ ] set a current tests workspace folder.

**Comment by yann300** [comment]
addressed by https://github.com/ethereum/remix-ide/pull/2906
