### ISSUE TITLE
Allow highlighting multiple parts of the code

### ISSUE THREAD

**Issue by fvictorio** [ethereum/remix-ide#2793]
See https://github.com/ethereum/remix-plugin/issues/165

tl;dr we are working on a solhint plugin for remix and when we call `client.editor.highlight` multiple times, only the last one is applied.

**Comment by fvictorio** [comment]
I'm not familiar with `remix-ide` code, but it looks like each highlight is keyed with a `from` property:

https://github.com/ethereum/remix-ide/blob/9bf4f721f8f32b23475d6ababe90d46b92e37e4d/src/app/editor/SourceHighlighters.js#L13

and that `from` is the `currentRequest`:

https://github.com/ethereum/remix-ide/blob/9bf4f721f8f32b23475d6ababe90d46b92e37e4d/src/app/editor/editor.js#L196-L197

Maybe one solution would be to have an optional key to use there, and default to the current request?

**Comment by yann300** [comment]
this is added to the next release and go to remix-alpha soon

**Comment by yann300** [comment]
that's deployed in https://remix-alpha.ethereum.org
the previous highlight is now not discarded and `discardHighlightAt(line, filePath)` has been added
https://github.com/ethereum/remix-plugins-directory/blob/master/common-api/editor/api.ts#L12

**Comment by fvictorio** [comment]
Awesome, thank you!
