### ISSUE TITLE
WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB

### ISSUE THREAD

**Issue by marsrobertson** [ethereum/remix-ide#2794]
Old version, made me switch to the new one.

![image](https://user-images.githubusercontent.com/44369284/80724104-5a9dc400-8af9-11ea-8275-cd110ba51627.png)

> Uncaught RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
    at instantiateSync (soljson-v0.6.6+commit.6c089d02.js:1)
    at Object.createWasm [as asm] (soljson-v0.6.6+commit.6c089d02.js:1)
    at soljson-v0.6.6+commit.6c089d02.js:1
instantiateSync @ soljson-v0.6.6+commit.6c089d02.js:1
createWasm @ soljson-v0.6.6+commit.6c089d02.js:1
(anonymous) @ soljson-v0.6.6+commit.6c089d02.js:1
app.js:22511 Uncaught TypeError: soljson.cwrap is not a function
    at setupMethods (app.js:22511)
    at onInternalCompilerLoaded (app.js:18848)
    at app.js:18863

**Comment by LianaHus** [comment]
hi, I'm sorry we do not support the old version anymore. If you have problems, suggestions to new one please open an issue or contact us in gitter https://gitter.im/ethereum/remix

**Comment by Tectract** [comment]
Hi, I'm getting this error on the newest version of solc-js / solcjson also. Please reopen. I'm unable to compile solidity under Chrome because of this, using [browser-solc](https://github.com/Tectract/browser-solc).
