### ISSUE TITLE
Use Solidity as default (but only if data supports it)

### ISSUE THREAD

**Issue by marsrobertson** [ethereum/remix-ide#2795]
If took me a trip to help the documentation manual.

I was missing some buttons.

Most of the software, most of the products have some sort of defaults.

You can skip configuration, use express settings and intuitively figure out the rest.

In my parallel universe Solidity has 90% (or more) market dominance, Vyper being an experimental thing.

If data supports it, please select Solidity as default.

**Comment by LianaHus** [comment]
@yann300 how this should work with preloaded plugins from URL? should we load all together or only if we don't have the list in URL?

**Comment by yann300** [comment]
The list in the URL as predominance.
yeah so, I think we could by default (and first time the user loads remix) activate the solidity plugin (and perhaps also the run&deploy). Then the list of plugins to activate is the list of previously loaded plugin (same as it is now). If there's something in the URL, then we'd take the list from there (same as it is now).
