### ISSUE TITLE
How to properly interact with the editor from a plugin?

### ISSUE THREAD

**Issue by fernandomg** [ethereum/remix-ide#2806]
Hello, we're currently working on a solhint plugin for remix, and we're facing a couple of issues:

1. when highlighting a section of the file, it works fine but for only one highlight. If we try to highlight several sections, only the last one remains active.

We're calling:
```javascript
      await client.editor.highlight({
        start: {
          line,
          column
        },
        end: {
          line,
          column
        }
      }, filename, '#f00')
```
for every section we want to highlight

2. On the other hand, along with the highlight, we would like to add a breakpoint sign next to the line number, with the possibility of adding an explanation of the error/warning we're highlighting. Is there a way to do this?

**Comment by yann300** [comment]
> On the other hand, along with the highlight, we would like to add a breakpoint sign next to the line number, with the possibility of adding an explanation of the error/warning we're highlighting. Is there a way to do this?

you can add annotation https://github.com/ethereum/remix-plugins-directory/blob/master/common-api/editor/api.ts#L13 let me know if that helps.

closing this as both request should be there.
The first one has been added by https://github.com/ethereum/remix-ide/pull/2815
