### ISSUE TITLE
Solidity compiler doesn't load wasm builds

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#2822]

**Comment by yann300** [comment]
some info that could be useful:
They load just fine for firefox, but for chromium it seems like it would need to switch to loading via webworker. 
In any case they should fix the maximum stack limit/too much recursion issues.

**Comment by LianaHus** [comment]
we are not using webworkers to load a compiler for browsers which do not support them, we also have whitelisted compiler versions to load with worker. I guess we can use wasm builds for those that outside of this list

**Comment by yann300** [comment]
can we use all the wasm build with web worker?

**Comment by LianaHus** [comment]
https://github.com/ethereum/solc-bin/tree/gh-pages/wasm

**Comment by LianaHus** [comment]
"If I rename soljson.js to soljson-v0.6.8.js, I can load it - https://test.ekpyron.org/soljson-v0.6.8.js works, even though it's the same file as https://test.ekpyron.org/soljson.js
So it seems that remix assumes that the URL contains the actual version string."

**Comment by yann300** [comment]
yes but, this issue is about loading wasm builds, doesn't seems related with the URL. modifying the `baseUrl` https://github.com/ethereum/remix-ide/search?q=baseUrl&unscoped_q=baseUrl might already work.
