### ISSUE TITLE
remove base64 images

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-ide#2831]
instead andd to assets/ and use webp for images and svg for icons if possible

**Comment by ryestew** [comment]
For internal plugins 
assets/webp
or 
assets/svg

**Comment by LianaHus** [comment]
well currently we have them flat under assets/img

**Comment by LianaHus** [comment]
we have pngs and webps there

**Comment by ryestew** [comment]
so we should continue to store images: png, svg, webp in
assets/img

**Comment by LianaHus** [comment]
we can have assets/img/png, assets/img/svg and assets/img/webp if you prefer so
