### ISSUE TITLE
I cant enable vyper compiler

### ISSUE THREAD

**Issue by Saater** [ethereum/remix-ide#2839]
I cannot access settings in remix plugin manager, when i click on permission i do see this popup message"No permission requested" where can i request for permission? 
![Screenshot (556)](https://user-images.githubusercontent.com/36656553/82102142-7bc00080-9706-11ea-89f5-a4e7e781e875.png)

**Comment by yann300** [comment]
I see in the screenshot that Vyper is activated, is it not properly showing up when you click on it?

**Comment by LianaHus** [comment]
@Saater please click on Vyper plugin icon on the left icon. do you see any error?

**Comment by LianaHus** [comment]
vyper is not working for me too. I'll tag this as a bug

**Comment by Saater** [comment]
> I see in the screenshot that Vyper is activated, is it not properly showing up when you click on it?

The problem is i can't access plugin manager settings, it showing me the pop up message in the screenshot how can i send the permission request. i learnt i need to enable vyper from the plugin settings.

**Comment by Saater** [comment]
> @Saater please click on Vyper plugin icon on the left icon. do you see any error?

I already added the vyper compiler but i can't compile, i read a tutorial that say i need to enable vyper from the plugin manager settings. problem: i cant access the plugin manager settings to enable vyper to be able to compile vyper codes. in the place of settings it's showing 'permission' instead. so the popup in the screenshot is what i want to be able to figure out; how to send the permission request. thank you.

**Comment by LianaHus** [comment]
you don't need to add permission manually. Vyper will ask for permission. if you denied once you need to remove it from settings but as I see it is not the case here

**Comment by LianaHus** [comment]
@Saater closing the issue. if you need farther support please reopen it
