### ISSUE TITLE
remixd url path

### ISSUE THREAD

**Issue by fritzschoff** [ethereum/remix-ide#2843]
If you want to connect to your file system and use the stated url in the popup
 ![image](https://user-images.githubusercontent.com/39312833/82318528-4ea67300-99d0-11ea-9821-f8738a0604f4.png)
 for `--remix-ide` it doesn't connect. remixd will refuse connection.
only `--remix-ide https://remix.ethereum.org` is working. Maybe you want to state that in the popup?

**Comment by LianaHus** [comment]
The command usage example is already on modal.
