### ISSUE TITLE
Assertion error when switching to compiler version 0.6.0 and above?

### ISSUE THREAD

**Issue by ethernal12** [ethereum/remix-ide#2849]
After I switch to version 0.6.0 or above I get an error

Uncaught Javascript exeption:

Abort (18) Build with -s ASSERTIONS = 1 for more info

What is this error ? I really need to use compiler version 0.6.0 and above, If I switch to compiler versions bellow 0.6.0 the error dissapears ...

**Comment by LianaHus** [comment]
@ethernal12 is it possible to share a piece of code to reproduce the error?

**Comment by ethernal12** [comment]
Sure, note that when I start remix with this code and a compiler version  0.5.7, I switch to version 0.6.0 I get an error:
Uncaught Javascript exception:
typeError: soljson.Pointer_stringify is not a function


Then I switch to a different version , for example : 0.6.1, then back to 0.6.0 I get an error:
Uncaught Javascript exeption:
Abort (18) Build with -s ASSERTIONS = 1 for more info

I hope that I described my problem so its understandable :) 
Im doing a Udemy course and can`t get help from their side so I would really appreciate some help because Im stuck...

```
pragma solidity ^0.6.0;
import "https://github.com/OpenZeppelin/openzeppelincontracts/contracts/access/Ownable.sol";
contract Allowance is Ownable {

 mapping(address => uint) public allowance;

 function setAllowance(address _who, uint _amount) public onlyOwner {
 allowance[_who] = _amount;
 }

 modifier ownerOrAllowed(uint _amount) {
 require(msg.sender == owner() || allowance[msg.sender] >= _amount, "You are not allowed!");
 _;
 }

 function reduceAllowance(address _who, uint _amount) internal ownerOrAllowed(_amount)
{
 allowance[_who] -= _amount;
 }

}
contract SharedWallet is Ownable, Allowance {

 function withdrawMoney(address payable _to, uint _amount) public ownerOrAllowed(_amount) {
 require(_amount <= address(this).balance, "Contract doesn't own enough money");
 if(msg.sender != owner()) {
 reduceAllowance(msg.sender, _amount);
 }
 _to.transfer(_amount);
 }

 receive() external payable {

 }
}

```
Tnx

**Comment by LianaHus** [comment]
thanks!

**Comment by LianaHus** [comment]
hmm.. https://github.com/OpenZeppelin/openzeppelincontracts/contracts/access/Ownable.sol is not there. do you have it already locally?

**Comment by LianaHus** [comment]
can you confirm that you still have errors even with `https://github.com/OpenZeppelin/openzeppelin-contracts/contracts/access/Ownable.sol`

**Comment by LianaHus** [comment]
please reopen if you still have the problem
