### ISSUE TITLE
Can't get remote compiler to kick in..  and plugin setting is now permissions.. but empty

### ISSUE THREAD

**Issue by johnda98** [ethereum/remix-ide#2853]
![Screenshot from 2020-05-26 14-18-25](https://user-images.githubusercontent.com/13384285/82941659-5af47800-9f5c-11ea-9808-72370960a041.png)
anyone get their .vy to compile and deploy.. is this a new bug ?
![Screenshot from 2020-05-26 14-18-45](https://user-images.githubusercontent.com/13384285/82941604-3f896d00-9f5c-11ea-9f78-9c7813d17718.png)

**Comment by yann300** [comment]
At this point, I think you should maybe try to install a local vyper.
https://github.com/vyperlang/vyper
and anyway it is safer for you to use a local compiler..

**Comment by johnda98** [comment]
well today remote compiler button appeared on both firefox and chrome.. :-)

**Comment by johnda98** [comment]
re-opened as remote compiler .. seems to run but no output and no contract listed to deploy.. and re triangle
