### ISSUE TITLE
What framework is this project based on? Is there a guidance document? Watching this all the time this week is uncomfortable and clueless! please!

### ISSUE THREAD

**Issue by daqingchong0809** [ethereum/remix-ide#2857]
What framework is this project based on? Is there a guidance document? Watching this all the time this week is uncomfortable and clueless! please!

**Comment by Aniket-Engg** [comment]
Hello @daqingchong0809 , You can find the remix ide documentation here: https://remix-ide.readthedocs.io/en/latest/
In case of any further queries, you can join gitter: https://gitter.im/ethereum/remix

**Comment by daqingchong0809** [comment]
> Hello @daqingchong0809 , You can find the remix ide documentation here: https://remix-ide.readthedocs.io/en/latest/
> In case of any further queries, you can join gitter: https://gitter.im/ethereum/remix

thank you very much,could you tell me how to deploy remix-ide to my own serve? use 'npm run build' ，the generated package is not deployed successfully.please!!!!!!!!

**Comment by yann300** [comment]
after cloning, best will be to do 
`npm install && npm run build && npm run serve` 
You can also try out https://github.com/ethereum/remix-desktop/releases

**Comment by daqingchong0809** [comment]
> after cloning, best will be to do
> `npm install && npm run build && npm run serve`
> You can also try out https://github.com/ethereum/remix-desktop/releases

Thank you very much. I will try it first. Before that, I used the conventional front-end deployment method to operate it. Maybe I am stupid. Thank you for your reply.

**Comment by daqingchong0809** [comment]
> > after cloning, best will be to do
> > `npm install && npm run build && npm run serve`
> > You can also try out https://github.com/ethereum/remix-desktop/releases
> 
> Thank you very much. I will try it first. Before that, I used the conventional front-end deployment method to operate it. Maybe I am stupid. Thank you for your reply.


After deploying, I opened my own domain name, and the webpage always reported this error:Uncaught SyntaxError: Unexpected token '<'！！！！I checked the information and said there was a problem with the imported file. Have you encountered this problem? Help! Thank you!This problem has troubled me for several days, and when this is solved, I will be happy to die! ! Thank you !!! This is the last question! ! !

**Comment by daqingchong0809** [comment]
> > after cloning, best will be to do
> > `npm install && npm run build && npm run serve`
> > You can also try out https://github.com/ethereum/remix-desktop/releases
> 
> Thank you very much. I will try it first. Before that, I used the conventional front-end deployment method to operate it. Maybe I am stupid. Thank you for your reply.

I've solved it, please trouble you
