### ISSUE TITLE
Use jQuery 3

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#286]
Currently browser-solidity uses jQuery 2.2. It would be nice upgrading to jQuery 3.x.

**Comment by brandonmanke** [comment]
I'd be interested in possibly working on this. Is there anything that would rely on older versions of jquery that would need to be changed?

**Comment by axic** [comment]
I think we're only using basic features. We do have a 2 places using ajax to download files and one place using `unbind`.

**Comment by chriseth** [comment]
What is the benefit of jquery3?

**Comment by axic** [comment]
I think jQuery 3 is a bit more lightweight than the version 2.

The reason jQuery can be useful here is the how familiar devs are with it.

**Comment by chriseth** [comment]
ok, then it makes sense.

**Comment by axic** [comment]
Fixed by #1010.
