### ISSUE TITLE
syntax highlighting of solidity code highlights random things

### ISSUE THREAD

**Issue by saurik** [ethereum/remix-ide#2886]
I started using the remix IDE on a new computer today--Windows 10 with Chrome--and the color scheme of the entire IDE has changed (fwiw, I like it better ;P) but I swear the syntax highlighting used to syntax highlight most keywords, but what I'm currently seeing is it highlighting a small subset of keywords and then function names and parameters (but not identifiers in other contexts)... am I doing something wrong? Is there some plugin I need to configure now?

<img width="507" alt="remix-syntax" src="https://user-images.githubusercontent.com/36743/83941113-89185a00-a79d-11ea-866a-c289d486aaaf.png">

**Comment by LianaHus** [comment]
hmm. is this in alpha or remix.ethereum.org?

**Comment by saurik** [comment]
This was the live site on remix.ethereum.org. (I don't even know how to get an "alpha" ;P.) FWIW, it was broken for a while when I sent that, but I then took a few weeks off from coding solidity and now it seems to be fixed, so I guess I'll close this issue.
