### ISSUE TITLE
Can't see all plugin

### ISSUE THREAD

**Issue by shuzang** [ethereum/remix-ide#2888]
I can not see all avaliable plugin in remix online. All the plugins I can see are as follows
![20200608171355](https://user-images.githubusercontent.com/26682846/84013711-de29bb00-a9ab-11ea-87a6-6280df92b20d.png)

**Comment by yann300** [comment]
which browser/OS are you using? do you have this for other browsers too?

**Comment by shuzang** [comment]
@yann300 Ubuntu 20.04, Chrome and Firefox have all tried, but not for browsers. The reason have found, its network. I can not see all plugins use wired network, but all right in wi-fi hotspots shared by phone. Although I still don't know the deeper reason.
