### ISSUE TITLE
MetaMask: `window.ethereum.enable()`

### ISSUE THREAD

**Issue by TheLoneRonin** [ethereum/remix-ide#2969]
Currently, the Remix IDE does not support the latest version of MetaMask. MetaMask has deprecated the old way to connect to the wallet with the new way which is:

```javascript
window.ethereum.enable()
```

Thus, it would be a good idea to perhaps update the source to use this method instead of the old deprecated way! 👍

**Comment by yann300** [comment]
we are currently doing https://github.com/ethereum/remix-project/blob/3ce30ccb299e439bf2f3c0dbb2b69d8476c73c43/libs/remix-lib/src/execution/execution-context.js#L131 seems like ok, no?
I m closing this, please reopen if I get something wrong
