### ISSUE TITLE
Support more import URLs

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#385]
(Moved from #163.)

e.g.
- ~~`live-libs://<lib>/<version>` (#163)~~
- ~~`bzz://<hash> and bzz://<hash>/<file>` (#357)~~
- ~~`fs:///ipfs/<hash>` (the URL definition of IPFS) (#133)~~
- `mango://<hash or ENS name>/<file or commit hash>` (#460)
- `http://github.com/<user>/<repo>/<path>#<commit hash>` (this is what npm supports)

**Comment by yann300** [comment]
we improved our current resolver to support commit hash and branch name and use resolver-engine as fallback.
