### ISSUE TITLE
Remix naming

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#404]
Since we're thinking to merge the two projects, I think the following layout might make sense:
- remix-core / remix-lib (the common libraries)
- remix-debug aka current remix (the debugger frontend which can be integrated into other projects)
- remix-ide aka browser-solidity (the stand-alone IDE frontend)

@yann300 @chriseth what do you think?

**Comment by chriseth** [comment]
Sounds good! Are you thinking about creating npm packages and / or repositories along this structure?

**Comment by yann300** [comment]
yes that's cool!
what would put in remix-core/-lib? code that is currently in the remix repo but not ui stuff?

**Comment by axic** [comment]
> what would put in remix-core/-lib? code that is currently in the remix repo but not ui stuff?

Yes and possible removing the duplicate items in browser-solidity (perhaps even moving some generic stuff from here).

**Comment by axic** [comment]
> Are you thinking about creating npm packages

Yes, though remix-ide wouldn't need a published package.

> repositories along this structure

Would be nice ultimately.

**Comment by axic** [comment]
@yann300 can you go ahead with renaming this repo to `remix-ide`? It is quite confusing that actual IDE issues are being kept opened on the remix repo.

**Comment by yann300** [comment]
oh yes, actually I always thought it was not possible to rename a repo.. it is actually :)

**Comment by axic** [comment]
It is simple and as long as nobody creates another repo named browser-solidity, it will symlink here. However, not sure that github pages works the same way :(

Perhaps you need to push a page version with a big popup to a new repo callde browser-solidity so that people can migrate their contracts.

**Comment by axic** [comment]
This became a bit more complicated in the last week:
- renaming `yann300.github.com/remix` to `ethereum.github.io/remix-ide-alpha` and `remix-alpha.ethereum.org`
- renaming `browser-solidity` to `remix-ide`

Steps:
- [x] display modal dialogs for all the new addresses on the appropriate urls
- [ ] change build to push to `remix-ide-alpha` instead of `yann300`
- [ ] push a stable build to `browser-solidity/gh-pages`
- [ ] rename `browser-solidity` to `remix-ide`
- [ ] create a new repo called `browser-solidity` and push the previous `gh-pages`  branch
- [ ] update build scripts to `remix-ide`

**Comment by axic** [comment]
Done!
