### ISSUE TITLE
Reading from public functions does not work if msg.value is specified

### ISSUE THREAD

**Issue by villesundell** [ethereum/remix-ide#413]
Consider the following example:

```
contract Sample {
    string public message;
    
    function Sample (string newMsg) payable {
        message = newMsg;
    }
}
```
Now, after deploying the contract, you can now access "message" with, and without supplying msg.value from the settings. Only invocations without the value (0) succeeds. I think it should not take msg.value into account at all when only running the code, right?

**Comment by axic** [comment]
Please see the list of exceptions here: http://solidity.readthedocs.io/en/develop/control-structures.html#exceptions

A contract should not receive ether for a getter function as a security measure.

**Comment by yann300** [comment]
so maybe we should just force the value to 0 when updating property

**Comment by chriseth** [comment]
We should re-think the value input field anyway - it does not make much sense to keep it at the same value across calls. A revamp of the UI should perhaps include a drop-down menu in the function call button where you can specify "call with value".

**Comment by villesundell** [comment]
Yep, and as a fun fact: because function calls are related to transactions, if I have two contracts which I try to deploy at once, the public functions of A are pending while B is under mining.

**Comment by yann300** [comment]
@ninabreznik what about this input field (value) ? there should be something to do here.
also remix should warn when user try to set value to a non payable method ..
