### ISSUE TITLE
Directory structure in files

### ISSUE THREAD

**Issue by chriseth** [ethereum/remix-ide#42]
The current list of files gets messy quite fast, especially if gists are imported and exported. It would be good if we could add a directory structure into the files, so that we can e.g. export only a single directory into a gist and are able to specify a directory we want to import a gist into (or import into a temporary directory by default and have the option to rename).

**Comment by axic** [comment]
Is there any reason we prefix files with `sol-cache-file-`?  Can the key contain characters like `:` and `/`?

If we need a special prefix, suggestion for storage keys: `sol:<path>`

Otherwise just file path: `<path>`

**Comment by axic** [comment]
I think the prefix would become obsolete with #374.

**Comment by chriseth** [comment]
There is no special reason and I don't think there are restrictions on the keys. Please add a prefix, it does not hurt at all and provides much better flexibility.

**Comment by axic** [comment]
Potentially we could add a meta item containing the file permissions (e.g. read only) for the entire file list (or on a per-directory bases).
