### ISSUE TITLE
Swarm import can import non-existing files

### ISSUE THREAD

**Issue by chriseth** [ethereum/remix-ide#437]
If you first use 
`import {Token} from "bzz://b17e450dadb731fd58201ed2c513d9733f8b62dffc6318e4dc30cdb4e1bff186/std/Token.sol";`
and then change it to `import {Token} from "bzz://b17e450dadb731fd58201ed2c513d9733f8b62dffc6318e4dc30cdb4e1bff186/std/Token.solo";` (note the `o` at the end), it still imports successfully. It stops working if you change the hash itself.

**Comment by chriseth** [comment]
@serapath do you want to take a look at this?

**Comment by axic** [comment]
That part is down to the Swarm gateway I'd think? We just pass the whole URL to it and take whatever it returns.

**Comment by LianaHus** [comment]
@yann300  should/can we do anything here?
