### ISSUE TITLE
Support projects hierarchy

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#478]
Each project should have its own files and be able to import from other projects:
- The ballot contract should be in a project called `Ballot`,
- a project called `Untitled` should be created for the user and
- any loaded Gist should become its own project.

The last point also makes the creation of "Import gist" button really simple.

**Comment by axic** [comment]
One the last meeting we've agreed to just use directories for this:
- on fresh instance the first file created is: `Examples/Ballot.sol`
- on creating the first new file, a new project is created: `Untitled/Untitled.sol`
- gists are imported to `<gist-hash>/<files>.sol`

**Comment by LianaHus** [comment]
we have this now
