### ISSUE TITLE
Poll for selected account changes

### ISSUE THREAD

**Issue by danfinlay** [ethereum/remix-ide#482]
Over at MetaMask, [we had a user submit an issue](https://github.com/MetaMask/hello/issues/39#issuecomment-287958410) where they were getting an error from MetaMask after doing the following:

1. Sign into metamask with one account
2. Load Remix
3. Switch metamask account
4. Attempt to publish a contract.

Remix attempts to publish with the first account it detected, instead of checking for a new selected account.

There is not currently any event to listen for, so unfortunately, the recommended method to detect an account change is currently [poll the web3.eth.accounts array](https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#ear-listening-for-selected-account-changes).

**Comment by yann300** [comment]
that's done
