### ISSUE TITLE
ON HOLD Add in-browser version control for files and folders of a project (git)

### ISSUE THREAD

**Issue by serapath** [ethereum/remix-ide#565]
One option to achieve version control for a projects files and folders is to use git inside of the browser.

There seems to be some prior work but they all have problems and don't work out of the box.
* (most promising) [`creationix/js-git`][jsgit] has a variety of tiny modules that make it up and work with it
* [`whylee/nogit`][whylee/nogit]
* [`SamyPesse/gitkit-js`][SamyPesse/gitkit-js]
* [`git-html5.js`][git-html5.js]
* alternative [`dat`][dat]
* alternative [`hyperdrive`][hyperdrive] ([here](https://www.youtube.com/watch?v=ohoR2p0yj5g) is a little introduction to the project)

**Next Steps:**
To make some little [spike](https://en.wikipedia.org/wiki/Spike_(software_development)) and try to see what features are supported and how they work in the browser and what's left missing. Then decide with which project to go and maybe also get in touch with the authors to implement missing features and make it all work

[jsgit]: https://github.com/creationix/js-git
[whylee/nogit]: https://github.com/whyleee/nogit
[SamyPesse/gitkit-js]: https://github.com/SamyPesse/gitkit-js
[git-html5.js]: https://github.com/ryanackley/git-html5.js
[dat]: https://github.com/substack/git-dat
[hyperdrive]: https://github.com/mafintosh/hyperdrive

**Comment by serapath** [comment]
#### Categories for git related libraries on npm
* git init
* gitSSH
* git-fetch-pack (protocol)
* git-apply-delta
* git-create-delta
* git side-band-messages
* git packfile
* git pull/clone/fetch
* github url
* git remote
* git push
* git objects (blob)
* git tree
* git history/walker
* git add/commit
* git stage/index (add)
* git rev
* git repo (abstract)
* git repo
* git odb (object database)
* git fs (git browser storage, github api)
* git log
* git sha1 / secure tag
* git zlib
* git refs tags/branch/head/...
* git status
* git cherry pick
* git checkout
* git config (git ignore)
* git working copy
* git diff
* git conflict (merge/rebase)
* git stash

Each of those categories contains around a dozen libraries that are related to the category name.
Currently I'm trying to put together a minimal version that works in the context of remix re-using libraries where possible and writing some glue code where existing stuff doesnt work. The version won't support all possible git features but just some essentials and more git related features can be added over time.
It also opens the question how to present certain git features in the UI.

**Comment by serapath** [comment]
**Github requests limitation (API)**
* `60 requests per hour for anonymous requests https://developer.github.com/v3/#rate-limiting
* `5000` requests per hour for authenticated requests https://developer.github.com/v3/#schema

---
I was talking with creationix, the author of `js-git`. Since the initial implementation some time has passed.
Not everything is up to date. From what has been implemented, it's possible to use `js-git` in the browser.
* it will use a "virtual file system" (which cannot be backed by localStorage but needs indexDB)
* it can't push/pull to git servers

**Github, Bitbucket & others**
Github and other "git cloud services" don't have CORS set in a way that would allow push/pull/clone of git directories. Instead, they offer a proprietary REST API that can be used and would need adapters to be implemented. What has been done instead is a `js-github` module, that can be mounted as a "virtual file system" in the browser, so working on files would directly work on the github repository instead of locally in the browser.

---

**Current Status**
* I currently have a little test project in which I'm using `js-git` in the browser.
* I'm using an indexDB backed virtual file system.
* I'm running a localhost git server

**The idea:**
* make it possible to push/pull/clone from/to that localhost git server
* once it works - write an adapter that uses the same interface but behind the scenes uses the github api

**Comment by serapath** [comment]
An alternative - which would require users to install `remixd` and `git` would be to don't use git at all, but instead we add some REST endpoints for common commands like `git commit`, `git pull`, `git push`, `git add`, ... basically remote controlling the command line git from the browser

**Comment by serapath** [comment]
Flow: 
* connect Github account (copy-paste token OR login with Github (mini handshake server))
* not anonymous -> 5000 API calls/h
* buttons in Browser solidity editor:
  * git init and git clone
  * git comit -am + message
  * git log --oneline -5 -> go to commit/git checkout
  * git push --force
  * git delete (diconnects locally)

* index DB

**Comment by LianaHus** [comment]
@yann300  can I close this?
