### ISSUE TITLE
Integrate UDapp (universal-dapp.js) better

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#58]
Historically I think UDapp was a fork of some of the initial browser-solidity UI, greatly improved, then it made it back into browser-solidity.

Since it doesn't seem to be used elsewhere, wouldn't it make sense splitting it up and integrating it more closely into the codebase? Even more so given the efforts of @redsquirrel we have a much more manageable app source code.

**Comment by redsquirrel** [comment]
@axic One of my next tasks (been waiting on #51 to be merged) was going to be to start refactoring the UDapp code. My intention is to eventually remove the distinction between app and udapp, in favor of modules with clearer responsibilities. Is that what you have in mind?

**Comment by axic** [comment]
Yes, there's little point having it separate.

I would like to keep a small wrapper managing the *execution context*, which is effectively a wrapper over VM and web3, but doesn't have the rendering responsibilities.
