### ISSUE TITLE
"Error encoding arguments: Error: Assertion failed" on valid transaction call

### ISSUE THREAD

**Issue by Stickerpants** [ethereum/remix-ide#621]
I was attempting to post a transaction using Remix earlier today, and noticed it was rejecting my transaction even though it was valid.

Environment:
* Using "Injected web3" with Metamask 3.9.0
* Using Solidity version 0.4.13+commit.fb4cb1a, with optimization ON

I've written a gist to demonstrate the issue, which can be found here: https://gist.github.com/Stickerpants/d72ff77887c383de71d865055eed4dab

Issue:
I attempt to call the `transfer(address, uint256)` function from an address which does have sufficient balance to transfer, using the amount 10000000000000000 (1e16, or 0.01 assuming 18 decimals). Remix gives back the following message: "Error encoding arguments: Error: Assertion failed".

This message does not appear and the transaction can be successfully posted, if the amount is reduced. I am not sure on the exact threshold that this happens, but I tried 1000000000 (1e-9 assuming 18 decimals) and it successfully works.

Steps to reproduce:
1. Paste the gist into Remix. Use "Javascript VM" as the environment.
2. `Create` TestToken, by passing an address into the constructor. Note that this address is automatically credited `1 * 10**18` tokens by the constructor. I'll refer to this address as `originAddr`.
3. From `originAddr`, attempt to call `transfer` to another address, and the set the transfer value to 10000000000000000 . An example of this might look like: `"0xca35b7d915458ef540ade6068dfe2f44e8fa733c", 10000000000000000 `
4. Observe the returned error message.
5. Attempt another `transfer`, this time using a smaller transfer amount. Example: `"0xca35b7d915458ef540ade6068dfe2f44e8fa733c", 1000000000 `
6. Note that the transaction succeeds.

Other notes:
I am very confident that the transaction itself is valid and does not throw, because I built the transaction data manually by hand and had both Metamask and Parity send it. These transactions did work, my theory is that Remix is having issues parsing the arguments.

Let me know if you need further information. Thanks!

**Comment by yann300** [comment]
yes, we need to have better management of input parameters...
please try ` "0xca35b7d915458ef540ade6068dfe2f44e8fa733c", "10000000000000000" `

**Comment by Stickerpants** [comment]
I see! That's neat, I didn't realize I could quote integers. Thanks!

**Comment by yann300** [comment]
keep opened cause we still need to make all this more flexible

**Comment by Hu4F00d** [comment]
Was having the same problem. Solved it by adding double quotes to every integer argument.

**Comment by srameshr** [comment]
Damn!
I spent 6 hours debugging this!

**Comment by ferittuncer** [comment]
Please provide a documentation on how to pass inputs. Spending 2 hours for this is INSANE.

**Comment by LianaHus** [comment]
https://remix-ide.readthedocs.io/en/latest/udapp.html#passing-in-a-tuple-or-a-struct-to-a-function
