### ISSUE TITLE
refactoring app.js

### ISSUE THREAD

**Issue by serapath** [ethereum/remix-ide#701]
~~* [ ] get rid of renderer.js cause it is just an helper now.~~
* [x] move the editor-resize section (line 420 app.js) away . in editor.js i guess...
* [x] get rid of loadVersion (line 994 - app.js) and move to the settings tabs.
* [x] chromeCloudSync (line 280) but that should in his own file i guess (btw could you check how it works?)
~~* [ ] refactor all the resizing functions.~~
* [x] UniversalDapp does not trigger anymore `debugRequested`, we should remove the comment and the registering to that event.
~~* [ ] Test and refactor `Copy file to another instance~~
```
window.addEventListener('message', function (ev) {
    if (typeof ev.data === typeof [] && ev.data[0] === 'loadFiles') {
      loadFilesCallback(ev.data[1])
    }
  }, false)
```
 * [x] move gistHandler.handleLoad to helper
 * [x] check whether every function API are actually used and remove unused
 * [x] move `OffsetToLineColumnConverter` to editor.js

**Comment by yann300** [comment]
* [ ] move `loadingFromGist` to helper

**Comment by yann300** [comment]
* [ ] check whether every function API are actually used and remove unused

**Comment by yann300** [comment]
@serapath could you check please what is already done / should be done here?
