### ISSUE TITLE
Menu (Status) Bar

### ISSUE THREAD

**Issue by serapath** [ethereum/remix-ide#714]
We will soon have some kind of "terminal" to execute commands or script the "remix IDE" and also to see the history (past) of what happens in the app in form of a log.

In many places we have the phenomenon of creating expectations of the future, like when the app is loading, or when the app is compiling, but also when transactions and other things are "pending".

#### Proposal
Let's make a "statusbar" for the remix IDE so there is a place where we can notify the user and show him a summary of what's currently happening inside the app. Everything in the app can inform the status bar and the status bar would be a visual collection of those.

Currently the app has several panels and each panel has some kind of menubar.
The statusbar would go into the app's overall menu bar (which currently does not exist yet)

**Comment by yann300** [comment]
yes that something that could be cool to add in the future. let's use this issue to list what we can put in the status bar.

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-ide/issues/2961
