### ISSUE TITLE
Publish to Gist should include actual link to browser-solidity which includes the gist link

### ISSUE THREAD

**Issue by raineorshine** [ethereum/remix-ide#75]
When I click "Publish to gist" it creates a proper gist, but the link in the description is broken:

> Created using browser-solidity: Realtime Ethereum Contract Compiler and Runtime. Load this file by pasting this gists URL or ID at https://ethereum.github.io/browser-solidity/#version=soljson-latest.js&optimize=undefined&gist=

e.g. https://gist.github.com/anonymous/74ba1d4ebfb740b03ced838519617613

**Comment by raineorshine** [comment]
Wait, I just read that over... is that my design, and it's really just asking the user to do it manually instead of generating the link automatically?

**Comment by axic** [comment]
I think it is by design because at the time creating the gist, you do not know what the gist hash will be.

I do see two bugs there:
- `optimize=undefined` should be a boolean
- and there should be an indication after `gist=`, i.e. `gist=<your gist url>`

**Comment by raineorshine** [comment]
You can just wait for the gist to be created, get the id, then [edit the gist](https://developer.github.com/v3/gists/#edit-a-gist).

**Comment by axic** [comment]
@raineorshine would you be able to submit a PR for that?

I think the code would need to go somewhere around here: https://github.com/ethereum/browser-solidity/blob/master/src/app.js#L110

**Comment by raineorshine** [comment]
> It looks like you can't edit an anonymous gist, and in order to use it authenticated, you need to generate a token API for your account and specify that you want to use with gist in the scope.
(http://stackoverflow.com/questions/17129465/update-a-gist-through-its-api)

Not sure the best way to handle this... should browser-solidity create gists from an authenticated account in this case? Does it have a server-side to store the Auth token?

**Comment by axic** [comment]
@raineorshine Github Pages is the server side, so you cannot easily store tokens there.

Perhaps if we could access the "referrer"  and see it came from a specific gist, that could be loaded?

**Comment by raineorshine** [comment]
The problem is with saving the url of the gist in the gist itself (so that it links back to browser-solidity), and doing so at gist creation time, since we cannot edit an anonymous gist.

What about just using gist as a back-end, and not exposing it to the user? Change `&gist=...` to `&id=` and the user never needs to know.
