### ISSUE TITLE
Editor: cmd + L clobbers browser shortcut

### ISSUE THREAD

**Issue by raineorshine** [ethereum/remix-ide#76]
On OSX + Chrome, go-to-line is mapped to `Cmd + L` which is a much-used shortcut in the browser to move the cursor to the address bar. I have seen most editors avoid overriding this shortcut and instead using something like `Cmd + Ctrl + G` or `Cmd + Alt + G` (for **go** to line).

**Comment by Denton-L** [comment]
This seems to be an issue with the editor we're using, `brace`.

**Comment by axic** [comment]
The question is how much we want to deviate from the ACE editor standards.

Would could certainly change `Ctrl + L` (= `Cmd + L`) to `Ctrl + Shift + L` (`Cmd + Shift + L`).

**Comment by chriseth** [comment]
I think it is better to just remove the shortcut. If we change it, nobody will find it.

**Comment by orgy** [comment]
as mentioned in a different thread, why not allow users to select whether or not they want to clobber? ive personally never used ctrl/cmd+L to use the address bar so i wouldn't mind using it to go to line

**Comment by chriseth** [comment]
@orgy yes, good idea! Still, I think the default setting should be not to hijack browser shortcuts.

**Comment by ckshei** [comment]
I can help work on this if we'd like to make this change
