### ISSUE TITLE
make room for gfx element

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#767]
to replace the actual quite unuseful small remix icon

**Comment by yann300** [comment]
we would use this issue to find a better way to display gfx.
yann300.github.io/remix (soon to be pushed to remix.ethereum.org) already displays icon in a nicer way (in the terminal).
@ianmeikle @ryestew @ninabreznik 
any ideas welcome :)

**Comment by yann300** [comment]
that 's issue is also kind of related to the https://github.com/ethereum/browser-solidity/issues/706 (making remix ui themable)

**Comment by ianmeikle** [comment]
![remix_1](https://user-images.githubusercontent.com/8150714/30380178-cc1fa6ce-9890-11e7-8f62-5661ea5b568a.jpg)
![remix_2](https://user-images.githubusercontent.com/8150714/30380179-cc38ddec-9890-11e7-8014-91a5430dc29c.jpg)
![remix_3](https://user-images.githubusercontent.com/8150714/30380182-cc471bfa-9890-11e7-9f37-cb2e77184e34.jpg)
![remix_4](https://user-images.githubusercontent.com/8150714/30380180-cc452bc4-9890-11e7-9085-4f25f2ca3c38.jpg)
![remix_5](https://user-images.githubusercontent.com/8150714/30380184-cc56dcfc-9890-11e7-837f-b1e83ff89850.jpg)
![remix_6](https://user-images.githubusercontent.com/8150714/30380181-cc45d1be-9890-11e7-966d-1571b8edf8a3.jpg)
![remix_7](https://user-images.githubusercontent.com/8150714/30380183-cc48b398-9890-11e7-8eb4-fc4501d2173c.jpg)

**Comment by ianmeikle** [comment]
Yann What do you make of these so far

**Comment by ianmeikle** [comment]
![remix_8](https://user-images.githubusercontent.com/8150714/30650444-ca99ac2a-9e1a-11e7-9745-ae9e17975b0d.jpg)
![remix_9](https://user-images.githubusercontent.com/8150714/30650453-cf073f5c-9e1a-11e7-80c7-ec0e508e1f9d.jpg)

**Comment by ianmeikle** [comment]
Which you prefer guys?

**Comment by ianmeikle** [comment]
![remix_10](https://user-images.githubusercontent.com/8150714/30651136-b581a1b0-9e1c-11e7-8231-8348610e405a.jpg)

**Comment by ianmeikle** [comment]
![remix_11](https://user-images.githubusercontent.com/8150714/30656527-59a5c69a-9e2c-11e7-9927-76a98800b72b.jpg)

**Comment by ianmeikle** [comment]
![remix_12](https://user-images.githubusercontent.com/8150714/30656821-41fc4bee-9e2d-11e7-964c-9153b772e426.jpg)

**Comment by ianmeikle** [comment]
I am actually a fan of the flat artwork not so much the shiny stuff

**Comment by ianmeikle** [comment]
![remix_13](https://user-images.githubusercontent.com/8150714/30668027-4f6fa5b8-9e51-11e7-8d9e-f9b38f7568cc.jpg)
