### ISSUE TITLE
weird slowness

### ISSUE THREAD

**Issue by mrsmkl** [ethereum/remix-ide#768]
For some reason the compilation time of this program doubles when a new if branch is added. The weird thing is that with the native compiler, it just compiles instantly no matter how many branches I add.
```
pragma solidity ^0.4.15;

contract Test {
    function test(uint hint, uint r1, uint r2, uint r3) returns (uint) {
        uint res;
        if (hint == 2 || hint == 3 || hint == 4 || hint == 5) {
            if (r1 == r2 || r2 == r3) res = r1;
        }
        if (hint == 2 || hint == 3 || hint == 4 || hint == 5) {
            if (r1 == r2 || r2 == r3) res = r1;
        }
        if (hint == 2 || hint == 3 || hint == 4 || hint == 5) {
            if (r1 == r2 || r2 == r3) res = r1;
        }
    }
}
```

**Comment by yann300** [comment]
what do you mean by native compiler? 
@chriseth @axic ?

**Comment by mrsmkl** [comment]
Just Solidity compiled from C++ to normal linux executable.

**Comment by chriseth** [comment]
@mrsmkl are you sure the optimizer settings are the same in both ways to compile?

**Comment by axic** [comment]
@mrsmkl also make sure you are using the exact version (you can download a static Linux binary in the release).

**Comment by mrsmkl** [comment]
Static binary didn't work for me, but I tested the Trusty zips. Command line:
```
Version: 0.4.16+commit.d7661dd9.Linux.g++
./solc --bin slow.sol > asd  0,02s user 0,02s system 105% cpu 0,030 total
Version: 0.4.16+commit.d7661dd9.Linux.clang
./solc --bin slow.sol > asd  0,02s user 0,00s system 52% cpu 0,030 total
./solc --bin --optimize slow.sol > asd  0,12s user 0,03s system 101% cpu 0,153 total
./solc --bin --optimize --optimize-runs=20000 slow.sol > asd  0,14s user 0,02s system 100% cpu 0,155 total
```

In browser https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.16+commit.d7661dd9.js: 
```
Your current Solidity version is
0.4.16+commit.d7661dd9.Emscripten.clang
Optimization off: Last compilation took 28336ms. We suggest to turn off autocompilation.
Optimization on: Last compilation took 27242ms. We suggest to turn off autocompilation.
```
I can see from JS profiler that most of the time is spent in soljson.js, but the names are mangled so I cannot find out more.

**Comment by chriseth** [comment]
Hm, interesting, so the emscripten compiler is faster when optimization is turned on? Perhaps that is just a bug in the time measurement of browser-solidity?
