### ISSUE TITLE
small UI changes

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#824]
- [x] RUN TAB: fix design for info and save/re-run transactions etc. (smaller size, black/on hover orange => same as other icons => see style guide)
![screenshot 2017-12-13 at 2 57 02 am](https://user-images.githubusercontent.com/1076427/33905532-7bd26f72-dfb1-11e7-9793-b1ba4bf68346.png) 
- [x] RUN TAB: replace `clear instances list` icon with `trash bin`
![screen shot 2017-12-13 at 11 43 07 pm](https://user-images.githubusercontent.com/1076427/33953651-464e5b2e-e068-11e7-9ade-9917af905da5.png)
- [x] TERMINAL: same color of running transaction logs (grey not black) + width 75%
![screen shot 2017-12-13 at 11 43 13 pm](https://user-images.githubusercontent.com/1076427/33952705-3b3ee148-e065-11e7-93c6-c039b78d1ddb.png)
- [x] TERMINAL: add expand/collapse logic to transaction logs (with a caret) instead of details button (whole log should be clickable and the caret changes when extended)
- [x] TERMINAL: make titles bold (from, to etc.)
![screen shot 2017-12-13 at 11 43 07 pm](https://user-images.githubusercontent.com/1076427/33952865-a9d68eee-e065-11e7-8f51-27d226b740e2.png)
- [x] RUN TAB: fix responsiveness  
![screen shot 2017-12-13 at 11 42 50 pm](https://user-images.githubusercontent.com/1076427/33952668-22053952-e065-11e7-9c40-b9b6c8160c46.png)
![screen shot 2017-12-13 at 11 42 39 pm](https://user-images.githubusercontent.com/1076427/33952671-22656890-e065-11e7-8c70-c7ca11ad1e7e.png)
![screen shot 2017-12-13 at 11 42 21 pm](https://user-images.githubusercontent.com/1076427/33952673-22ab97de-e065-11e7-9413-9b72199391cd.png)

 - [x]  reset action to remove list of contracts instances
 - [x] warn in the run tab that the compilation failed.
 - [x] display event id in tx `details`
 - ~~[ ] display gas costs even if the tx fails~~.
 - [x] display gas costs for call also (only VM) https://github.com/ethereum/browser-solidity/issues/845
 - [x] add Successfully copied after Copy-top-Clipboard is clicked
 - [x] in `details`, replace `interface` by `interface - abi`.

**Comment by ninabreznik** [comment]
All tasks done
