### ISSUE TITLE
Support Chat

### ISSUE THREAD

**Issue by serapath** [ethereum/remix-ide#839]
> @PhuNHNexttech @/all the support chat is a very recent (new) feature in the remix app. It's open source and free of charge.
We currently develop it with a small team and lack resources for giving full time support to everyone - especially given that there are a lot of people joining the support channel since it was added to the remix app. I don't know if that will change in the future. So when there is nobody around to help out personally, you can try to look into the documentation and of course we hope, that the community might help each other out too ...if that starts to happen a lot, then that might be the benefit of having more and more people in the channel 

Answered to by:
> **Ayushya Chitransh 06:51**
> @serapath IMHO This or a similar message should be displayed below the support chat!
> Oh I see! There is a message!

Maybe we should adapt the current message to make it more clear what people can expect from the chat. Maybe even make something bold - because maybe most people miss the message?

**Comment by yann300** [comment]
@serapath closing that one . please reopen if you think there's still something to do here
