### ISSUE TITLE
Have a welcome popup on first visit

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#875]
Basically if the localstorage is empty, consider it as "first visit" (we create the config that point anyway).

This popup should have a few guidance messages, such as explaining which tab does what and that auto compilation be turned on (so that #874 is not a problem).

**Comment by axic** [comment]
Also we should already have a welcome popup when localstorage is unavailable (such as Safari private mode). Likely that could be integrated into the same popup.

**Comment by yann300** [comment]
instead of a popup, having a real content that will replace the current Remix view (and containing links to doc, more explanations, ...) would be really nice.
@ninabreznik @ryestew
