### ISSUE TITLE
Remix does not redirect to https

### ISSUE THREAD

**Issue by maurelian** [ethereum/remix-ide#897]
I can visit either http://remix.ethereum.org or https://remix.ethereum.org, and when I do I have different files stored in the cache. 

This is quite confusing!

**Comment by wowa1983** [comment]
Bitte hilfe

**Comment by axic** [comment]
@maurelian this is also a problem or feature with using ethereum.github.io/browser-solidity. I think it would be a good idea to redirect all of them to a single URL (preferable https://remix.ethereum.org), but there is one rather significant issue with this: if redirecting, content stored in the alternative URLs is not easily accessible for users.

It can be introduced as a soft change though with warning (popup) when using the "non-canonical" URL.

**Comment by axic** [comment]
@yann300 what do you think?

**Comment by maurelian** [comment]
@axic good point about people losing their content. 

> It can be introduced as a soft change though with warning (popup) when using the "non-canonical" URL.

Seems reasonable, that would at least help people understand why they don't have the same contracts as before.

**Comment by yann300** [comment]
We can't use `web3 Provider` and browse `https` at the same time. 
so we can't redirect to `https` by default . I don't see any easy solution to this yet ...

**Comment by maurelian** [comment]
Since the only side effect for the user of visiting http vs. https is the files available in the cache, I would suggest just a simple label on the file folder in either situation:

![image](https://user-images.githubusercontent.com/23033765/33324875-d3059178-d41e-11e7-9a1e-6653408275e1.png)

**Comment by axic** [comment]
> Since the only side effect for the user of visiting http vs. https is the files available in the cache, I would suggest just a simple label on the file folder in either situation:

That would definitely make sense even in case people think their files are lost (because they went to the wrong http/https). Perhaps adding a tooltip explaining it is worth?

**Comment by maurelian** [comment]
A tooltip would be useful I think, as long as it has a slight delay.  My suggestion for the directory label would still be useful for calling awareness to the issue in general.

**Comment by yann300** [comment]
we display a notification if `https` is used (already pushed to remix.ethereum.org)
