### ISSUE TITLE
Add support of Solhint linter for code validation

### ISSUE THREAD

**Issue by idrabenia** [ethereum/remix-ide#907]
Hi Guys,

We develop code linter that provide:
1. Strict source code validation according [Solidity Style Guide](http://solidity.readthedocs.io/en/develop/style-guide.html)
2. Security code check using [ConsenSys Guide for Smart Contracts](https://consensys.github.io/smart-contract-best-practices/recommendations/)
3. Best practices code validation

We think that it would be very helpful for community to integrate capabilities of our linter to browser-solidity.

We may create a PR. What do you think?

Thanks!
\- Ilya

**Comment by yann300** [comment]
We are actually thinking how we could integrate external tooling in Remix. 
So yes that is a good idea. We need to check in which part of the remix code base the integration can be done. getting back to you asap!

**Comment by yann300** [comment]
is the linter is in a github repo?

**Comment by yann300** [comment]
We are testing some solution to include external plugins to Remix. we'll get back to you asap

**Comment by idrabenia** [comment]
Hi @yann300 ,

Thank you for your interest!

Yes, there is a repo https://github.com/protofire/solhint 
This is a [medium blog post](https://medium.com/@ProtoFire_io/solhint-an-advanced-linter-for-ethereums-solidity-c6b155aced7b) about Solhint.

I think it would very helpful for community to make integration in any way - as external plugin or as core part (to work both with static analyzer).


\- Ilya

**Comment by yann300** [comment]
@idrabenia what's the best way to PM you?

**Comment by yann300** [comment]
is there something that we should do to help for the integration
@serapath @idrabenia

**Comment by yann300** [comment]
@idrabenia are you still interested on providing this linter?
Please PM at gitter/yann300
