### ISSUE TITLE
Separate inputs for functions into separate components, 1 per argument

### ISSUE THREAD

**Issue by VoR0220** [ethereum/remix-ide#953]
Currently, it's incredibly difficult to work with the input functionality of Remix as I have to go and add them all on one line. This not only reduces readability, but it makes it very difficult to know what place I'm actually in and forces me to spend more time going back and forth with arrow keys to make sure that I'm inserting it into the correct place. 

Tl;dr

Current design:

inputs here: "argument1", 13094220490340294, "l33t#4x0r5"

Proposed design:

(Function call button, turned off until all values are filled)
- Arg1: [insert value here]
- Arg2: [insert value here]

**Comment by yann300** [comment]
Yes that's a good idea and we need to address that since long time cause the current situation is not good (the fact that hex has to be wrapped too is bad).
We also need to think of a way to collapse inputs list when being out of focus.
@ryestew  could you take a look at this too ?
