### ISSUE TITLE
Can't compile old contract using old version of compiler

### ISSUE THREAD

**Issue by tomsib2001** [ethereum/remix-ide#959]
Hi,
I've been trying to compile and analyze the so-called "Block King" contract, which can be found on [Etherscan](https://etherscan.io/address/0x3ad14db4e5a658d8d20f8836deabe9d5286f79e1#code). However, I can't find a way to run the compiler which is claimed to have produced the EVM code currently on the blockchain, namely version v0.2.1-2016-02-10-7b5d96c. I have tried to specify this version in the remix IDE but nothing happens when I try to compile it.

**Comment by yann300** [comment]
this fix should do the trick https://github.com/ethereum/solc-js/pull/168

**Comment by tomsib2001** [comment]
Hi, thanks for the quick response! Has the fix been pushed to https://remix.ethereum.org/? It still has the same behaviour as previously.

**Comment by yann300** [comment]
it has been pushed for sure by now
