### ISSUE TITLE
Connecting to remote Web3 provider

### ISSUE THREAD

**Issue by chainhead** [ethereum/remix-ide#975]
From the Run option in the IDE, I tried connecting to a `geth` node that exposes RPC port on a public IP address by entering `http://public-ip-address:7545`. I have set-up reverse proxy using Apache such that traffic at 7545 is directed to `http://localhost:8545`. The `geth` itself is running as shown below.

```
geth --mine --testnet --rpc --rpcaddr "localhost" --rpcport "8545" --rpcapi "web3,eth" --rpccorsdomain "http://localhost:8545"
```
However, the connection keeps failing with this error message.

> Not possible to connect to the Web3 provider. Make sure the provider is running and a connection is open (via IPC or RPC).

So, is it possible for the Remix IDE to connect to a remote `geth` node that exposes an RPC port?

**Comment by nostdm** [comment]
You might wanna try using `--rpccorsdomain "*"` setting it to `localhost:8545` doesn't make much sense. 

https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

**Comment by chainhead** [comment]
That option didn't work.

> You might wanna try using --rpccorsdomain "*" setting it to localhost:8545 doesn't make much sense:

I thought, with reverse proxy setting, the `--rpccorsdomain "http://localhost:8545"` was to be used. If you wouldn't mind, can you please take a look into the following settings?

### Apache settings
The following is in my `/etc/apache2/sites-enabled/000-default.conf`
```

<VirtualHost *:80>
        ServerName public-ip-address
        ErrorLog ${APACHE_LOG_DIR}/error-80.log
        CustomLog ${APACHE_LOG_DIR}/access-80.log combined
        Header set Access-Control-Allow-Origin "*"
        Header set Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept"
        ProxyPreserveHost On
        ProxyPass / http://127.0.0.1:8080/
        ProxyPassReverse / http://127.0.0.1:8080/
</VirtualHost>

<VirtualHost *:7545>
       ServerName public-ip-address
       ErrorLog ${APACHE_LOG_DIR}/error-7545.log
       CustomLog ${APACHE_LOG_DIR}/access-7545.log combined
       Header set Access-Control-Allow-Origin "*"
       Header set Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept"
       ProxyPass / http://localhost:8545/
       ProxyPassReverse / http://localhost:8545/
</VirtualHost>

```

### Remix settings
From the Run panel, I enter the IP address as `http://public-ip-address:7545` I am thinking, with reverse proxy in effect, the traffic will be redirected by the Apache server to `geth` at 8545.

### No constraint settings
With `--rpcaddr "0.0.0.0"` and `--rpccorsdomain "*"`, I don't see this error message. But, under the drop-down for Environment, I see a message as 

> Can't detect network

**Comment by yann300** [comment]
try leaving out `--rpcaddr "0.0.0.0"`

**Comment by yann300** [comment]
@chainhead is this working better when if you remove `--rpcaddr "0.0.0.0"`

**Comment by chainhead** [comment]
@yann300 No that didn't help.

**Comment by pzagor2** [comment]
@chainhead Are you using https://remix.ethereum.org or your own instance of Remix IDE on localhost? 

Try using non HTTPS version http://remix.ethereum.org/

Checkout out this issue: https://github.com/ethereum/browser-solidity/issues/897

**Comment by chainhead** [comment]
@pzagor2 The aim is to connect to a Remix instance running on an public IP address. From the Run setting in the IDE, I provide the address as `http://public-ip-address:7545`. A reverse proxy setting is done such that, the traffic of port 7545 is redirected to 8545 where `geth` is running.

Since the above set-up did not work, I tried connecting to `http://public-ip-address:7545` and `http://public-ip-address:8545` from Remix IDE at `http://remix.ethereum.org` and `https://remix.ethereum.org`. Neither seem to be working. :(

Kindly advise.

**Comment by chainhead** [comment]
@yann300 are we looking at a time-frame to resolve this?

**Comment by yann300** [comment]
I just tried connecting to a public IP and that worked. could you request the web3 API `public-ip-address:7545` and check if you have a connection ? please PM me @yann300 in gitter

**Comment by mark-win** [comment]
I don't know if that is the case for apache reverse proxys, but I do know that nginx does have some trouble with "index" definitions, only blocking OPTIONS requests from reaching their target.

Did you inspect network traffic in your browsers' network monitor? (Firefox: Ctrl + Shift + E or Command + Option + E on a Mac)
You can filter for XHR if you want, to boil down the output to mostly only requests against the API address you tell remix. The first Request to the API should be an OPTIONS Request to '/'. What do the response headers look like? Good ones should look something like this:
```
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: POST
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 600
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Date: Fri, 26 Jan 2018 20:46:09 GMT
Origin, Access-Control-Request-Method, Access-Control-Request-Headers
```
The * should be the value of whatever you entered into the `--rpccorsdomain` parameter.

**Comment by chainhead** [comment]
@mark-win Finally, got around to test this. This is what I have.

### Commands
With this command, I am able to get Remix to connect to `geth`.
```
geth --rpc --rpcaddr "0.0.0.0" --rpcport "8545" --rpcapi "web3,eth,net,debug" --rpccorsdomain "*" --testnet
```
With the reverse proxy version, it does not work for me.
```
geth --rpc --rpcaddr "localhost" --rpcport "8545" --rpcapi "web3,eth,net,debug" --rpccorsdomain "http://localhost:7545" --testnet
```

This is the request header - there is no response.
### Request
```
OPTIONS / HTTP/1.1
Host: aws-public-ip:7545
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Origin: http://aws-public-ip
Connection: keep-alive
```

**Comment by prashantprabhakar** [comment]
I am also facing the same issue. Hosted a private geth instance on Digital Ocean with the following command:

`geth --identity "1337" --cache=1024 --rpc --rpcport "8013" --rpcaddr "0.0.0.0" --rpccorsdomain "*" --datadir "myPrivateNetwork"  --rpcapi "personal,eth,admin,miner,web3,db" --datadir "myPrivateNetwork" --port "30312" -networkid 1902 --nat "any" --ipcpath "/home/prashant/.ethereum/geth.ipc" console
`


Now when I try to connect remix running on my local browser with:
`http://<server-public-ic>:8013
`
I can see my accounts in accounts list along with balances, but unable to deploy any contract.  The Environment says: **web3 Provider can't detect network**.

Is there any solution to this?

**Comment by xlog2n** [comment]
you say: I have set-up reverse proxy using Apache
you must configure cross-domain information in Apache httpd.conf
because remix-ide help you visit web3 provider. their domain or ports are different.

**Comment by kggp1995** [comment]
@chainhead , you may wanna check your firewall rules. Could that geth node be a new VM & you missed setting up the firewall inbound rules for port 8545?

**Comment by dinuni** [comment]
geth --networkid 1234 --rpc --rpcport 8545 --rpcapi "db, net, web3, personal" --rpccorsdomain "*" --rpcaddr "0.0.0.0" --testnet console 
allows me to connect to Remix

**Comment by yann300** [comment]
closing this now . please reopen if necessary.
I think that could likely be due to firewall rules

**Comment by DMNV** [comment]
Hi
 I have the same question so if I use this command for create public ethereum node, please tell me is there is any changes to be done this cmd line 
use azure VM,

### geth --identity "Four.Exchange.Node" --rpc --rpcport 8080 --rpcaddr "127.0.0.1" --rpccorsdomain "*" --datadir four.exchange.node --port 30303 --nodiscover --rpcapi db,eth,net,web3,personal,txpool --networkid 1 console

**Comment by sagarpomal** [comment]
It can be a cross-origin issue, try installing a chrome cross-origin plugin and then try again.

**Comment by MaazAhmedZ** [comment]
I need help, cant install npm install -g ethereumjs-testrpc ..... how can i fix this? i have ganache. i'm very new to this, please help!
npm install -g ethereumjs-testrpc
npm WARN deprecated ethereumjs-testrpc@6.0.3: ethereumjs-testrpc has been renamed to ganache-cli, please use this package from now on.
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.npm/_logs/2018-08-16T18_31_47_433Z-debug.log

**Comment by kggp1995** [comment]
I recommend to use ganache-cli.
However, if need be to use testrpc, prefix  that command with sudo. That
may do it.

**Comment by MaazAhmedZ** [comment]
and I can connect to remix, environment web3 provider . this show up 
Not possible to connect to the Web3 provider. Make sure the provider is running and a connection is open (via IPC or RPC).
please help 
I have ganache with 10 accounts, nodejs, metamask and atom. what am I doing worng? should i uninstall everything? and re-do it ?

**Comment by yann300** [comment]
is ganache running when you try to connect? does it display the rpc port?

**Comment by MaazAhmedZ** [comment]
yes its running and the rpc server HTTP://127.0.0.1:7545

**Comment by stvenyin** [comment]
Thank you very much.

**Comment by macizomedia** [comment]
Allow unsafe script on chrome, try to find same fuction on firefox.

Source https://www.youtube.com/watch?v=58yeu6HtzpM
