### ISSUE TITLE
Hosting Remix IDE with a geth node on a server

### ISSUE THREAD

**Issue by nostdm** [ethereum/remix-ide#981]
I've installed a `geth` node on a server and also set up the remix IDE but apparently when I use it to connect to `localhost`, it goes to my laptop's `localhost` not my server's `localhost`.

Is there a way to set up the IDE so that it connects to the node running directly on the server?

**Comment by yann300** [comment]
when you swith to `web3 provider` you have to input your server url, not localhost

**Comment by wowa1983** [comment]
Gips dafür fasthub patch code

Am 08.01.2018 11:26 schrieb "yann300" <notifications@github.com>:

**Comment by wowa1983** [comment]
Versuche sd storage rapair ausfüren

Am 08.01.2018 11:29 schrieb "Vladimir Galliardt" <wladigall@gmail.com>:

**Comment by chainhead** [comment]
@nostdm Keen to know your progress. I raised an issue as I wasn't able to connect to a remote `geth` node #975

**Comment by yann300** [comment]
starting geth with:
`geth --rpc --rpccorsdomain="*" --rpcapi web3,eth,debug,personal,net --vmdebug --ipcpath /home/testchains/test2/geth.ipc --datadir /home/testchains/test2/ --dev console`
should be enough to connect to remix.
closing this now, please reopen if necessary
