### ISSUE TITLE
Modal Dialog Improvement

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#986]
- [ ] `Enter` should confirm the modal
- [ ] `Esc` should close it
- [ ] clicking outside should close it

**Comment by up730418** [comment]
Hi, 
Are you still looking for someone to fix the Enter and Esc parts of this issue.
If so i would be happy to take them on.

**Comment by yann300** [comment]
please do

**Comment by yann300** [comment]
it think the ` clicking outside should close it` is still to do

**Comment by up730418** [comment]
ok i will look at that as well
