### ISSUE TITLE
Uncaught TypeError: Cannot read property 'transactionHash' of undefined

### ISSUE THREAD

**Issue by dean-kim** [ethereum/remix-ide#996]
Problem
Using http://ethereum.github.io/browser-solidity/#optimize=false&version=soljson-v0.4.19+commit.c4cbbb05.js I've connected to my own Ethereum node remotely by RPC.
It looks well - I see successful requests in Network tab of my browser.
but I clicked 'Create' return console message
Here is console message:

```
Uncaught TypeError: Cannot read property 'transactionHash' of undefined
    at Object.callback (app.js:155754)
    at app.js:126221
    at app.js:147716
    at XMLHttpRequest.request.onreadystatechange (app.js:146519)
(anonymous) @ app.js:155754
(anonymous) @ app.js:126221
(anonymous) @ app.js:147716
request.onreadystatechange @ app.js:146519
XMLHttpRequest.send (async)
HttpProvider.sendAsync @ app.js:146528
RequestManager.sendAsync @ app.js:147710
send @ app.js:126220
tryTillResponse @ app.js:155745
(anonymous) @ app.js:155685
(anonymous) @ app.js:126221
(anonymous) @ app.js:147719
request.onreadystatechange @ app.js:146519
XMLHttpRequest.send (async)
HttpProvider.sendAsync @ app.js:146528
RequestManager.sendAsync @ app.js:147710
send @ app.js:126220
(anonymous) @ app.js:155680
(anonymous) @ app.js:126221
(anonymous) @ app.js:147719
request.onreadystatechange @ app.js:146519
XMLHttpRequest.send (async)
HttpProvider.sendAsync @ app.js:146528
RequestManager.sendAsync @ app.js:147710
send @ app.js:126220
TxRunner.execute @ app.js:155661
run @ app.js:155765
TxRunner.rawRun @ app.js:155629
runTransaction @ app.js:161547
next @ app.js:161467
(anonymous) @ app.js:161525
getAddress @ app.js:151220
queryAddress @ app.js:161522
next @ app.js:161467
(anonymous) @ app.js:161512
getValue @ app.js:151238
queryValue @ app.js:161509
next @ app.js:161467
(anonymous) @ app.js:161497
getGasLimit @ app.js:151244
queryGasLimit @ app.js:161494
next @ app.js:161467
execute @ app.js:161469
UniversalDApp.runTx @ app.js:161485
createContract @ app.js:154339
(anonymous) @ app.js:159132
buildData @ app.js:154499
createInstance @ app.js:159129
_6.onclick @ app.js:159097
```

**Comment by wowa1983** [comment]
Kannst du mir helfen wie ich das korigire habe neue Bundle installiert Java habe IMS Syntax Fehler gehabt habe korrigiert jetzt ims und weiß nicht wie weiter kannst mir beschreiben wie ich denn Befehl ausführe mit Python Danke schön mal shin shin ;)

**Comment by wowa1983** [comment]
Please helps

**Comment by wowa1983** [comment]
Ich schaue gleich nach Moment pc hoch fahren Java Befehle kann Mann auch mit Python befehlen oder

**Comment by wowa1983** [comment]
?

**Comment by wowa1983** [comment]
im sorry habe das korigiert

**Comment by yann300** [comment]
hmm which Ethereum node are you using?

**Comment by yann300** [comment]
@dean-kim  ^

**Comment by wowa1983** [comment]
Wie kann ich das Befehlen und mit welches Modul?pydroid? Mein Desktop lässt
das nicht scrollen auf b.sodalited

Am 24.01.2018 17:57 schrieb "yann300" <notifications@github.com>:

**Comment by yann300** [comment]
we need here to fix the test `if (!err && !result) {` and to retry if error is !null || if result is null
https://github.com/ethereum/browser-solidity/blob/master/src/app/execution/txRunner.js#L194

**Comment by yann300** [comment]
the fix has been pushed. could you double check please? thanks
closing now, please reopen if necessary

**Comment by dean-kim** [comment]
@yann300 thx, I checked, and work well~!
